create or replace view XXAP_SUPPLIER_MASTER_V
as
select 
    xasv.ORG_ID,
    xasv.VENDOR_ID,
    xasv.VENDOR_SITE_ID,
    nvl(xasv.PARTY_SITE_ID,-1) PARTY_SITE_ID,
    nvl(xsbv.EXT_BANK_ACCOUNT_ID,-1) EXT_BANK_ACCOUNT_ID,
    xsbv.BANK_ID,
    xsbv.BRANCH_ID,
    xasv.OPERATING_UNIT_NAME,
    xasv.VENDOR_NUMBER,
    xasv.TCC_VENDOR_ID,
    xasv.PAYMENT_PURPOSE,
    xasv.VENDOR_NAME,
    xasv.ALTERNATE_VENDOR_NAME,
    xasv.VENDOR_TYPE,
    xasv.PAYMENT_METHOD,
    xasv.INVOICE_CURRENCY_CODE,
    xasv.INVOICE_MATCH_OPTION,
    xasv.PAYMENT_CURRENCY_CODE,
    xasv.PAYMENT_PRIORITY,
    xasv.TERMS_NAME,
    xasv.TERMS_DATE_BASIS,
    xasv.PAY_DATE_BASIS,
    xasv.PAY_GROUP,
    xasv.ALWAYS_TAKE_DISCOUNT,
    xasv.REMIT_TO_EMAIL,
    xasv.VENDOR_SITE_CODE,
    xasv.PURCHASING_SITE_FLAG,
    xasv.PAYMENT_SITE_FLAG,
    xasv.COUNTRY_CODE,
    xasv.ADDRESS_LINE1,
    xasv.ADDRESS_LINE2,
    xasv.ADDRESS_LINE3,
    xasv.ADDRESS_LINE4,
    xasv.CITY,
    xasv.PROVINCE,
    xasv.POSTAL_CODE,
    xasv.PHONE_AREA_CODE,
    xasv.PHONE,
    xasv.FAX_AREA_CODE,
    xasv.FAX,
    xasv.EMAIL,
    xasv.SITE_LIABILITY_ACCOUNT,
    xasv.SITE_PREPAYMENT_ACCOUNT,
    xasv.SITE_SHIP_TO_LOCATION,
    xasv.SITE_BILL_TO_LOCATION,
    xasv.SITE_PAYMENT_METHOD,
    xasv.SITE_INVOICE_TOLERANCE,
    xasv.SITE_INVOICE_MATCH_OPTION,
    xasv.SITE_INVOICE_CURRENCY_CODE,
    xasv.SITE_SERVICES_TOLERANCE,
    xasv.SITE_PAYMENT_CURRENCY,
    xasv.SITE_PAYMENT_PRIORITY,
    xasv.SITE_PAY_GROUP,
    xasv.SITE_TERMS_NAME,
    xasv.SITE_TERMS_DATE_BASIS,
    xasv.SITE_PAY_DATE_BASIS,
    xasv.SITE_ALWAYS_TAKE_DISCOUNT,
    xsbv.BANK_ACC_START_DATE,
    xsbv.BANK_ACC_END_DATE,
    xsbv.BANK_ACC_PRIORITY,
    xsbv.BANK_ACC_COUNTRY_CODE,
    xsbv.ALLOW_INT_PAYMENTS,
    xsbv.BANK_NAME,
    xsbv.BANK_ALT_NAME,
    xsbv.BANK_NUMBER,
    xsbv.BRANCH_NAME,
    xsbv.BRANCH_ALT_NAME,
    xsbv.BRANCH_NUMBER,
    xsbv.BIC,
    xsbv.BRANCH_TYPE,
    xsbv.BANK_ACCOUNT_NUM,
    xsbv.BANK_ACCOUNT_NAME,
    xsbv.BANK_ACCOUNT_CURRENCY,
    xsbv.BANK_ACCOUNT_TYPE,
    xsbv.ACCOUNT_OWNERS,
    xsbv.OWNER_PRIMARY_FLAG,
    xsbv.OWNER_END_DATE
from 
    XXAP_SUPPLIERS_V xasv,
    XXAP_SUPPLIER_BANKS_V xsbv
where xasv.org_id = xsbv.org_id (+)
and xasv.vendor_id = xsbv.vendor_id (+)
and xasv.vendor_site_id = xsbv.vendor_site_id (+)
and nvl(xasv.party_site_id,-1) = nvl(xsbv.party_site_id(+),-1)
;
