--drop view xxap_invoice_list;

CREATE VIEW XXAP_INVOICE_LIST_V
AS
SELECT --DISTINCT
    AIA.ORG_ID ORG_ID,
    HOU.NAME OPERATING_UNIT_NAME,
    APS.VENDOR_ID,
    APS.VENDOR_NAME,
    APSS.VENDOR_SITE_ID,
    APSS.VENDOR_SITE_CODE,
    AIA.INVOICE_ID,
    AIA.INVOICE_NUM INVOICE_NUMBER,
    AIA.INVOICE_DATE,
    AIA.INVOICE_CURRENCY_CODE INVOICE_CURRENCY_CODE,    
    AIA.INVOICE_AMOUNT INVOICE_AMOUNT,    
    --AIA.EXCHANGE_RATE,
    --AIA.EXCHANGE_RATE_TYPE,
    --AIA.EXCHANGE_DATE,
    AIA.BASE_AMOUNT INVOICE_FUNC_AMOUNT,
    --DECODE(AIA.PAYMENT_STATUS_FLAG,'N','UN-PAID','P','Partial Paid','Y','PAID') PAYMENT_STATUS_FLAG,
    --APT.NAME TERM_NAME,
    ACA.CHECK_DATE INVOICE_SETTLEMENT_DATE,  
    --AIA.DESCRIPTION HEADER_DESCRIPTION,
    --APSA.PAYMENT_METHOD_CODE,
    --AIA.PAY_GROUP_LOOKUP_CODE,
    PHA.PO_HEADER_ID PO_HEADER_ID,
    PHA.SEGMENT1 PO_NUMBER,
    PHA.CLOSED_CODE PO_STATUS,
    PHA.CURRENCY_CODE PO_CURRENCY_CODE,
    (select SUM(NVL(UNIT_PRICE, 0) * NVL(QUANTITY, 0)) from PO.PO_LINES_ALL where PO_HEADER_ID = PHA.PO_HEADER_ID) PO_AMOUNT, 
    (select SUM(NVL(UNIT_PRICE, 0) * NVL(QUANTITY, 0)) from PO.PO_LINES_ALL where PO_HEADER_ID = PHA.PO_HEADER_ID) * NVL(PHA.RATE,1) PO_FUNC_AMOUNT,     
    RCV.SHIPMENT_ID RCPT_ID,
    RCV.RECEIPT_AMOUNT RCPT_AMOUNT,
    RCV.RECEIPT_AMOUNT * NVL(PHA.RATE,1) RCPT_FUNC_AMOUNT,
    RCV.LATEST_RECEIPT_DATE RCPT_DATE,
    EE1.FULL_NAME PO_BUYER_NAME,
    EE1.EMPLOYEE_NUMBER PO_BUYER_EMPLOYEE_NUMBER
--    GCC.CONCATENATED_SEGMENTS LIABILITY_ACCOUNT,
--    APSA.AMOUNT_REMAINING,
--    NVL(ROUND(APSA.AMOUNT_REMAINING*AIA.EXCHANGE_RATE,2),APSA.AMOUNT_REMAINING) HKD_EQ,
--    (SELECT DISTINCT POSTED_FLAG FROM AP.AP_INVOICE_DISTRIBUTIONS_ALL
--     WHERE INVOICE_ID = AIA.INVOICE_ID) POSTED_TO_GL
FROM
    AP.AP_INVOICES_ALL AIA,
    AP.AP_SUPPLIERS APS,
    AP.AP_SUPPLIER_SITES_ALL APSS,
    PO.PO_HEADERS_ALL PHA,
    APPS.GL_CODE_COMBINATIONS_KFV GCC,
    AP.AP_PAYMENT_SCHEDULES_ALL APSA,
    AP.AP_TERMS_TL APT,
    HR.HR_ALL_ORGANIZATION_UNITS HOU,
--   AP.AP_INVOICE_LINES_ALL aila
     HR.PER_ALL_PEOPLE_F EE1,
     (
        SELECT 
            RSL.PO_HEADER_ID RCV_PO_HEADER_ID,
            MAX(RSL.CREATION_DATE) LATEST_RECEIPT_DATE,
            MAX(RSL.SHIPMENT_LINE_STATUS_CODE) RECEIPT_STATUS,
            MAX(RSH.SHIPMENT_HEADER_ID) SHIPMENT_ID,
            MAX(RSH.RECEIPT_NUM) RECEIPT_NUM,
            SUM(NVL (RSL.QUANTITY_RECEIVED, 0) * NVL (PLA.UNIT_PRICE, 0)) RECEIPT_AMOUNT
        FROM 
        PO.RCV_SHIPMENT_HEADERS RSH,
        PO.RCV_SHIPMENT_LINES RSL,
        PO.PO_LINES_ALL PLA
        WHERE RSH.SHIPMENT_HEADER_ID = RSL.SHIPMENT_HEADER_ID
        AND RSL.PO_LINE_ID = PLA.PO_LINE_ID
        GROUP BY RSL.PO_HEADER_ID
    ) RCV,
    AP.AP_INVOICE_PAYMENTS_ALL AIPA, 	
    ap.AP_CHECKS_ALL ACA
WHERE AIA.VENDOR_ID = APS.VENDOR_ID
--and aia.invoice_id = aila.invoice_id
--AND   aia.payment_status_flag = 'Y'
AND   AIA.VENDOR_SITE_ID = APSS.VENDOR_SITE_ID
AND   APS.VENDOR_ID = APSS.VENDOR_ID
AND   AIA.QUICK_PO_HEADER_ID = PHA.PO_HEADER_ID (+)
AND   AIA.ACCTS_PAY_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
AND   APSA.INVOICE_ID = AIA.INVOICE_ID
AND   APT.TERM_ID = AIA.TERMS_ID
AND   HOU.ORGANIZATION_ID = AIA.ORG_ID
and AIA.INVOICE_ID = AIPA.INVOICE_ID (+)
and AIPA.CHECK_ID = ACA.CHECK_ID (+)
and ACA.VOID_DATE IS NULL
--AND   aia.INVOICE_DATE between '01-JAN-21' and '31-MAR-21'
AND PHA.AGENT_ID  = EE1.PERSON_ID (+)
AND  AIA.QUICK_PO_HEADER_ID  = RCV.RCV_PO_HEADER_ID (+)
ORDER BY AIA.INVOICE_NUM
;
