CREATE OR REPLACE VIEW XXPO_LIST_V
AS
SELECT 
    PHA.ORG_ID ORG_ID,
    PHA.PO_HEADER_ID PO_HEADER_ID,
    PLA.PO_LINE_ID PO_LINE_ID,
    PDA.PO_DISTRIBUTION_ID PO_DIST_ID,
    AAS.VENDOR_ID VENDOR_ID,
    PPA.PROJECT_ID PROJECT_ID,
    HOU.NAME OPERATING_UNIT_NAME,
    PHA.SEGMENT1 PO_NUMBER,
    PHA.REVISION_NUM REVISION_NUM,
    PHA.ENABLED_FLAG    ENABLED_FLAG,
    PHA.CREATION_DATE   ORDER_DATE,
    PHA.CURRENCY_CODE   CURRENCY_CODE,
    PHA.RATE            EXCHANGE_RATE, 
    PHA.CLOSED_CODE         HEADER_STATUS,
    PHA.APPROVED_FLAG   APPROVAL_FLAG,
    AAS.VENDOR_NAME         VENDOR_NAME,
    AAS.VENDOR_TYPE_LOOKUP_CODE     VENDOR_TYPE,
    PLA.LINE_NUM    LINE_NUM,
    PLA.UNIT_PRICE          LINE_UNIT_PRICE,
    PLA.ITEM_DESCRIPTION    LINE_DESC,
    PLA.CLOSED_CODE         LINE_STATUS,
    PDA.QUANTITY_ORDERED    DIST_QTY,
    PDA.QUANTITY_BILLED     DIST_QTY_BILLED,
    CHG_GCC.SEGMENT1            CHARGE_ACC_SEG1,
    CHG_GCC.SEGMENT2            CHARGE_ACC_SEG2,
    CHG_GCC.SEGMENT3            CHARGE_ACC_SEG3,
    CHG_GCC.SEGMENT4            CHARGE_ACC_SEG4,
    CHG_GCC.SEGMENT5            CHARGE_ACC_SEG5,
    CHG_GCC.SEGMENT6            CHARGE_ACC_SEG6,
    DIST_CHG_GCC.SEGMENT1       DIST_ACC_SEG1,
    DIST_CHG_GCC.SEGMENT2       DIST_ACC_SEG2,
    DIST_CHG_GCC.SEGMENT3       DIST_ACC_SEG3,
    DIST_CHG_GCC.SEGMENT4       DIST_ACC_SEG4,
    DIST_CHG_GCC.SEGMENT5       DIST_ACC_SEG5,
    DIST_CHG_GCC.SEGMENT6       DIST_ACC_SEG6,
    PDA.EXPENDITURE_TYPE        DIST_EXP_TYPE,
    PPA.SEGMENT1              PROJECT_NUMBER,
    PPA.DESCRIPTION           PROJECT_NAME,
    PPF.FULL_NAME             BUYER_NAME,
    REQ_PPF.FULL_NAME         REQUESTOR_NAME,
    REQ_GCC.SEGMENT1          REQUESTOR_EXP_SEG1,
    REQ_GCC.SEGMENT2          REQUESTOR_EXP_SEG2,
    REQ_GCC.SEGMENT3          REQUESTOR_EXP_SEG3,
    REQ_GCC.SEGMENT4          REQUESTOR_EXP_SEG4,
    REQ_GCC.SEGMENT5          REQUESTOR_EXP_SEG5,
    REQ_GCC.SEGMENT6          REQUESTOR_EXP_SEG6
FROM
    HR_ALL_ORGANIZATION_UNITS HOU,
    PO.PO_HEADERS_ALL       PHA,
    PO.PO_LINES_ALL         PLA,
    PO.PO_DISTRIBUTIONS_ALL PDA,
    GL.GL_CODE_COMBINATIONS CHG_GCC,
    GL.GL_CODE_COMBINATIONS DIST_CHG_GCC,
    GL.GL_CODE_COMBINATIONS REQ_GCC,
    AP.AP_SUPPLIERS         AAS,   
    PA.PA_PROJECTS_ALL      PPA,
    PER_ALL_PEOPLE_F        PPF,
    PER_ALL_PEOPLE_F        REQ_PPF,
    (select * from per_all_assignments_f where effective_end_date = '31-DEC-4712') REQ_PAF
WHERE   HOU.ORGANIZATION_ID = PHA.ORG_ID
AND     PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
AND     PHA.PO_HEADER_ID = PDA.PO_HEADER_ID
AND     PLA.PO_LINE_ID = PDA.PO_LINE_ID
AND     PDA.CODE_COMBINATION_ID = CHG_GCC.CODE_COMBINATION_ID
AND     PDA.DEST_CHARGE_ACCOUNT_ID = DIST_CHG_GCC.CODE_COMBINATION_ID (+)
AND     PHA.AGENT_ID = PPF.PERSON_ID
AND     PDA.DELIVER_TO_PERSON_ID = REQ_PPF.PERSON_ID (+)
AND     REQ_PPF.PERSON_ID = REQ_PAF.PERSON_ID
AND     REQ_PAF.DEFAULT_CODE_COMB_ID = REQ_GCC.CODE_COMBINATION_ID (+)
AND     PHA.VENDOR_ID = AAS.VENDOR_ID
AND     PDA.PROJECT_ID  = PPA.PROJECT_ID (+)
--AND     ((PHA.CLOSED_CODE IS NULL) OR (PHA.CLOSED_CODE = 'OPEN' ))
--AND     ((PLA.CLOSED_CODE IS NULL )OR PLA.CLOSED_CODE <> 'CLOSED')
;
