--drop table tableauetl.XXAP_EXPENSE_REPORT;

  CREATE TABLE "TABLEAUETL"."XXAP_EXPENSE_REPORT" 
   (	
    "ORG_ID" NUMBER(15,0) ,    
    "EXPENSE_REPORT_ID" NUMBER(15,0) , 
	"REPORT_HEADER_ID" NUMBER(15,0) , 
	"REPORT_LINE_ID" NUMBER(15,0), 
	"REPORT_DISTRIBUTION_ID" NUMBER(15,0), 
	"PROJECT_ID" NUMBER(15,0), 
	"OPERATING_UNIT_NAME" VARCHAR2(240 BYTE),         
	"REPORT_NUMBER" VARCHAR2(50 BYTE), 
	"REPORT_SUBMITTED_DATE" DATE, 
    "GL_DATE" DATE, 
	"EXPENSE_STATUS_CODE" VARCHAR2(30 BYTE), 
	"RECEIPTS_STATUS" VARCHAR2(30 BYTE), 
	"DEFAULT_CURRENCY_CODE" VARCHAR2(15 BYTE) , 
	"TOTAL" NUMBER , 
	"FULL_NAME" VARCHAR2(240 BYTE), 
	"EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
	"PURPOSE" VARCHAR2(240 BYTE), 
	"OVERRIDE_APPROVER_NAME" VARCHAR2(240 BYTE), 
	"REPORT_TYPE" VARCHAR2(25 BYTE) , 
	"DISTRIBUTION_LINE_NUMBER" NUMBER(15,0), 
	"EXPENSE_TYPE" VARCHAR2(240 BYTE) , 
	"START_EXPENSE_DATE" DATE, 
	"END_EXPENSE_DATE" DATE, 
	"RECEIPT_CURRENCY_AMOUNT" NUMBER, 
	"RECEIPT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"RECEIPT_CONVERSION_RATE" NUMBER, 
	"LINE_AMOUNT" NUMBER, 
	"JUSTIFICATION" VARCHAR2(240 BYTE), 
	"MERCHANT_NAME#1" VARCHAR2(240 BYTE), 
	"DIST_AMOUNT" NUMBER, 
	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"TASK_NUMBER" VARCHAR2(25 BYTE), 
	"CONCATENATED_SEGMENTS" VARCHAR2(155 BYTE), 
	"ITEMIZATION_PARENT_ID" NUMBER,
    CONSTRAINT "XXAP_EXPENSE_REPORT_PK" PRIMARY KEY ("ORG_ID", "EXPENSE_REPORT_ID", "REPORT_HEADER_ID", "REPORT_LINE_ID","REPORT_DISTRIBUTION_ID")
   ) TABLESPACE "USERS";

CREATE OR REPLACE PUBLIC SYNONYM XXAP_EXPENSE_REPORT FOR TABLEAUETL.XXAP_EXPENSE_REPORT;
