--drop table XXAP_FUNDING;

  CREATE TABLE "TABLEAUETL"."XXAP_FUNDING" 
   (	
	"ORG_ID" NUMBER(15,0), 
	"BANK_ID" NUMBER, 
	"BANK_ACCT_ID" NUMBER, 
    "INVOICE_ID" NUMBER(15,0), 
	"VENDOR_ID" NUMBER, 
	"LEGAL_ENTITY" VARCHAR2(240 BYTE), 
	"LEGAL_ENTITY_ID" NUMBER(15,0), 
	"OPERATING_UNIT_NAME" VARCHAR2(4000 BYTE), 
	"BANK_NAME" VARCHAR2(360 BYTE), 
	"BANK_ACCT_NAME" VARCHAR2(100 BYTE), 
	"BANK_ACCT_NUM" VARCHAR2(30 BYTE), 
	"VENDOR_TYPE" VARCHAR2(30 BYTE),
	"VENDOR_NAME" VARCHAR2(240 BYTE), 
	"VENDOR_NUM" VARCHAR2(30 BYTE), 
	"PAYMENT_METHOD_CODE" VARCHAR2(30 BYTE), 
	"INVOICE_NUM" VARCHAR2(50 BYTE), 
	"INVOICE_DATE" DATE, 
	"INVOICE_DUE_DATE" DATE, 
    "INVOICE_OVERDUE_DAY" NUMBER,
	"INVOICE_AMOUNT" NUMBER, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"FUNC_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"CONVERSION_RATE" NUMBER, 
	"FUNC_AMOUNT" NUMBER, 
	"SCHEDULED_PAYMENT_DATE" DATE, 
	"PAY_GROUP" VARCHAR2(30 BYTE),
	 CONSTRAINT "XXAP_FUNDING_PK" PRIMARY KEY ("ORG_ID", "INVOICE_ID")
   ) TABLESPACE "USERS" ;

CREATE OR REPLACE PUBLIC SYNONYM XXAP_FUNDING FOR TABLEAUETL.XXAP_FUNDING;
