--drop table TABLEAUETL.XXAP_INVOICE_LIST;

  CREATE TABLE "TABLEAUETL"."XXAP_INVOICE_LIST" 
   (	
    "ORG_ID" NUMBER(15,0), 
	"OPERATING_UNIT_NAME" VARCHAR2(240 BYTE), 
	"VENDOR_ID" NUMBER, 
	"VENDOR_NAME" VARCHAR2(240 BYTE), 
	"VENDOR_SITE_ID" NUMBER, 
	"VENDOR_SITE_CODE" VARCHAR2(15 BYTE), 
	"INVOICE_ID" NUMBER(15,0), 
	"INVOICE_NUMBER" VARCHAR2(50 BYTE), 
	"INVOICE_DATE" DATE, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"INVOICE_AMOUNT" NUMBER, 
	"INVOICE_FUNC_AMOUNT" NUMBER, 
	"INVOICE_SETTLEMENT_DATE" DATE, 
	"PO_HEADER_ID" NUMBER, 
	"PO_NUMBER" VARCHAR2(20 BYTE), 
	"PO_STATUS" VARCHAR2(25 BYTE), 
	"PO_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"PO_AMOUNT" NUMBER, 
	"PO_FUNC_AMOUNT" NUMBER, 
	"RCPT_ID" NUMBER, 
	"RCPT_AMOUNT" NUMBER, 
	"RCPT_FUNC_AMOUNT" NUMBER, 
	"RCPT_DATE" DATE, 
	"PO_BUYER_NAME" VARCHAR2(240 BYTE), 
	"PO_BUYER_EMPLOYEE_NUMBER" VARCHAR2(30 BYTE)
   ) TABLESPACE "USERS";

CREATE OR REPLACE PUBLIC SYNONYM XXAP_INVOICE_LIST FOR TABLEAUETL.XXAP_INVOICE_LIST;
