--drop table xxar_day_paid;

  CREATE TABLE "TABLEAUETL"."XXAR_DAY_PAID" 
   (	
    "ORG_ID" NUMBER(15,0), 
	"CUST_ACCOUNT_ID" NUMBER(15,0), 
	"AR_CUSTOMER_TRX_ID" NUMBER(15,0),
    "RECEIVABLE_APPLICATION_ID" NUMBER(15,0),
	"PROJECT_ID" NUMBER(15,0), 
	"OPERATING_UNIT_NAME" VARCHAR2(240 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(360 BYTE), 
	"CUSTOMER_NUMBER" VARCHAR2(30 BYTE), 
	"BUSINESS_UNIT" CHAR(240 BYTE), 
	"LEGAL_ENTITY" VARCHAR2(240 BYTE), 
	"LEGAL_ENTITY_NAME" VARCHAR2(240 BYTE), 
	"INVOICE_NUMBER" VARCHAR2(50 BYTE), 
	"INVOICE_DATE" DATE, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"INVOICE_TYPE" VARCHAR2(20 BYTE),  
	"PRIMARY_SALESREP" VARCHAR2(360 BYTE), 
	"PRIMARY_SALESREP_SPLIT" NUMBER, 
	"OTHER_SALESREP_NAME" VARCHAR2(4000 BYTE), 
	"OTHER_SALESREP_SPLIT" VARCHAR2(1000 BYTE),
	"PRIMARY_PRODUCT_TYPE" VARCHAR2(50 BYTE), 
	"ORIG_AMOUNT" NUMBER, 
	"APPLIED_AMOUNT" NUMBER, 
	"OPEN_AMOUNT" NUMBER, 
	"FUNC_AMOUNT" NUMBER, 
	"FUNC_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"APPLIED_DATE" DATE, 
	"RCPT_NUMBER" VARCHAR2(30 BYTE), 
	"RCPT_DATE" DATE, 
	"DAYS_PAID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(240 BYTE), 
	"INVOICE_GL_DATE" DATE, 
    "RECEIPT_GL_DATE" DATE, 
	"RECEIPT_BANK_NAME" VARCHAR2(100 BYTE), 
	"RECEIPT_BANK_ACCOUNT_NUMBER" VARCHAR2(100 BYTE),
    CONSTRAINT "XXAR_DAY_PAID_PK" PRIMARY KEY ("ORG_ID", "AR_CUSTOMER_TRX_ID", "RECEIVABLE_APPLICATION_ID")
   ) TABLESPACE "USERS" ;

CREATE OR REPLACE PUBLIC SYNONYM XXAR_DAY_PAID FOR TABLEAUETL.XXAR_DAY_PAID;
