package toppanmerrill.oracle.apps.xxtm.cb.invoicestyle.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceStyleVORowImpl extends OAViewRowImpl {
    public static final int INVOICESTYLEID = 0;
    public static final int INVOICESTYLENAME = 1;
    public static final int LANGUAGE = 2;
    public static final int CREATEDBY = 3;
    public static final int CREATIONDATE = 4;
    public static final int LASTUPDATEDBY = 5;
    public static final int LASTUPDATEDATE = 6;
    public static final int LASTUPDATELOGIN = 7;
    public static final int HEADATTENTION = 8;
    public static final int HEADINVOICENUMBER = 9;
    public static final int HEADINVOICEDATE = 10;
    public static final int HEADDATERECEIVED = 11;
    public static final int HEADSALESPERSON = 12;
    public static final int HEADOURORDERNUMBER = 13;
    public static final int HEADCUSTORDERNUMBER = 14;
    public static final int HEADTERMS = 15;
    public static final int FOOTPAGE = 16;
    public static final int DETAILFREIGHT = 17;
    public static final int DETAILTAX = 18;
    public static final int DETAILPOSTAGE = 19;
    public static final int DETAILTOTALINVOICE = 20;
    public static final int FOOTLEFT = 21;
    public static final int FOOTRIGHT = 22;
    public static final int HEADEMAIL = 23;
    public static final int DETAILSUBTOTALPRETAX = 24;
    public static final int INACTIVEDATE = 25;

    /**This is the default constructor (do not remove)
     */
    public InvoiceStyleVORowImpl() {
    }

    /**Gets InvoiceStyleEO entity object.
     */
    public InvoiceStyleEOImpl getInvoiceStyleEO() {
        return (InvoiceStyleEOImpl)getEntity(0);
    }

    /**Gets the attribute value for INVOICE_STYLE_ID using the alias name InvoiceStyleId
     */
    public Number getInvoiceStyleId() {
        return (Number) getAttributeInternal(INVOICESTYLEID);
    }

    /**Sets <code>value</code> as attribute value for INVOICE_STYLE_ID using the alias name InvoiceStyleId
     */
    public void setInvoiceStyleId(Number value) {
        setAttributeInternal(INVOICESTYLEID, value);
    }

    /**Gets the attribute value for INVOICE_STYLE_NAME using the alias name InvoiceStyleName
     */
    public String getInvoiceStyleName() {
        return (String) getAttributeInternal(INVOICESTYLENAME);
    }

    /**Sets <code>value</code> as attribute value for INVOICE_STYLE_NAME using the alias name InvoiceStyleName
     */
    public void setInvoiceStyleName(String value) {
        setAttributeInternal(INVOICESTYLENAME, value);
    }

    /**Gets the attribute value for LANGUAGE using the alias name Language
     */
    public String getLanguage() {
        return (String) getAttributeInternal(LANGUAGE);
    }

    /**Sets <code>value</code> as attribute value for LANGUAGE using the alias name Language
     */
    public void setLanguage(String value) {
        setAttributeInternal(LANGUAGE, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for HEAD_ATTENTION using the alias name HeadAttention
     */
    public String getHeadAttention() {
        return (String) getAttributeInternal(HEADATTENTION);
    }

    /**Sets <code>value</code> as attribute value for HEAD_ATTENTION using the alias name HeadAttention
     */
    public void setHeadAttention(String value) {
        setAttributeInternal(HEADATTENTION, value);
    }

    /**Gets the attribute value for HEAD_INVOICE_NUMBER using the alias name HeadInvoiceNumber
     */
    public String getHeadInvoiceNumber() {
        return (String) getAttributeInternal(HEADINVOICENUMBER);
    }

    /**Sets <code>value</code> as attribute value for HEAD_INVOICE_NUMBER using the alias name HeadInvoiceNumber
     */
    public void setHeadInvoiceNumber(String value) {
        setAttributeInternal(HEADINVOICENUMBER, value);
    }

    /**Gets the attribute value for HEAD_INVOICE_DATE using the alias name HeadInvoiceDate
     */
    public String getHeadInvoiceDate() {
        return (String) getAttributeInternal(HEADINVOICEDATE);
    }

    /**Sets <code>value</code> as attribute value for HEAD_INVOICE_DATE using the alias name HeadInvoiceDate
     */
    public void setHeadInvoiceDate(String value) {
        setAttributeInternal(HEADINVOICEDATE, value);
    }

    /**Gets the attribute value for HEAD_DATE_RECEIVED using the alias name HeadDateReceived
     */
    public String getHeadDateReceived() {
        return (String) getAttributeInternal(HEADDATERECEIVED);
    }

    /**Sets <code>value</code> as attribute value for HEAD_DATE_RECEIVED using the alias name HeadDateReceived
     */
    public void setHeadDateReceived(String value) {
        setAttributeInternal(HEADDATERECEIVED, value);
    }

    /**Gets the attribute value for HEAD_SALESPERSON using the alias name HeadSalesperson
     */
    public String getHeadSalesperson() {
        return (String) getAttributeInternal(HEADSALESPERSON);
    }

    /**Sets <code>value</code> as attribute value for HEAD_SALESPERSON using the alias name HeadSalesperson
     */
    public void setHeadSalesperson(String value) {
        setAttributeInternal(HEADSALESPERSON, value);
    }

    /**Gets the attribute value for HEAD_OUR_ORDER_NUMBER using the alias name HeadOurOrderNumber
     */
    public String getHeadOurOrderNumber() {
        return (String) getAttributeInternal(HEADOURORDERNUMBER);
    }

    /**Sets <code>value</code> as attribute value for HEAD_OUR_ORDER_NUMBER using the alias name HeadOurOrderNumber
     */
    public void setHeadOurOrderNumber(String value) {
        setAttributeInternal(HEADOURORDERNUMBER, value);
    }

    /**Gets the attribute value for HEAD_CUST_ORDER_NUMBER using the alias name HeadCustOrderNumber
     */
    public String getHeadCustOrderNumber() {
        return (String) getAttributeInternal(HEADCUSTORDERNUMBER);
    }

    /**Sets <code>value</code> as attribute value for HEAD_CUST_ORDER_NUMBER using the alias name HeadCustOrderNumber
     */
    public void setHeadCustOrderNumber(String value) {
        setAttributeInternal(HEADCUSTORDERNUMBER, value);
    }

    /**Gets the attribute value for HEAD_TERMS using the alias name HeadTerms
     */
    public String getHeadTerms() {
        return (String) getAttributeInternal(HEADTERMS);
    }

    /**Sets <code>value</code> as attribute value for HEAD_TERMS using the alias name HeadTerms
     */
    public void setHeadTerms(String value) {
        setAttributeInternal(HEADTERMS, value);
    }

    /**Gets the attribute value for FOOT_PAGE using the alias name FootPage
     */
    public String getFootPage() {
        return (String) getAttributeInternal(FOOTPAGE);
    }

    /**Sets <code>value</code> as attribute value for FOOT_PAGE using the alias name FootPage
     */
    public void setFootPage(String value) {
        setAttributeInternal(FOOTPAGE, value);
    }

    /**Gets the attribute value for DETAIL_FREIGHT using the alias name DetailFreight
     */
    public String getDetailFreight() {
        return (String) getAttributeInternal(DETAILFREIGHT);
    }

    /**Sets <code>value</code> as attribute value for DETAIL_FREIGHT using the alias name DetailFreight
     */
    public void setDetailFreight(String value) {
        setAttributeInternal(DETAILFREIGHT, value);
    }

    /**Gets the attribute value for DETAIL_TAX using the alias name DetailTax
     */
    public String getDetailTax() {
        return (String) getAttributeInternal(DETAILTAX);
    }

    /**Sets <code>value</code> as attribute value for DETAIL_TAX using the alias name DetailTax
     */
    public void setDetailTax(String value) {
        setAttributeInternal(DETAILTAX, value);
    }

    /**Gets the attribute value for DETAIL_POSTAGE using the alias name DetailPostage
     */
    public String getDetailPostage() {
        return (String) getAttributeInternal(DETAILPOSTAGE);
    }

    /**Sets <code>value</code> as attribute value for DETAIL_POSTAGE using the alias name DetailPostage
     */
    public void setDetailPostage(String value) {
        setAttributeInternal(DETAILPOSTAGE, value);
    }

    /**Gets the attribute value for DETAIL_TOTAL_INVOICE using the alias name DetailTotalInvoice
     */
    public String getDetailTotalInvoice() {
        return (String) getAttributeInternal(DETAILTOTALINVOICE);
    }

    /**Sets <code>value</code> as attribute value for DETAIL_TOTAL_INVOICE using the alias name DetailTotalInvoice
     */
    public void setDetailTotalInvoice(String value) {
        setAttributeInternal(DETAILTOTALINVOICE, value);
    }

    /**Gets the attribute value for FOOT_LEFT using the alias name FootLeft
     */
    public String getFootLeft() {
        return (String) getAttributeInternal(FOOTLEFT);
    }

    /**Sets <code>value</code> as attribute value for FOOT_LEFT using the alias name FootLeft
     */
    public void setFootLeft(String value) {
        setAttributeInternal(FOOTLEFT, value);
    }

    /**Gets the attribute value for FOOT_RIGHT using the alias name FootRight
     */
    public String getFootRight() {
        return (String) getAttributeInternal(FOOTRIGHT);
    }

    /**Sets <code>value</code> as attribute value for FOOT_RIGHT using the alias name FootRight
     */
    public void setFootRight(String value) {
        setAttributeInternal(FOOTRIGHT, value);
    }

    /**Gets the attribute value for HEAD_EMAIL using the alias name HeadEmail
     */
    public String getHeadEmail() {
        return (String) getAttributeInternal(HEADEMAIL);
    }

    /**Sets <code>value</code> as attribute value for HEAD_EMAIL using the alias name HeadEmail
     */
    public void setHeadEmail(String value) {
        setAttributeInternal(HEADEMAIL, value);
    }

    /**Gets the attribute value for DETAIL_SUBTOTAL_PRETAX using the alias name DetailSubtotalPretax
     */
    public String getDetailSubtotalPretax() {
        return (String) getAttributeInternal(DETAILSUBTOTALPRETAX);
    }

    /**Sets <code>value</code> as attribute value for DETAIL_SUBTOTAL_PRETAX using the alias name DetailSubtotalPretax
     */
    public void setDetailSubtotalPretax(String value) {
        setAttributeInternal(DETAILSUBTOTALPRETAX, value);
    }

    /**Gets the attribute value for INACTIVE_DATE using the alias name InactiveDate
     */
    public Date getInactiveDate() {
        return (Date) getAttributeInternal(INACTIVEDATE);
    }

    /**Sets <code>value</code> as attribute value for INACTIVE_DATE using the alias name InactiveDate
     */
    public void setInactiveDate(Date value) {
        setAttributeInternal(INACTIVEDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case INVOICESTYLEID:
            return getInvoiceStyleId();
        case INVOICESTYLENAME:
            return getInvoiceStyleName();
        case LANGUAGE:
            return getLanguage();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case HEADATTENTION:
            return getHeadAttention();
        case HEADINVOICENUMBER:
            return getHeadInvoiceNumber();
        case HEADINVOICEDATE:
            return getHeadInvoiceDate();
        case HEADDATERECEIVED:
            return getHeadDateReceived();
        case HEADSALESPERSON:
            return getHeadSalesperson();
        case HEADOURORDERNUMBER:
            return getHeadOurOrderNumber();
        case HEADCUSTORDERNUMBER:
            return getHeadCustOrderNumber();
        case HEADTERMS:
            return getHeadTerms();
        case FOOTPAGE:
            return getFootPage();
        case DETAILFREIGHT:
            return getDetailFreight();
        case DETAILTAX:
            return getDetailTax();
        case DETAILPOSTAGE:
            return getDetailPostage();
        case DETAILTOTALINVOICE:
            return getDetailTotalInvoice();
        case FOOTLEFT:
            return getFootLeft();
        case FOOTRIGHT:
            return getFootRight();
        case HEADEMAIL:
            return getHeadEmail();
        case DETAILSUBTOTALPRETAX:
            return getDetailSubtotalPretax();
        case INACTIVEDATE:
            return getInactiveDate();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case INVOICESTYLEID:
            setInvoiceStyleId((Number)value);
            return;
        case INVOICESTYLENAME:
            setInvoiceStyleName((String)value);
            return;
        case LANGUAGE:
            setLanguage((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case HEADATTENTION:
            setHeadAttention((String)value);
            return;
        case HEADINVOICENUMBER:
            setHeadInvoiceNumber((String)value);
            return;
        case HEADINVOICEDATE:
            setHeadInvoiceDate((String)value);
            return;
        case HEADDATERECEIVED:
            setHeadDateReceived((String)value);
            return;
        case HEADSALESPERSON:
            setHeadSalesperson((String)value);
            return;
        case HEADOURORDERNUMBER:
            setHeadOurOrderNumber((String)value);
            return;
        case HEADCUSTORDERNUMBER:
            setHeadCustOrderNumber((String)value);
            return;
        case HEADTERMS:
            setHeadTerms((String)value);
            return;
        case FOOTPAGE:
            setFootPage((String)value);
            return;
        case DETAILFREIGHT:
            setDetailFreight((String)value);
            return;
        case DETAILTAX:
            setDetailTax((String)value);
            return;
        case DETAILPOSTAGE:
            setDetailPostage((String)value);
            return;
        case DETAILTOTALINVOICE:
            setDetailTotalInvoice((String)value);
            return;
        case FOOTLEFT:
            setFootLeft((String)value);
            return;
        case FOOTRIGHT:
            setFootRight((String)value);
            return;
        case HEADEMAIL:
            setHeadEmail((String)value);
            return;
        case DETAILSUBTOTALPRETAX:
            setDetailSubtotalPretax((String)value);
            return;
        case INACTIVEDATE:
            setInactiveDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
