package toppanmerrill.oracle.apps.xxtm.cb.invoicestyle.server;

import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.fnd.framework.server.OADBTransactionImpl;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.Row;

import oracle.jdbc.internal.OracleCallableStatement;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceStyleAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public InvoiceStyleAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("toppanmerrill.oracle.apps.xxtm.cb.invoicestyle.server", /* package name */
      "InvoiceStyleAMLocal" /* Configuration Name */);
    }

    /**Container's getter for SearchInvoiceStyleVO1
     */
     public SearchInvoiceStyleVOImpl getSearchInvoiceStyleVO1() {
         return (SearchInvoiceStyleVOImpl)findViewObject("SearchInvoiceStyleVO1");
     }
     
    public void createRow()
    {

        InvoiceStyleVOImpl vo = (InvoiceStyleVOImpl)getInvoiceStyleVO1();

        // below initializes the VO used for both update and query as per
    
        // standards but not mandatory
    
        if (!vo.isPreparedForExecution())
        {
            vo.executeQuery();
        }
    
        Row row = vo.createRow();
    
        vo.insertRow(row);
    
        // Required per OA Framework Model Coding Standard but not mandatory
        row.setNewRowState(Row.STATUS_INITIALIZED);

    }
    
    public void updateRow(String InvoiceStyleId)
    {
        InvoiceStyleVOImpl vo = (InvoiceStyleVOImpl)getInvoiceStyleVO1();
        vo.initQuery(InvoiceStyleId);
    }
       
    public void apply()
    {
        getTransaction().commit();
    }

    public void rollback()
    {
        getTransaction().rollback();
    }

    /**Container's getter for InvoiceStyleVO1
     */
    public InvoiceStyleVOImpl getInvoiceStyleVO1() {
        return (InvoiceStyleVOImpl)findViewObject("InvoiceStyleVO1");
    }    
}
