package toppanmerrill.oracle.apps.xxtm.cb.invoicestyle.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceStyleVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public InvoiceStyleVOImpl() {
    }
    public void initQuery(String InvoiceStyleId)
    {
        if ((InvoiceStyleId != null) && (!("".equals(InvoiceStyleId.trim()))))
        {
            setWhereClause("INVOICE_STYLE_ID = :1");
            setWhereClauseParams(null); // Always reset
            setWhereClauseParam(0, InvoiceStyleId);
            executeQuery();
        }    
    }    
}
