package toppanmerrill.oracle.apps.xxtm.cb.invoice.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceLineEOImpl extends OAEntityImpl {
    public static final int CUSTOMERTRXLINEID = 0;
    public static final int CUSTOMERTRXID = 1;
    public static final int ORIGCUSTOMERTRXID = 2;
    public static final int ORIGTRXLINEID = 3;
    public static final int PROJECTID = 4;
    public static final int LINENUMBER = 5;
    public static final int PROJECTORGID = 6;
    public static final int QUANTITYSELL = 7;
    public static final int UNITSELL = 8;
    public static final int SELLAMOUNT = 9;
    public static final int PRODUCTTYPEID = 10;
    public static final int LONGDESCRIPTION = 11;
    public static final int CREATEDBY = 12;
    public static final int CREATIONDATE = 13;
    public static final int LASTUPDATEDBY = 14;
    public static final int LASTUPDATEDATE = 15;
    public static final int LASTUPDATELOGIN = 16;
    public static final int ARTRXLINENUMBER = 17;
    public static final int LINETYPE = 18;
    public static final int STATUS = 19;
    public static final int LEVEL1 = 20;
    public static final int LEVEL2 = 21;
    public static final int LEVEL3 = 22;
    public static final int ORGID = 23;
    public static final int INVOICEEO = 24;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public InvoiceLineEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("toppanmerrill.oracle.apps.xxtm.cb.invoice.server.InvoiceLineEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for CustomerTrxLineId, using the alias name CustomerTrxLineId
     */
    public Number getCustomerTrxLineId() {
        return (Number)getAttributeInternal(CUSTOMERTRXLINEID);
    }

    /**Sets <code>value</code> as the attribute value for CustomerTrxLineId
     */
    public void setCustomerTrxLineId(Number value) {
        setAttributeInternal(CUSTOMERTRXLINEID, value);
    }

    /**Gets the attribute value for CustomerTrxId, using the alias name CustomerTrxId
     */
    public Number getCustomerTrxId() {
        return (Number)getAttributeInternal(CUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for CustomerTrxId
     */
    public void setCustomerTrxId(Number value) {
        setAttributeInternal(CUSTOMERTRXID, value);
    }

    /**Gets the attribute value for OrigCustomerTrxId, using the alias name OrigCustomerTrxId
     */
    public Number getOrigCustomerTrxId() {
        return (Number)getAttributeInternal(ORIGCUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for OrigCustomerTrxId
     */
    public void setOrigCustomerTrxId(Number value) {
        setAttributeInternal(ORIGCUSTOMERTRXID, value);
    }

    /**Gets the attribute value for OrigTrxLineId, using the alias name OrigTrxLineId
     */
    public Number getOrigTrxLineId() {
        return (Number)getAttributeInternal(ORIGTRXLINEID);
    }

    /**Sets <code>value</code> as the attribute value for OrigTrxLineId
     */
    public void setOrigTrxLineId(Number value) {
        setAttributeInternal(ORIGTRXLINEID, value);
    }

    /**Gets the attribute value for ProjectId, using the alias name ProjectId
     */
    public Number getProjectId() {
        return (Number)getAttributeInternal(PROJECTID);
    }

    /**Sets <code>value</code> as the attribute value for ProjectId
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**Gets the attribute value for LineNumber, using the alias name LineNumber
     */
    public Number getLineNumber() {
        return (Number)getAttributeInternal(LINENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for LineNumber
     */
    public void setLineNumber(Number value) {
        setAttributeInternal(LINENUMBER, value);
    }


    /**Gets the attribute value for ProjectOrgId, using the alias name ProjectOrgId
     */
    public Number getProjectOrgId() {
        return (Number)getAttributeInternal(PROJECTORGID);
    }

    /**Sets <code>value</code> as the attribute value for ProjectOrgId
     */
    public void setProjectOrgId(Number value) {
        setAttributeInternal(PROJECTORGID, value);
    }

    /**Gets the attribute value for QuantitySell, using the alias name QuantitySell
     */
    public Number getQuantitySell() {
        return (Number)getAttributeInternal(QUANTITYSELL);
    }

    /**Sets <code>value</code> as the attribute value for QuantitySell
     */
    public void setQuantitySell(Number value) {
        setAttributeInternal(QUANTITYSELL, value);
    }

    /**Gets the attribute value for UnitSell, using the alias name UnitSell
     */
    public Number getUnitSell() {
        return (Number)getAttributeInternal(UNITSELL);
    }

    /**Sets <code>value</code> as the attribute value for UnitSell
     */
    public void setUnitSell(Number value) {
        setAttributeInternal(UNITSELL, value);
    }

    /**Gets the attribute value for SellAmount, using the alias name SellAmount
     */
    public Number getSellAmount() {
        return (Number)getAttributeInternal(SELLAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for SellAmount
     */
    public void setSellAmount(Number value) {
        setAttributeInternal(SELLAMOUNT, value);
    }

    /**Gets the attribute value for ProductTypeId, using the alias name ProductTypeId
     */
    public String getProductTypeId() {
        return (String)getAttributeInternal(PRODUCTTYPEID);
    }

    /**Sets <code>value</code> as the attribute value for ProductTypeId
     */
    public void setProductTypeId(String value) {
        setAttributeInternal(PRODUCTTYPEID, value);
    }

    /**Gets the attribute value for LongDescription, using the alias name LongDescription
     */
    public String getLongDescription() {
        return (String)getAttributeInternal(LONGDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for LongDescription
     */
    public void setLongDescription(String value) {
        setAttributeInternal(LONGDESCRIPTION, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for ArTrxLineNumber, using the alias name ArTrxLineNumber
     */
    public Number getArTrxLineNumber() {
        return (Number)getAttributeInternal(ARTRXLINENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for ArTrxLineNumber
     */
    public void setArTrxLineNumber(Number value) {
        setAttributeInternal(ARTRXLINENUMBER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CUSTOMERTRXLINEID:
            return getCustomerTrxLineId();
        case CUSTOMERTRXID:
            return getCustomerTrxId();
        case ORIGCUSTOMERTRXID:
            return getOrigCustomerTrxId();
        case ORIGTRXLINEID:
            return getOrigTrxLineId();
        case PROJECTID:
            return getProjectId();
        case LINENUMBER:
            return getLineNumber();
        case PROJECTORGID:
            return getProjectOrgId();
        case QUANTITYSELL:
            return getQuantitySell();
        case UNITSELL:
            return getUnitSell();
        case SELLAMOUNT:
            return getSellAmount();
        case PRODUCTTYPEID:
            return getProductTypeId();
        case LONGDESCRIPTION:
            return getLongDescription();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ARTRXLINENUMBER:
            return getArTrxLineNumber();
        case LINETYPE:
            return getLineType();
        case STATUS:
            return getStatus();
        case LEVEL1:
            return getLevel1();
        case LEVEL2:
            return getLevel2();
        case LEVEL3:
            return getLevel3();
        case ORGID:
            return getOrgId();
        case INVOICEEO:
            return getInvoiceEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CUSTOMERTRXLINEID:
            setCustomerTrxLineId((Number)value);
            return;
        case CUSTOMERTRXID:
            setCustomerTrxId((Number)value);
            return;
        case ORIGCUSTOMERTRXID:
            setOrigCustomerTrxId((Number)value);
            return;
        case ORIGTRXLINEID:
            setOrigTrxLineId((Number)value);
            return;
        case PROJECTID:
            setProjectId((Number)value);
            return;
        case LINENUMBER:
            setLineNumber((Number)value);
            return;
        case PROJECTORGID:
            setProjectOrgId((Number)value);
            return;
        case QUANTITYSELL:
            setQuantitySell((Number)value);
            return;
        case UNITSELL:
            setUnitSell((Number)value);
            return;
        case SELLAMOUNT:
            setSellAmount((Number)value);
            return;
        case PRODUCTTYPEID:
            setProductTypeId((String)value);
            return;
        case LONGDESCRIPTION:
            setLongDescription((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ARTRXLINENUMBER:
            setArTrxLineNumber((Number)value);
            return;
        case LINETYPE:
            setLineType((String)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case LEVEL1:
            setLevel1((String)value);
            return;
        case LEVEL2:
            setLevel2((String)value);
            return;
        case LEVEL3:
            setLevel3((String)value);
            return;
        case ORGID:
            setOrgId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity InvoiceEOImpl
     */
    public InvoiceEOImpl getInvoiceEO() {
        return (InvoiceEOImpl)getAttributeInternal(INVOICEEO);
    }

    /**Sets <code>value</code> as the associated entity InvoiceEOImpl
     */
    public void setInvoiceEO(InvoiceEOImpl value) {
        setAttributeInternal(INVOICEEO, value);
    }

    /**Gets the attribute value for LineType, using the alias name LineType
     */
    public String getLineType() {
        return (String)getAttributeInternal(LINETYPE);
    }

    /**Sets <code>value</code> as the attribute value for LineType
     */
    public void setLineType(String value) {
        setAttributeInternal(LINETYPE, value);
    }

    /**Gets the attribute value for Status, using the alias name Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for Level1, using the alias name Level1
     */
    public String getLevel1() {
        return (String)getAttributeInternal(LEVEL1);
    }

    /**Sets <code>value</code> as the attribute value for Level1
     */
    public void setLevel1(String value) {
        setAttributeInternal(LEVEL1, value);
    }

    /**Gets the attribute value for Level2, using the alias name Level2
     */
    public String getLevel2() {
        return (String)getAttributeInternal(LEVEL2);
    }

    /**Sets <code>value</code> as the attribute value for Level2
     */
    public void setLevel2(String value) {
        setAttributeInternal(LEVEL2, value);
    }

    /**Gets the attribute value for Level3, using the alias name Level3
     */
    public String getLevel3() {
        return (String)getAttributeInternal(LEVEL3);
    }

    /**Sets <code>value</code> as the attribute value for Level3
     */
    public void setLevel3(String value) {
        setAttributeInternal(LEVEL3, value);
    }

    /**Gets the attribute value for OrgId, using the alias name OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number customerTrxLineId) {
        return new Key(new Object[]{customerTrxLineId});
    }
}
