package toppanmerrill.oracle.apps.xxtm.cb.invoice.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceCombineReqEOImpl extends OAEntityImpl {
    public static final int COMBINEREQID = 0;
    public static final int PARENTCUSTOMERTRXID = 1;
    public static final int COMBINEREQNUMBER = 2;
    public static final int STATUS = 3;
    public static final int APPROVALREASON = 4;
    public static final int JUSTIFICATION = 5;
    public static final int ORGID = 6;
    public static final int CREATEDBY = 7;
    public static final int CREATIONDATE = 8;
    public static final int LASTUPDATEDBY = 9;
    public static final int LASTUPDATEDATE = 10;
    public static final int LASTUPDATELOGIN = 11;
    public static final int REQTYPE = 12;
    public static final int INVOICECOMBINEREQDTLEO1 = 13;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public InvoiceCombineReqEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("toppanmerrill.oracle.apps.xxtm.cb.invoice.server.InvoiceCombineReqEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for CombineReqId, using the alias name CombineReqId
     */
    public Number getCombineReqId() {
        return (Number)getAttributeInternal(COMBINEREQID);
    }

    /**Sets <code>value</code> as the attribute value for CombineReqId
     */
    public void setCombineReqId(Number value) {
        setAttributeInternal(COMBINEREQID, value);
    }

    /**Gets the attribute value for ParentCustomerTrxId, using the alias name ParentCustomerTrxId
     */
    public Number getParentCustomerTrxId() {
        return (Number)getAttributeInternal(PARENTCUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for ParentCustomerTrxId
     */
    public void setParentCustomerTrxId(Number value) {
        setAttributeInternal(PARENTCUSTOMERTRXID, value);
    }

    /**Gets the attribute value for CombineReqNumber, using the alias name CombineReqNumber
     */
    public String getCombineReqNumber() {
        return (String)getAttributeInternal(COMBINEREQNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for CombineReqNumber
     */
    public void setCombineReqNumber(String value) {
        setAttributeInternal(COMBINEREQNUMBER, value);
    }

    /**Gets the attribute value for Status, using the alias name Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for ApprovalReason, using the alias name ApprovalReason
     */
    public String getApprovalReason() {
        return (String)getAttributeInternal(APPROVALREASON);
    }

    /**Sets <code>value</code> as the attribute value for ApprovalReason
     */
    public void setApprovalReason(String value) {
        setAttributeInternal(APPROVALREASON, value);
    }

    /**Gets the attribute value for Justification, using the alias name Justification
     */
    public String getJustification() {
        return (String)getAttributeInternal(JUSTIFICATION);
    }

    /**Sets <code>value</code> as the attribute value for Justification
     */
    public void setJustification(String value) {
        setAttributeInternal(JUSTIFICATION, value);
    }

    /**Gets the attribute value for OrgId, using the alias name OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for ReqType, using the alias name ReqType
     */
    public String getReqType() {
        return (String)getAttributeInternal(REQTYPE);
    }

    /**Sets <code>value</code> as the attribute value for ReqType
     */
    public void setReqType(String value) {
        setAttributeInternal(REQTYPE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case COMBINEREQID:
            return getCombineReqId();
        case PARENTCUSTOMERTRXID:
            return getParentCustomerTrxId();
        case COMBINEREQNUMBER:
            return getCombineReqNumber();
        case STATUS:
            return getStatus();
        case APPROVALREASON:
            return getApprovalReason();
        case JUSTIFICATION:
            return getJustification();
        case ORGID:
            return getOrgId();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case REQTYPE:
            return getReqType();
        case INVOICECOMBINEREQDTLEO1:
            return getInvoiceCombineReqDtlEO1();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case COMBINEREQID:
            setCombineReqId((Number)value);
            return;
        case PARENTCUSTOMERTRXID:
            setParentCustomerTrxId((Number)value);
            return;
        case COMBINEREQNUMBER:
            setCombineReqNumber((String)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case APPROVALREASON:
            setApprovalReason((String)value);
            return;
        case JUSTIFICATION:
            setJustification((String)value);
            return;
        case ORGID:
            setOrgId((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case REQTYPE:
            setReqType((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getInvoiceCombineReqDtlEO1() {
        return (RowIterator)getAttributeInternal(INVOICECOMBINEREQDTLEO1);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number combineReqId) {
        return new Key(new Object[]{combineReqId});
    }
}
