package toppanmerrill.oracle.apps.xxtm.cb.invoice.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceActivityEOImpl extends OAEntityImpl {


    public static final int TRXACTIVITYID = 0;
    public static final int CUSTOMERTRXID = 1;
    public static final int ACTIVITYDATE = 2;
    public static final int ACTIVITYTYPE = 3;
    public static final int PERSON = 4;
    public static final int CHANGEFROM = 5;
    public static final int CHANGETO = 6;
    public static final int APPROVALACTION = 7;
    public static final int APPROVALREASON = 8;
    public static final int JUSTIFICATION = 9;
    public static final int CREATEDBY = 10;
    public static final int CREATIONDATE = 11;
    public static final int LASTUPDATEDBY = 12;
    public static final int LASTUPDATEDATE = 13;
    public static final int LASTUPDATELOGIN = 14;
    public static final int INVOICEEO = 15;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public InvoiceActivityEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("toppanmerrill.oracle.apps.xxtm.cb.invoice.server.InvoiceActivityEO");
        }
        return mDefinitionObject;
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TRXACTIVITYID:
            return getTrxActivityId();
        case CUSTOMERTRXID:
            return getCustomerTrxId();
        case ACTIVITYDATE:
            return getActivityDate();
        case ACTIVITYTYPE:
            return getActivityType();
        case PERSON:
            return getPerson();
        case CHANGEFROM:
            return getChangeFrom();
        case CHANGETO:
            return getChangeTo();
        case APPROVALACTION:
            return getApprovalAction();
        case APPROVALREASON:
            return getApprovalReason();
        case JUSTIFICATION:
            return getJustification();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case INVOICEEO:
            return getInvoiceEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TRXACTIVITYID:
            setTrxActivityId((Number)value);
            return;
        case CUSTOMERTRXID:
            setCustomerTrxId((Number)value);
            return;
        case ACTIVITYDATE:
            setActivityDate((Date)value);
            return;
        case ACTIVITYTYPE:
            setActivityType((String)value);
            return;
        case PERSON:
            setPerson((Number)value);
            return;
        case CHANGEFROM:
            setChangeFrom((String)value);
            return;
        case CHANGETO:
            setChangeTo((String)value);
            return;
        case APPROVALACTION:
            setApprovalAction((String)value);
            return;
        case APPROVALREASON:
            setApprovalReason((String)value);
            return;
        case JUSTIFICATION:
            setJustification((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for TrxActivityId, using the alias name TrxActivityId
     */
    public Number getTrxActivityId() {
        return (Number)getAttributeInternal(TRXACTIVITYID);
    }

    /**Sets <code>value</code> as the attribute value for TrxActivityId
     */
    public void setTrxActivityId(Number value) {
        setAttributeInternal(TRXACTIVITYID, value);
    }

    /**Gets the attribute value for CustomerTrxId, using the alias name CustomerTrxId
     */
    public Number getCustomerTrxId() {
        return (Number)getAttributeInternal(CUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for CustomerTrxId
     */
    public void setCustomerTrxId(Number value) {
        setAttributeInternal(CUSTOMERTRXID, value);
    }

    /**Gets the attribute value for ActivityDate, using the alias name ActivityDate
     */
    public Date getActivityDate() {
        return (Date)getAttributeInternal(ACTIVITYDATE);
    }

    /**Sets <code>value</code> as the attribute value for ActivityDate
     */
    public void setActivityDate(Date value) {
        setAttributeInternal(ACTIVITYDATE, value);
    }

    /**Gets the attribute value for ActivityType, using the alias name ActivityType
     */
    public String getActivityType() {
        return (String)getAttributeInternal(ACTIVITYTYPE);
    }

    /**Sets <code>value</code> as the attribute value for ActivityType
     */
    public void setActivityType(String value) {
        setAttributeInternal(ACTIVITYTYPE, value);
    }

    /**Gets the attribute value for Person, using the alias name Person
     */
    public Number getPerson() {
        return (Number)getAttributeInternal(PERSON);
    }

    /**Sets <code>value</code> as the attribute value for Person
     */
    public void setPerson(Number value) {
        setAttributeInternal(PERSON, value);
    }

    /**Gets the attribute value for ChangeFrom, using the alias name ChangeFrom
     */
    public String getChangeFrom() {
        return (String)getAttributeInternal(CHANGEFROM);
    }

    /**Sets <code>value</code> as the attribute value for ChangeFrom
     */
    public void setChangeFrom(String value) {
        setAttributeInternal(CHANGEFROM, value);
    }

    /**Gets the attribute value for ChangeTo, using the alias name ChangeTo
     */
    public String getChangeTo() {
        return (String)getAttributeInternal(CHANGETO);
    }

    /**Sets <code>value</code> as the attribute value for ChangeTo
     */
    public void setChangeTo(String value) {
        setAttributeInternal(CHANGETO, value);
    }

    /**Gets the attribute value for ApprovalAction, using the alias name ApprovalAction
     */
    public String getApprovalAction() {
        return (String)getAttributeInternal(APPROVALACTION);
    }

    /**Sets <code>value</code> as the attribute value for ApprovalAction
     */
    public void setApprovalAction(String value) {
        setAttributeInternal(APPROVALACTION, value);
    }

    /**Gets the attribute value for ApprovalReason, using the alias name ApprovalReason
     */
    public String getApprovalReason() {
        return (String)getAttributeInternal(APPROVALREASON);
    }

    /**Sets <code>value</code> as the attribute value for ApprovalReason
     */
    public void setApprovalReason(String value) {
        setAttributeInternal(APPROVALREASON, value);
    }

    /**Gets the attribute value for Justification, using the alias name Justification
     */
    public String getJustification() {
        return (String)getAttributeInternal(JUSTIFICATION);
    }

    /**Sets <code>value</code> as the attribute value for Justification
     */
    public void setJustification(String value) {
        setAttributeInternal(JUSTIFICATION, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the associated entity InvoiceEOImpl
     */
    public InvoiceEOImpl getInvoiceEO() {
        return (InvoiceEOImpl)getAttributeInternal(INVOICEEO);
    }

    /**Sets <code>value</code> as the associated entity InvoiceEOImpl
     */
    public void setInvoiceEO(InvoiceEOImpl value) {
        setAttributeInternal(INVOICEEO, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number trxActivityId) {
        return new Key(new Object[]{trxActivityId});
    }
}
