package toppanmerrill.oracle.apps.xxtm.cb.invoice.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceEOImpl extends OAEntityImpl {
    public static final int CUSTOMERTRXID = 0;
    public static final int PARENTCUSTOMERTRXID = 1;
    public static final int ARTRXNUMBER = 2;
    public static final int SETOFBOOKSID = 3;
    public static final int PRIMARYPRODUCTTYPEID = 4;
    public static final int PROFILEID = 5;
    public static final int CUSTTRXTYPEID = 6;
    public static final int TRXDATE = 7;
    public static final int DATERECEIVED = 8;
    public static final int PERIODNAME = 9;
    public static final int PRIMARYSALESREPID = 10;
    public static final int DESCRIPTION = 11;
    public static final int COMMENTS = 12;
    public static final int BILLTOADDRESSID = 13;
    public static final int BILLTOCUSTOMERID = 14;
    public static final int ATTENDEE = 15;
    public static final int ATTENDEEEMAIL = 16;
    public static final int INVOICEADDRESSID = 17;
    public static final int ORDERNUMBER = 18;
    public static final int CUSTOMERORDERNUMBER = 19;
    public static final int OWNINGBILLERID = 20;
    public static final int ACTIVEBILLERID = 21;
    public static final int CURRENTSTATUSDATE = 22;
    public static final int TERMID = 23;
    public static final int CURRENCYCODE = 24;
    public static final int ENTEREDCURRENCYCODE = 25;
    public static final int EXCHANGEDATE = 26;
    public static final int EXCHANGERATE = 27;
    public static final int EXCHANGERATETYPE = 28;
    public static final int CREATEDBY = 29;
    public static final int CREATIONDATE = 30;
    public static final int LASTUPDATEDBY = 31;
    public static final int LASTUPDATEDATE = 32;
    public static final int LASTUPDATELOGIN = 33;
    public static final int PROJECTCATEGORYID = 34;
    public static final int PRIMARYPROJECTORGID = 35;
    public static final int ORIGINALPROJECTID = 36;
    public static final int SOURCESYSTEM = 37;
    public static final int PROJECTCOMPLETEDATE = 38;
    public static final int COSTSUMSENDDATE = 39;
    public static final int MARGINREPORTSENDDATE = 40;
    public static final int BILLREMARK = 41;
    public static final int INVOICECLASS = 42;
    public static final int CURRENTSTATUS = 43;
    public static final int INVOICESTYLENAME = 44;
    public static final int INVOICETITLE = 45;
    public static final int INVOICEDESCONELINE = 46;
    public static final int TAXDESC = 47;
    public static final int TAXAMOUNT = 48;
    public static final int INVOICEFOOTTOP = 49;
    public static final int INVOICEFOOTBOTTOM = 50;
    public static final int DISPLAYSALESPERSON = 51;
    public static final int DISPLAYLEVEL1 = 52;
    public static final int DISPLAYLEVEL1TOTAL = 53;
    public static final int DISPLAYLEVEL2 = 54;
    public static final int DISPLAYLEVEL2TOTAL = 55;
    public static final int DISPLAYLEVEL3 = 56;
    public static final int DISPLAYLEVEL3TOTAL = 57;
    public static final int PRELIMINARY = 58;
    public static final int BILLTOCONTACTID = 59;
    public static final int SECBILLTOCUSTOMERID = 60;
    public static final int ORGID = 61;
    public static final int PRINTREQUESTID = 62;
    public static final int PREVIOUSSTATUS = 63;
    public static final int TOTALLINEAMOUNT = 64;
    public static final int REVISEDCUSTOMERTRXID = 65;
    public static final int REVISETONUM = 66;
    public static final int BILLREMARK2 = 67;
    public static final int INVOICESALESREPSPLITSEO = 68;
    public static final int INVOICELINEEO = 69;
    public static final int INVOICEACTIVITYEO = 70;
    public static final int INVOICEAUDITEO = 71;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public InvoiceEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("toppanmerrill.oracle.apps.xxtm.cb.invoice.server.InvoiceEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for CustomerTrxId, using the alias name CustomerTrxId
     */
    public Number getCustomerTrxId() {
        return (Number)getAttributeInternal(CUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for CustomerTrxId
     */
    public void setCustomerTrxId(Number value) {
        setAttributeInternal(CUSTOMERTRXID, value);
    }

    /**Gets the attribute value for ParentCustomerTrxId, using the alias name ParentCustomerTrxId
     */
    public Number getParentCustomerTrxId() {
        return (Number)getAttributeInternal(PARENTCUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for ParentCustomerTrxId
     */
    public void setParentCustomerTrxId(Number value) {
        setAttributeInternal(PARENTCUSTOMERTRXID, value);
    }

    /**Gets the attribute value for ArTrxNumber, using the alias name ArTrxNumber
     */
    public String getArTrxNumber() {
        return (String)getAttributeInternal(ARTRXNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for ArTrxNumber
     */
    public void setArTrxNumber(String value) {
        setAttributeInternal(ARTRXNUMBER, value);
    }


    /**Gets the attribute value for SetOfBooksId, using the alias name SetOfBooksId
     */
    public Number getSetOfBooksId() {
        return (Number)getAttributeInternal(SETOFBOOKSID);
    }

    /**Sets <code>value</code> as the attribute value for SetOfBooksId
     */
    public void setSetOfBooksId(Number value) {
        setAttributeInternal(SETOFBOOKSID, value);
    }

    /**Gets the attribute value for PrimaryProductTypeId, using the alias name PrimaryProductTypeId
     */
    public String getPrimaryProductTypeId() {
        return (String)getAttributeInternal(PRIMARYPRODUCTTYPEID);
    }

    /**Sets <code>value</code> as the attribute value for PrimaryProductTypeId
     */
    public void setPrimaryProductTypeId(String value) {
        setAttributeInternal(PRIMARYPRODUCTTYPEID, value);
    }

    /**Gets the attribute value for ProfileId, using the alias name ProfileId
     */
    public Number getProfileId() {
        return (Number)getAttributeInternal(PROFILEID);
    }

    /**Sets <code>value</code> as the attribute value for ProfileId
     */
    public void setProfileId(Number value) {
        setAttributeInternal(PROFILEID, value);
    }

    /**Gets the attribute value for CustTrxTypeId, using the alias name CustTrxTypeId
     */
    public Number getCustTrxTypeId() {
        return (Number)getAttributeInternal(CUSTTRXTYPEID);
    }

    /**Sets <code>value</code> as the attribute value for CustTrxTypeId
     */
    public void setCustTrxTypeId(Number value) {
        setAttributeInternal(CUSTTRXTYPEID, value);
    }

    /**Gets the attribute value for TrxDate, using the alias name TrxDate
     */
    public Date getTrxDate() {
        return (Date)getAttributeInternal(TRXDATE);
    }

    /**Sets <code>value</code> as the attribute value for TrxDate
     */
    public void setTrxDate(Date value) {
        setAttributeInternal(TRXDATE, value);
    }

    /**Gets the attribute value for DateReceived, using the alias name DateReceived
     */
    public Date getDateReceived() {
        return (Date)getAttributeInternal(DATERECEIVED);
    }

    /**Sets <code>value</code> as the attribute value for DateReceived
     */
    public void setDateReceived(Date value) {
        setAttributeInternal(DATERECEIVED, value);
    }

    /**Gets the attribute value for PeriodName, using the alias name PeriodName
     */
    public String getPeriodName() {
        return (String)getAttributeInternal(PERIODNAME);
    }

    /**Sets <code>value</code> as the attribute value for PeriodName
     */
    public void setPeriodName(String value) {
        setAttributeInternal(PERIODNAME, value);
    }

    /**Gets the attribute value for PrimarySalesrepId, using the alias name PrimarySalesrepId
     */
    public Number getPrimarySalesrepId() {
        return (Number)getAttributeInternal(PRIMARYSALESREPID);
    }

    /**Sets <code>value</code> as the attribute value for PrimarySalesrepId
     */
    public void setPrimarySalesrepId(Number value) {
        setAttributeInternal(PRIMARYSALESREPID, value);
    }

    /**Gets the attribute value for Description, using the alias name Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**Gets the attribute value for Comments, using the alias name Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**Gets the attribute value for BillToAddressId, using the alias name BillToAddressId
     */
    public Number getBillToAddressId() {
        return (Number)getAttributeInternal(BILLTOADDRESSID);
    }

    /**Sets <code>value</code> as the attribute value for BillToAddressId
     */
    public void setBillToAddressId(Number value) {
        setAttributeInternal(BILLTOADDRESSID, value);
    }

    /**Gets the attribute value for BillToCustomerId, using the alias name BillToCustomerId
     */
    public Number getBillToCustomerId() {
        return (Number)getAttributeInternal(BILLTOCUSTOMERID);
    }

    /**Sets <code>value</code> as the attribute value for BillToCustomerId
     */
    public void setBillToCustomerId(Number value) {
        setAttributeInternal(BILLTOCUSTOMERID, value);
    }

    /**Gets the attribute value for Attendee, using the alias name Attendee
     */
    public String getAttendee() {
        return (String)getAttributeInternal(ATTENDEE);
    }

    /**Sets <code>value</code> as the attribute value for Attendee
     */
    public void setAttendee(String value) {
        setAttributeInternal(ATTENDEE, value);
    }

    /**Gets the attribute value for AttendeeEmail, using the alias name AttendeeEmail
     */
    public String getAttendeeEmail() {
        return (String)getAttributeInternal(ATTENDEEEMAIL);
    }

    /**Sets <code>value</code> as the attribute value for AttendeeEmail
     */
    public void setAttendeeEmail(String value) {
        setAttributeInternal(ATTENDEEEMAIL, value);
    }

    /**Gets the attribute value for InvoiceAddressId, using the alias name InvoiceAddressId
     */
    public Number getInvoiceAddressId() {
        return (Number)getAttributeInternal(INVOICEADDRESSID);
    }

    /**Sets <code>value</code> as the attribute value for InvoiceAddressId
     */
    public void setInvoiceAddressId(Number value) {
        setAttributeInternal(INVOICEADDRESSID, value);
    }

    /**Gets the attribute value for OrderNumber, using the alias name OrderNumber
     */
    public String getOrderNumber() {
        return (String)getAttributeInternal(ORDERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for OrderNumber
     */
    public void setOrderNumber(String value) {
        setAttributeInternal(ORDERNUMBER, value);
    }

    /**Gets the attribute value for CustomerOrderNumber, using the alias name CustomerOrderNumber
     */
    public String getCustomerOrderNumber() {
        return (String)getAttributeInternal(CUSTOMERORDERNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for CustomerOrderNumber
     */
    public void setCustomerOrderNumber(String value) {
        setAttributeInternal(CUSTOMERORDERNUMBER, value);
    }

    /**Gets the attribute value for OwningBillerId, using the alias name OwningBillerId
     */
    public Number getOwningBillerId() {
        return (Number)getAttributeInternal(OWNINGBILLERID);
    }

    /**Sets <code>value</code> as the attribute value for OwningBillerId
     */
    public void setOwningBillerId(Number value) {
        setAttributeInternal(OWNINGBILLERID, value);
    }

    /**Gets the attribute value for ActiveBillerId, using the alias name ActiveBillerId
     */
    public Number getActiveBillerId() {
        return (Number)getAttributeInternal(ACTIVEBILLERID);
    }

    /**Sets <code>value</code> as the attribute value for ActiveBillerId
     */
    public void setActiveBillerId(Number value) {
        setAttributeInternal(ACTIVEBILLERID, value);
    }

    /**Gets the attribute value for CurrentStatusDate, using the alias name CurrentStatusDate
     */
    public Date getCurrentStatusDate() {
        return (Date)getAttributeInternal(CURRENTSTATUSDATE);
    }

    /**Sets <code>value</code> as the attribute value for CurrentStatusDate
     */
    public void setCurrentStatusDate(Date value) {
        setAttributeInternal(CURRENTSTATUSDATE, value);
    }

    /**Gets the attribute value for TermId, using the alias name TermId
     */
    public Number getTermId() {
        return (Number)getAttributeInternal(TERMID);
    }

    /**Sets <code>value</code> as the attribute value for TermId
     */
    public void setTermId(Number value) {
        setAttributeInternal(TERMID, value);
    }

    /**Gets the attribute value for CurrencyCode, using the alias name CurrencyCode
     */
    public String getCurrencyCode() {
        return (String)getAttributeInternal(CURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**Gets the attribute value for EnteredCurrencyCode, using the alias name EnteredCurrencyCode
     */
    public String getEnteredCurrencyCode() {
        return (String)getAttributeInternal(ENTEREDCURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for EnteredCurrencyCode
     */
    public void setEnteredCurrencyCode(String value) {
        setAttributeInternal(ENTEREDCURRENCYCODE, value);
    }

    /**Gets the attribute value for ExchangeDate, using the alias name ExchangeDate
     */
    public Date getExchangeDate() {
        return (Date)getAttributeInternal(EXCHANGEDATE);
    }

    /**Sets <code>value</code> as the attribute value for ExchangeDate
     */
    public void setExchangeDate(Date value) {
        setAttributeInternal(EXCHANGEDATE, value);
    }

    /**Gets the attribute value for ExchangeRate, using the alias name ExchangeRate
     */
    public Number getExchangeRate() {
        return (Number)getAttributeInternal(EXCHANGERATE);
    }

    /**Sets <code>value</code> as the attribute value for ExchangeRate
     */
    public void setExchangeRate(Number value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**Gets the attribute value for ExchangeRateType, using the alias name ExchangeRateType
     */
    public String getExchangeRateType() {
        return (String)getAttributeInternal(EXCHANGERATETYPE);
    }

    /**Sets <code>value</code> as the attribute value for ExchangeRateType
     */
    public void setExchangeRateType(String value) {
        setAttributeInternal(EXCHANGERATETYPE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for ProjectCategoryId, using the alias name ProjectCategoryId
     */
    public Number getProjectCategoryId() {
        return (Number)getAttributeInternal(PROJECTCATEGORYID);
    }

    /**Sets <code>value</code> as the attribute value for ProjectCategoryId
     */
    public void setProjectCategoryId(Number value) {
        setAttributeInternal(PROJECTCATEGORYID, value);
    }

    /**Gets the attribute value for PrimaryProjectOrgId, using the alias name PrimaryProjectOrgId
     */
    public Number getPrimaryProjectOrgId() {
        return (Number)getAttributeInternal(PRIMARYPROJECTORGID);
    }

    /**Sets <code>value</code> as the attribute value for PrimaryProjectOrgId
     */
    public void setPrimaryProjectOrgId(Number value) {
        setAttributeInternal(PRIMARYPROJECTORGID, value);
    }

    /**Gets the attribute value for OriginalProjectId, using the alias name OriginalProjectId
     */
    public Number getOriginalProjectId() {
        return (Number)getAttributeInternal(ORIGINALPROJECTID);
    }

    /**Sets <code>value</code> as the attribute value for OriginalProjectId
     */
    public void setOriginalProjectId(Number value) {
        setAttributeInternal(ORIGINALPROJECTID, value);
    }

    /**Gets the attribute value for SourceSystem, using the alias name SourceSystem
     */
    public String getSourceSystem() {
        return (String)getAttributeInternal(SOURCESYSTEM);
    }

    /**Sets <code>value</code> as the attribute value for SourceSystem
     */
    public void setSourceSystem(String value) {
        setAttributeInternal(SOURCESYSTEM, value);
    }

    /**Gets the attribute value for ProjectCompleteDate, using the alias name ProjectCompleteDate
     */
    public Date getProjectCompleteDate() {
        return (Date)getAttributeInternal(PROJECTCOMPLETEDATE);
    }

    /**Sets <code>value</code> as the attribute value for ProjectCompleteDate
     */
    public void setProjectCompleteDate(Date value) {
        setAttributeInternal(PROJECTCOMPLETEDATE, value);
    }

    /**Gets the attribute value for CostSumSendDate, using the alias name CostSumSendDate
     */
    public Date getCostSumSendDate() {
        return (Date)getAttributeInternal(COSTSUMSENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for CostSumSendDate
     */
    public void setCostSumSendDate(Date value) {
        setAttributeInternal(COSTSUMSENDDATE, value);
    }

    /**Gets the attribute value for MarginReportSendDate, using the alias name MarginReportSendDate
     */
    public Date getMarginReportSendDate() {
        return (Date)getAttributeInternal(MARGINREPORTSENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for MarginReportSendDate
     */
    public void setMarginReportSendDate(Date value) {
        setAttributeInternal(MARGINREPORTSENDDATE, value);
    }

    /**Gets the attribute value for BillRemark, using the alias name BillRemark
     */
    public String getBillRemark() {
        return (String)getAttributeInternal(BILLREMARK);
    }

    /**Sets <code>value</code> as the attribute value for BillRemark
     */
    public void setBillRemark(String value) {
        setAttributeInternal(BILLREMARK, value);
    }

    /**Gets the attribute value for InvoiceClass, using the alias name InvoiceClass
     */
    public String getInvoiceClass() {
        return (String)getAttributeInternal(INVOICECLASS);
    }

    /**Sets <code>value</code> as the attribute value for InvoiceClass
     */
    public void setInvoiceClass(String value) {
        setAttributeInternal(INVOICECLASS, value);
    }

    /**Gets the attribute value for CurrentStatus, using the alias name CurrentStatus
     */
    public String getCurrentStatus() {
        return (String)getAttributeInternal(CURRENTSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for CurrentStatus
     */
    public void setCurrentStatus(String value) {
        setAttributeInternal(CURRENTSTATUS, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CUSTOMERTRXID:
            return getCustomerTrxId();
        case PARENTCUSTOMERTRXID:
            return getParentCustomerTrxId();
        case ARTRXNUMBER:
            return getArTrxNumber();
        case SETOFBOOKSID:
            return getSetOfBooksId();
        case PRIMARYPRODUCTTYPEID:
            return getPrimaryProductTypeId();
        case PROFILEID:
            return getProfileId();
        case CUSTTRXTYPEID:
            return getCustTrxTypeId();
        case TRXDATE:
            return getTrxDate();
        case DATERECEIVED:
            return getDateReceived();
        case PERIODNAME:
            return getPeriodName();
        case PRIMARYSALESREPID:
            return getPrimarySalesrepId();
        case DESCRIPTION:
            return getDescription();
        case COMMENTS:
            return getComments();
        case BILLTOADDRESSID:
            return getBillToAddressId();
        case BILLTOCUSTOMERID:
            return getBillToCustomerId();
        case ATTENDEE:
            return getAttendee();
        case ATTENDEEEMAIL:
            return getAttendeeEmail();
        case INVOICEADDRESSID:
            return getInvoiceAddressId();
        case ORDERNUMBER:
            return getOrderNumber();
        case CUSTOMERORDERNUMBER:
            return getCustomerOrderNumber();
        case OWNINGBILLERID:
            return getOwningBillerId();
        case ACTIVEBILLERID:
            return getActiveBillerId();
        case CURRENTSTATUSDATE:
            return getCurrentStatusDate();
        case TERMID:
            return getTermId();
        case CURRENCYCODE:
            return getCurrencyCode();
        case ENTEREDCURRENCYCODE:
            return getEnteredCurrencyCode();
        case EXCHANGEDATE:
            return getExchangeDate();
        case EXCHANGERATE:
            return getExchangeRate();
        case EXCHANGERATETYPE:
            return getExchangeRateType();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case PROJECTCATEGORYID:
            return getProjectCategoryId();
        case PRIMARYPROJECTORGID:
            return getPrimaryProjectOrgId();
        case ORIGINALPROJECTID:
            return getOriginalProjectId();
        case SOURCESYSTEM:
            return getSourceSystem();
        case PROJECTCOMPLETEDATE:
            return getProjectCompleteDate();
        case COSTSUMSENDDATE:
            return getCostSumSendDate();
        case MARGINREPORTSENDDATE:
            return getMarginReportSendDate();
        case BILLREMARK:
            return getBillRemark();
        case INVOICECLASS:
            return getInvoiceClass();
        case CURRENTSTATUS:
            return getCurrentStatus();
        case INVOICESTYLENAME:
            return getInvoiceStyleName();
        case INVOICETITLE:
            return getInvoiceTitle();
        case INVOICEDESCONELINE:
            return getInvoiceDescOneLine();
        case TAXDESC:
            return getTaxDesc();
        case TAXAMOUNT:
            return getTaxAmount();
        case INVOICEFOOTTOP:
            return getInvoiceFootTop();
        case INVOICEFOOTBOTTOM:
            return getInvoiceFootBottom();
        case DISPLAYSALESPERSON:
            return getDisplaySalesperson();
        case DISPLAYLEVEL1:
            return getDisplayLevel1();
        case DISPLAYLEVEL1TOTAL:
            return getDisplayLevel1Total();
        case DISPLAYLEVEL2:
            return getDisplayLevel2();
        case DISPLAYLEVEL2TOTAL:
            return getDisplayLevel2Total();
        case DISPLAYLEVEL3:
            return getDisplayLevel3();
        case DISPLAYLEVEL3TOTAL:
            return getDisplayLevel3Total();
        case PRELIMINARY:
            return getPreliminary();
        case BILLTOCONTACTID:
            return getBillToContactId();
        case SECBILLTOCUSTOMERID:
            return getSecBillToCustomerId();
        case ORGID:
            return getOrgId();
        case PRINTREQUESTID:
            return getPrintRequestId();
        case PREVIOUSSTATUS:
            return getPreviousStatus();
        case TOTALLINEAMOUNT:
            return getTotalLineAmount();
        case REVISEDCUSTOMERTRXID:
            return getRevisedCustomerTrxId();
        case REVISETONUM:
            return getReviseToNum();
        case BILLREMARK2:
            return getBillRemark2();
        case INVOICEACTIVITYEO:
            return getInvoiceActivityEO();
        case INVOICEAUDITEO:
            return getInvoiceAuditEO();
        case INVOICELINEEO:
            return getInvoiceLineEO();
        case INVOICESALESREPSPLITSEO:
            return getInvoiceSalesRepSplitsEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CUSTOMERTRXID:
            setCustomerTrxId((Number)value);
            return;
        case PARENTCUSTOMERTRXID:
            setParentCustomerTrxId((Number)value);
            return;
        case ARTRXNUMBER:
            setArTrxNumber((String)value);
            return;
        case SETOFBOOKSID:
            setSetOfBooksId((Number)value);
            return;
        case PRIMARYPRODUCTTYPEID:
            setPrimaryProductTypeId((String)value);
            return;
        case PROFILEID:
            setProfileId((Number)value);
            return;
        case CUSTTRXTYPEID:
            setCustTrxTypeId((Number)value);
            return;
        case TRXDATE:
            setTrxDate((Date)value);
            return;
        case DATERECEIVED:
            setDateReceived((Date)value);
            return;
        case PERIODNAME:
            setPeriodName((String)value);
            return;
        case PRIMARYSALESREPID:
            setPrimarySalesrepId((Number)value);
            return;
        case DESCRIPTION:
            setDescription((String)value);
            return;
        case COMMENTS:
            setComments((String)value);
            return;
        case BILLTOADDRESSID:
            setBillToAddressId((Number)value);
            return;
        case BILLTOCUSTOMERID:
            setBillToCustomerId((Number)value);
            return;
        case ATTENDEE:
            setAttendee((String)value);
            return;
        case ATTENDEEEMAIL:
            setAttendeeEmail((String)value);
            return;
        case INVOICEADDRESSID:
            setInvoiceAddressId((Number)value);
            return;
        case ORDERNUMBER:
            setOrderNumber((String)value);
            return;
        case CUSTOMERORDERNUMBER:
            setCustomerOrderNumber((String)value);
            return;
        case OWNINGBILLERID:
            setOwningBillerId((Number)value);
            return;
        case ACTIVEBILLERID:
            setActiveBillerId((Number)value);
            return;
        case CURRENTSTATUSDATE:
            setCurrentStatusDate((Date)value);
            return;
        case TERMID:
            setTermId((Number)value);
            return;
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        case ENTEREDCURRENCYCODE:
            setEnteredCurrencyCode((String)value);
            return;
        case EXCHANGEDATE:
            setExchangeDate((Date)value);
            return;
        case EXCHANGERATE:
            setExchangeRate((Number)value);
            return;
        case EXCHANGERATETYPE:
            setExchangeRateType((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case PROJECTCATEGORYID:
            setProjectCategoryId((Number)value);
            return;
        case PRIMARYPROJECTORGID:
            setPrimaryProjectOrgId((Number)value);
            return;
        case ORIGINALPROJECTID:
            setOriginalProjectId((Number)value);
            return;
        case SOURCESYSTEM:
            setSourceSystem((String)value);
            return;
        case PROJECTCOMPLETEDATE:
            setProjectCompleteDate((Date)value);
            return;
        case COSTSUMSENDDATE:
            setCostSumSendDate((Date)value);
            return;
        case MARGINREPORTSENDDATE:
            setMarginReportSendDate((Date)value);
            return;
        case BILLREMARK:
            setBillRemark((String)value);
            return;
        case INVOICECLASS:
            setInvoiceClass((String)value);
            return;
        case CURRENTSTATUS:
            setCurrentStatus((String)value);
            return;
        case INVOICESTYLENAME:
            setInvoiceStyleName((String)value);
            return;
        case INVOICETITLE:
            setInvoiceTitle((String)value);
            return;
        case INVOICEDESCONELINE:
            setInvoiceDescOneLine((String)value);
            return;
        case TAXDESC:
            setTaxDesc((String)value);
            return;
        case TAXAMOUNT:
            setTaxAmount((Number)value);
            return;
        case INVOICEFOOTTOP:
            setInvoiceFootTop((String)value);
            return;
        case INVOICEFOOTBOTTOM:
            setInvoiceFootBottom((String)value);
            return;
        case DISPLAYSALESPERSON:
            setDisplaySalesperson((String)value);
            return;
        case DISPLAYLEVEL1:
            setDisplayLevel1((String)value);
            return;
        case DISPLAYLEVEL1TOTAL:
            setDisplayLevel1Total((String)value);
            return;
        case DISPLAYLEVEL2:
            setDisplayLevel2((String)value);
            return;
        case DISPLAYLEVEL2TOTAL:
            setDisplayLevel2Total((String)value);
            return;
        case DISPLAYLEVEL3:
            setDisplayLevel3((String)value);
            return;
        case DISPLAYLEVEL3TOTAL:
            setDisplayLevel3Total((String)value);
            return;
        case PRELIMINARY:
            setPreliminary((String)value);
            return;
        case BILLTOCONTACTID:
            setBillToContactId((Number)value);
            return;
        case SECBILLTOCUSTOMERID:
            setSecBillToCustomerId((Number)value);
            return;
        case ORGID:
            setOrgId((Number)value);
            return;
        case PRINTREQUESTID:
            setPrintRequestId((Number)value);
            return;
        case PREVIOUSSTATUS:
            setPreviousStatus((String)value);
            return;
        case TOTALLINEAMOUNT:
            setTotalLineAmount((Number)value);
            return;
        case REVISEDCUSTOMERTRXID:
            setRevisedCustomerTrxId((Number)value);
            return;
        case REVISETONUM:
            setReviseToNum((Number)value);
            return;
        case BILLREMARK2:
            setBillRemark2((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getInvoiceSalesRepSplitsEO() {
        return (RowIterator)getAttributeInternal(INVOICESALESREPSPLITSEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getInvoiceLineEO() {
        return (RowIterator)getAttributeInternal(INVOICELINEEO);
    }

    /**Gets the attribute value for InvoiceStyleName, using the alias name InvoiceStyleName
     */
    public String getInvoiceStyleName() {
        return (String)getAttributeInternal(INVOICESTYLENAME);
    }

    /**Sets <code>value</code> as the attribute value for InvoiceStyleName
     */
    public void setInvoiceStyleName(String value) {
        setAttributeInternal(INVOICESTYLENAME, value);
    }

    /**Gets the attribute value for InvoiceTitle, using the alias name InvoiceTitle
     */
    public String getInvoiceTitle() {
        return (String)getAttributeInternal(INVOICETITLE);
    }

    /**Sets <code>value</code> as the attribute value for InvoiceTitle
     */
    public void setInvoiceTitle(String value) {
        setAttributeInternal(INVOICETITLE, value);
    }

    /**Gets the attribute value for InvoiceDescOneLine, using the alias name InvoiceDescOneLine
     */
    public String getInvoiceDescOneLine() {
        return (String)getAttributeInternal(INVOICEDESCONELINE);
    }

    /**Sets <code>value</code> as the attribute value for InvoiceDescOneLine
     */
    public void setInvoiceDescOneLine(String value) {
        setAttributeInternal(INVOICEDESCONELINE, value);
    }

    /**Gets the attribute value for TaxDesc, using the alias name TaxDesc
     */
    public String getTaxDesc() {
        return (String)getAttributeInternal(TAXDESC);
    }

    /**Sets <code>value</code> as the attribute value for TaxDesc
     */
    public void setTaxDesc(String value) {
        setAttributeInternal(TAXDESC, value);
    }

    /**Gets the attribute value for TaxAmount, using the alias name TaxAmount
     */
    public Number getTaxAmount() {
        return (Number)getAttributeInternal(TAXAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for TaxAmount
     */
    public void setTaxAmount(Number value) {
        setAttributeInternal(TAXAMOUNT, value);
    }

    /**Gets the attribute value for InvoiceFootTop, using the alias name InvoiceFootTop
     */
    public String getInvoiceFootTop() {
        return (String)getAttributeInternal(INVOICEFOOTTOP);
    }

    /**Sets <code>value</code> as the attribute value for InvoiceFootTop
     */
    public void setInvoiceFootTop(String value) {
        setAttributeInternal(INVOICEFOOTTOP, value);
    }

    /**Gets the attribute value for InvoiceFootBottom, using the alias name InvoiceFootBottom
     */
    public String getInvoiceFootBottom() {
        return (String)getAttributeInternal(INVOICEFOOTBOTTOM);
    }

    /**Sets <code>value</code> as the attribute value for InvoiceFootBottom
     */
    public void setInvoiceFootBottom(String value) {
        setAttributeInternal(INVOICEFOOTBOTTOM, value);
    }

    /**Gets the attribute value for DisplaySalesperson, using the alias name DisplaySalesperson
     */
    public String getDisplaySalesperson() {
        return (String)getAttributeInternal(DISPLAYSALESPERSON);
    }

    /**Sets <code>value</code> as the attribute value for DisplaySalesperson
     */
    public void setDisplaySalesperson(String value) {
        setAttributeInternal(DISPLAYSALESPERSON, value);
    }

    /**Gets the attribute value for DisplayLevel1, using the alias name DisplayLevel1
     */
    public String getDisplayLevel1() {
        return (String)getAttributeInternal(DISPLAYLEVEL1);
    }

    /**Sets <code>value</code> as the attribute value for DisplayLevel1
     */
    public void setDisplayLevel1(String value) {
        setAttributeInternal(DISPLAYLEVEL1, value);
    }

    /**Gets the attribute value for DisplayLevel1Total, using the alias name DisplayLevel1Total
     */
    public String getDisplayLevel1Total() {
        return (String)getAttributeInternal(DISPLAYLEVEL1TOTAL);
    }

    /**Sets <code>value</code> as the attribute value for DisplayLevel1Total
     */
    public void setDisplayLevel1Total(String value) {
        setAttributeInternal(DISPLAYLEVEL1TOTAL, value);
    }

    /**Gets the attribute value for DisplayLevel2, using the alias name DisplayLevel2
     */
    public String getDisplayLevel2() {
        return (String)getAttributeInternal(DISPLAYLEVEL2);
    }

    /**Sets <code>value</code> as the attribute value for DisplayLevel2
     */
    public void setDisplayLevel2(String value) {
        setAttributeInternal(DISPLAYLEVEL2, value);
    }

    /**Gets the attribute value for DisplayLevel2Total, using the alias name DisplayLevel2Total
     */
    public String getDisplayLevel2Total() {
        return (String)getAttributeInternal(DISPLAYLEVEL2TOTAL);
    }

    /**Sets <code>value</code> as the attribute value for DisplayLevel2Total
     */
    public void setDisplayLevel2Total(String value) {
        setAttributeInternal(DISPLAYLEVEL2TOTAL, value);
    }

    /**Gets the attribute value for DisplayLevel3, using the alias name DisplayLevel3
     */
    public String getDisplayLevel3() {
        return (String)getAttributeInternal(DISPLAYLEVEL3);
    }

    /**Sets <code>value</code> as the attribute value for DisplayLevel3
     */
    public void setDisplayLevel3(String value) {
        setAttributeInternal(DISPLAYLEVEL3, value);
    }

    /**Gets the attribute value for DisplayLevel3Total, using the alias name DisplayLevel3Total
     */
    public String getDisplayLevel3Total() {
        return (String)getAttributeInternal(DISPLAYLEVEL3TOTAL);
    }

    /**Sets <code>value</code> as the attribute value for DisplayLevel3Total
     */
    public void setDisplayLevel3Total(String value) {
        setAttributeInternal(DISPLAYLEVEL3TOTAL, value);
    }

    /**Gets the attribute value for Preliminary, using the alias name Preliminary
     */
    public String getPreliminary() {
        return (String)getAttributeInternal(PRELIMINARY);
    }

    /**Sets <code>value</code> as the attribute value for Preliminary
     */
    public void setPreliminary(String value) {
        setAttributeInternal(PRELIMINARY, value);
    }

    /**Gets the attribute value for BillToContactId, using the alias name BillToContactId
     */
    public Number getBillToContactId() {
        return (Number)getAttributeInternal(BILLTOCONTACTID);
    }

    /**Sets <code>value</code> as the attribute value for BillToContactId
     */
    public void setBillToContactId(Number value) {
        setAttributeInternal(BILLTOCONTACTID, value);
    }

    /**Gets the attribute value for SecBillToCustomerId, using the alias name SecBillToCustomerId
     */
    public Number getSecBillToCustomerId() {
        return (Number)getAttributeInternal(SECBILLTOCUSTOMERID);
    }

    /**Sets <code>value</code> as the attribute value for SecBillToCustomerId
     */
    public void setSecBillToCustomerId(Number value) {
        setAttributeInternal(SECBILLTOCUSTOMERID, value);
    }

    /**Gets the attribute value for OrgId, using the alias name OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getInvoiceActivityEO() {
        return (RowIterator)getAttributeInternal(INVOICEACTIVITYEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getInvoiceAuditEO() {
        return (RowIterator)getAttributeInternal(INVOICEAUDITEO);
    }

    /**Gets the attribute value for PrintRequestId, using the alias name PrintRequestId
     */
    public Number getPrintRequestId() {
        return (Number)getAttributeInternal(PRINTREQUESTID);
    }

    /**Sets <code>value</code> as the attribute value for PrintRequestId
     */
    public void setPrintRequestId(Number value) {
        setAttributeInternal(PRINTREQUESTID, value);
    }

    /**Gets the attribute value for PreviousStatus, using the alias name PreviousStatus
     */
    public String getPreviousStatus() {
        return (String)getAttributeInternal(PREVIOUSSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for PreviousStatus
     */
    public void setPreviousStatus(String value) {
        setAttributeInternal(PREVIOUSSTATUS, value);
    }

    /**Gets the attribute value for TotalLineAmount, using the alias name TotalLineAmount
     */
    public Number getTotalLineAmount() {
        return (Number)getAttributeInternal(TOTALLINEAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for TotalLineAmount
     */
    public void setTotalLineAmount(Number value) {
        setAttributeInternal(TOTALLINEAMOUNT, value);
    }

    /**Gets the attribute value for RevisedCustomerTrxId, using the alias name RevisedCustomerTrxId
     */
    public Number getRevisedCustomerTrxId() {
        return (Number)getAttributeInternal(REVISEDCUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for RevisedCustomerTrxId
     */
    public void setRevisedCustomerTrxId(Number value) {
        setAttributeInternal(REVISEDCUSTOMERTRXID, value);
    }

    /**Gets the attribute value for ReviseToNum, using the alias name ReviseToNum
     */
    public Number getReviseToNum() {
        return (Number)getAttributeInternal(REVISETONUM);
    }

    /**Sets <code>value</code> as the attribute value for ReviseToNum
     */
    public void setReviseToNum(Number value) {
        setAttributeInternal(REVISETONUM, value);
    }

    /**Gets the attribute value for BillRemark2, using the alias name BillRemark2
     */
    public String getBillRemark2() {
        return (String)getAttributeInternal(BILLREMARK2);
    }

    /**Sets <code>value</code> as the attribute value for BillRemark2
     */
    public void setBillRemark2(String value) {
        setAttributeInternal(BILLREMARK2, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number customerTrxId) {
        return new Key(new Object[]{customerTrxId});
    }
}
