package toppanmerrill.oracle.apps.xxtm.cb.invoice.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceCombineReqDtlEOImpl extends OAEntityImpl {
    public static final int COMBINEREQDTLID = 0;
    public static final int COMBINEREQID = 1;
    public static final int CHILDCUSTOMERTRXID = 2;
    public static final int CREATEDBY = 3;
    public static final int CREATIONDATE = 4;
    public static final int LASTUPDATEDBY = 5;
    public static final int LASTUPDATEDATE = 6;
    public static final int LASTUPDATELOGIN = 7;
    public static final int INVOICECOMBINEREQEO1 = 8;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public InvoiceCombineReqDtlEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("toppanmerrill.oracle.apps.xxtm.cb.invoice.server.InvoiceCombineReqDtlEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for CombineReqDtlId, using the alias name CombineReqDtlId
     */
    public Number getCombineReqDtlId() {
        return (Number)getAttributeInternal(COMBINEREQDTLID);
    }

    /**Sets <code>value</code> as the attribute value for CombineReqDtlId
     */
    public void setCombineReqDtlId(Number value) {
        setAttributeInternal(COMBINEREQDTLID, value);
    }

    /**Gets the attribute value for CombineReqId, using the alias name CombineReqId
     */
    public Number getCombineReqId() {
        return (Number)getAttributeInternal(COMBINEREQID);
    }

    /**Sets <code>value</code> as the attribute value for CombineReqId
     */
    public void setCombineReqId(Number value) {
        setAttributeInternal(COMBINEREQID, value);
    }

    /**Gets the attribute value for ChildCustomerTrxId, using the alias name ChildCustomerTrxId
     */
    public Number getChildCustomerTrxId() {
        return (Number)getAttributeInternal(CHILDCUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for ChildCustomerTrxId
     */
    public void setChildCustomerTrxId(Number value) {
        setAttributeInternal(CHILDCUSTOMERTRXID, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case COMBINEREQDTLID:
            return getCombineReqDtlId();
        case COMBINEREQID:
            return getCombineReqId();
        case CHILDCUSTOMERTRXID:
            return getChildCustomerTrxId();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case INVOICECOMBINEREQEO1:
            return getInvoiceCombineReqEO1();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case COMBINEREQDTLID:
            setCombineReqDtlId((Number)value);
            return;
        case COMBINEREQID:
            setCombineReqId((Number)value);
            return;
        case CHILDCUSTOMERTRXID:
            setChildCustomerTrxId((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the associated entity InvoiceCombineReqEOImpl
     */
    public InvoiceCombineReqEOImpl getInvoiceCombineReqEO1() {
        return (InvoiceCombineReqEOImpl)getAttributeInternal(INVOICECOMBINEREQEO1);
    }

    /**Sets <code>value</code> as the associated entity InvoiceCombineReqEOImpl
     */
    public void setInvoiceCombineReqEO1(InvoiceCombineReqEOImpl value) {
        setAttributeInternal(INVOICECOMBINEREQEO1, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number combineReqDtlId) {
        return new Key(new Object[]{combineReqDtlId});
    }
}
