package toppanmerrill.oracle.apps.xxtm.cb.invoice.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceSalesRepSplitsEOImpl extends OAEntityImpl {
    public static final int REPSPLITID = 0;
    public static final int CUSTOMERTRXID = 1;
    public static final int SALESREPID = 2;
    public static final int PRIMARYFLAG = 3;
    public static final int SPLITPERCENTAGE = 4;
    public static final int CREATEDBY = 5;
    public static final int CREATIONDATE = 6;
    public static final int LASTUPDATEDBY = 7;
    public static final int LASTUPDATEDATE = 8;
    public static final int LASTUPDATELOGIN = 9;
    public static final int ADJUSTMENT = 10;
    public static final int SALESPERSONTYPE = 11;
    public static final int SEQUENCENUMBER = 12;
    public static final int INVOICEEO = 13;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public InvoiceSalesRepSplitsEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("toppanmerrill.oracle.apps.xxtm.cb.invoice.server.InvoiceSalesRepSplitsEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for RepSplitId, using the alias name RepSplitId
     */
    public Number getRepSplitId() {
        return (Number)getAttributeInternal(REPSPLITID);
    }

    /**Sets <code>value</code> as the attribute value for RepSplitId
     */
    public void setRepSplitId(Number value) {
        setAttributeInternal(REPSPLITID, value);
    }

    /**Gets the attribute value for CustomerTrxId, using the alias name CustomerTrxId
     */
    public Number getCustomerTrxId() {
        return (Number)getAttributeInternal(CUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for CustomerTrxId
     */
    public void setCustomerTrxId(Number value) {
        setAttributeInternal(CUSTOMERTRXID, value);
    }

    /**Gets the attribute value for SalesrepId, using the alias name SalesrepId
     */
    public Number getSalesrepId() {
        return (Number)getAttributeInternal(SALESREPID);
    }

    /**Sets <code>value</code> as the attribute value for SalesrepId
     */
    public void setSalesrepId(Number value) {
        setAttributeInternal(SALESREPID, value);
    }

    /**Gets the attribute value for PrimaryFlag, using the alias name PrimaryFlag
     */
    public String getPrimaryFlag() {
        return (String)getAttributeInternal(PRIMARYFLAG);
    }

    /**Sets <code>value</code> as the attribute value for PrimaryFlag
     */
    public void setPrimaryFlag(String value) {
        setAttributeInternal(PRIMARYFLAG, value);
    }

    /**Gets the attribute value for SplitPercentage, using the alias name SplitPercentage
     */
    public Number getSplitPercentage() {
        return (Number)getAttributeInternal(SPLITPERCENTAGE);
    }

    /**Sets <code>value</code> as the attribute value for SplitPercentage
     */
    public void setSplitPercentage(Number value) {
        setAttributeInternal(SPLITPERCENTAGE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for Adjustment, using the alias name Adjustment
     */
    public Number getAdjustment() {
        return (Number)getAttributeInternal(ADJUSTMENT);
    }

    /**Sets <code>value</code> as the attribute value for Adjustment
     */
    public void setAdjustment(Number value) {
        setAttributeInternal(ADJUSTMENT, value);
    }

    /**Gets the attribute value for SalespersonType, using the alias name SalespersonType
     */
    public String getSalespersonType() {
        return (String)getAttributeInternal(SALESPERSONTYPE);
    }

    /**Sets <code>value</code> as the attribute value for SalespersonType
     */
    public void setSalespersonType(String value) {
        setAttributeInternal(SALESPERSONTYPE, value);
    }

    /**Gets the attribute value for SequenceNumber, using the alias name SequenceNumber
     */
    public Number getSequenceNumber() {
        return (Number)getAttributeInternal(SEQUENCENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for SequenceNumber
     */
    public void setSequenceNumber(Number value) {
        setAttributeInternal(SEQUENCENUMBER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REPSPLITID:
            return getRepSplitId();
        case CUSTOMERTRXID:
            return getCustomerTrxId();
        case SALESREPID:
            return getSalesrepId();
        case PRIMARYFLAG:
            return getPrimaryFlag();
        case SPLITPERCENTAGE:
            return getSplitPercentage();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ADJUSTMENT:
            return getAdjustment();
        case SALESPERSONTYPE:
            return getSalespersonType();
        case SEQUENCENUMBER:
            return getSequenceNumber();
        case INVOICEEO:
            return getInvoiceEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case REPSPLITID:
            setRepSplitId((Number)value);
            return;
        case CUSTOMERTRXID:
            setCustomerTrxId((Number)value);
            return;
        case SALESREPID:
            setSalesrepId((Number)value);
            return;
        case PRIMARYFLAG:
            setPrimaryFlag((String)value);
            return;
        case SPLITPERCENTAGE:
            setSplitPercentage((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ADJUSTMENT:
            setAdjustment((Number)value);
            return;
        case SALESPERSONTYPE:
            setSalespersonType((String)value);
            return;
        case SEQUENCENUMBER:
            setSequenceNumber((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity toppanmerrill.oracle.apps.xxtm.cb.invoice.server.InvoiceEOImpl
     */
    public InvoiceEOImpl getInvoiceEO() {
        return (InvoiceEOImpl)getAttributeInternal(INVOICEEO);
    }

    /**Sets <code>value</code> as the associated entity toppanmerrill.oracle.apps.xxtm.cb.invoice.server.InvoiceEOImpl
     */
    public void setInvoiceEO(InvoiceEOImpl value) {
        setAttributeInternal(INVOICEEO, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number repSplitId) {
        return new Key(new Object[]{repSplitId});
    }
}
