package toppanmerrill.oracle.apps.xxtm.cb.invoice.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceAuditEOImpl extends OAEntityImpl {
    public static final int TRXAUDITID = 0;
    public static final int CUSTOMERTRXID = 1;
    public static final int PROBLEMDESC = 2;
    public static final int FIXDESC = 3;
    public static final int CREATEDBY = 4;
    public static final int CREATIONDATE = 5;
    public static final int LASTUPDATEDBY = 6;
    public static final int LASTUPDATEDATE = 7;
    public static final int LASTUPDATELOGIN = 8;
    public static final int INVOICEEO = 9;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public InvoiceAuditEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("toppanmerrill.oracle.apps.xxtm.cb.invoice.server.InvoiceAuditEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for TrxAuditId, using the alias name TrxAuditId
     */
    public Number getTrxAuditId() {
        return (Number)getAttributeInternal(TRXAUDITID);
    }

    /**Sets <code>value</code> as the attribute value for TrxAuditId
     */
    public void setTrxAuditId(Number value) {
        setAttributeInternal(TRXAUDITID, value);
    }

    /**Gets the attribute value for CustomerTrxId, using the alias name CustomerTrxId
     */
    public Number getCustomerTrxId() {
        return (Number)getAttributeInternal(CUSTOMERTRXID);
    }

    /**Sets <code>value</code> as the attribute value for CustomerTrxId
     */
    public void setCustomerTrxId(Number value) {
        setAttributeInternal(CUSTOMERTRXID, value);
    }

    /**Gets the attribute value for ProblemDesc, using the alias name ProblemDesc
     */
    public String getProblemDesc() {
        return (String)getAttributeInternal(PROBLEMDESC);
    }

    /**Sets <code>value</code> as the attribute value for ProblemDesc
     */
    public void setProblemDesc(String value) {
        setAttributeInternal(PROBLEMDESC, value);
    }

    /**Gets the attribute value for FixDesc, using the alias name FixDesc
     */
    public String getFixDesc() {
        return (String)getAttributeInternal(FIXDESC);
    }

    /**Sets <code>value</code> as the attribute value for FixDesc
     */
    public void setFixDesc(String value) {
        setAttributeInternal(FIXDESC, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TRXAUDITID:
            return getTrxAuditId();
        case CUSTOMERTRXID:
            return getCustomerTrxId();
        case PROBLEMDESC:
            return getProblemDesc();
        case FIXDESC:
            return getFixDesc();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case INVOICEEO:
            return getInvoiceEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TRXAUDITID:
            setTrxAuditId((Number)value);
            return;
        case CUSTOMERTRXID:
            setCustomerTrxId((Number)value);
            return;
        case PROBLEMDESC:
            setProblemDesc((String)value);
            return;
        case FIXDESC:
            setFixDesc((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity InvoiceEOImpl
     */
    public InvoiceEOImpl getInvoiceEO() {
        return (InvoiceEOImpl)getAttributeInternal(INVOICEEO);
    }

    /**Sets <code>value</code> as the associated entity InvoiceEOImpl
     */
    public void setInvoiceEO(InvoiceEOImpl value) {
        setAttributeInternal(INVOICEEO, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number trxAuditId) {
        return new Key(new Object[]{trxAuditId});
    }
}
