package toppanmerrill.oracle.apps.xxtm.cb.invoice.server;

import oracle.apps.fnd.framework.server.OAEntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceCombineReqDtlEOCollImpl extends OAEntityCache {
    /**This is the default constructor (do not remove)
     */
    public InvoiceCombineReqDtlEOCollImpl() {
    }
}
