CREATE SEQUENCE "XXTM"."XXBS_CUSTOMER_TRX_S"  
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 1 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_CUSTOMER_TRX_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_CUSTOMER_TRX_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_CUSTOMER_TRX_S FOR XXTM.XXBS_CUSTOMER_TRX_S;


CREATE SEQUENCE "XXTM"."XXBS_AR_TRX_NUMBER_S"  
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 30000000 CACHE 20 ;


GRANT ALTER ON "XXTM"."XXBS_AR_TRX_NUMBER_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_AR_TRX_NUMBER_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_AR_TRX_NUMBER_S FOR XXTM.XXBS_AR_TRX_NUMBER_S;


CREATE SEQUENCE "XXTM"."XXBS_CUSTOMER_TRX_LINE_S"  
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 1 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_CUSTOMER_TRX_LINE_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_CUSTOMER_TRX_LINE_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_CUSTOMER_TRX_LINE_S FOR XXTM.XXBS_CUSTOMER_TRX_LINE_S;


CREATE SEQUENCE "XXTM"."XXBS_REP_SPLITS_S"  
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 1 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_REP_SPLITS_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_REP_SPLITS_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_REP_SPLITS_S FOR XXTM.XXBS_REP_SPLITS_S;


CREATE SEQUENCE "XXTM"."XXBS_INVOICE_STYLES_S"  
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 100 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_INVOICE_STYLES_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_INVOICE_STYLES_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_INVOICE_STYLES_S FOR XXTM.XXBS_INVOICE_STYLES_S;


CREATE SEQUENCE "XXTM"."XXBS_INVOICE_REPORTS_S"  
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 1 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_INVOICE_REPORTS_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_INVOICE_REPORTS_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_INVOICE_STYLES_S FOR XXTM.XXBS_INVOICE_REPORTS_S;



CREATE SEQUENCE "XXTM"."XXBS_TRX_ACTIVITY_S"
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 1 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_TRX_ACTIVITY_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_TRX_ACTIVITY_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_TRX_ACTIVITY_S FOR XXTM.XXBS_TRX_ACTIVITY_S;


CREATE SEQUENCE "XXTM"."XXBS_TRX_AUDIT_S"
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 1 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_TRX_AUDIT_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_TRX_AUDIT_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_TRX_AUDIT_S FOR XXTM.XXBS_TRX_AUDIT_S;


CREATE SEQUENCE "XXTM"."XXBS_COMBINE_REQ_S"
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 1 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_COMBINE_REQ_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_COMBINE_REQ_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_COMBINE_REQ_S FOR XXTM.XXBS_COMBINE_REQ_S;


CREATE SEQUENCE "XXTM"."XXBS_COMBINE_REQ_DTL_S"
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 1 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_COMBINE_REQ_DTL_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_COMBINE_REQ_DTL_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_COMBINE_REQ_DTL_S FOR XXTM.XXBS_COMBINE_REQ_DTL_S;


CREATE SEQUENCE "XXTM"."XXBS_COMBINE_REQ_NUM_S"
MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 
START WITH 1 CACHE 20 ;

GRANT ALTER ON "XXTM"."XXBS_COMBINE_REQ_NUM_S" TO "APPS" WITH GRANT OPTION;
GRANT SELECT ON "XXTM"."XXBS_COMBINE_REQ_NUM_S" TO "APPS" WITH GRANT OPTION;
CREATE SYNONYM APPS.XXBS_COMBINE_REQ_NUM_S FOR XXTM.XXBS_COMBINE_REQ_NUM_S;


