package testing.oracle.apps.ak.hello.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HelloAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public HelloAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("testing.oracle.apps.ak.hello.server", /* package name */
      "HelloAMLocal" /* Configuration Name */);
    }
}
