--------------------------------------------------------
--  DDL for Table XXAR_CREDITCARD_INT_DOC
--------------------------------------------------------

  CREATE TABLE "APPS"."XXAR_CREDITCARD_INT_DOC" 
   (	"DOC_ID" NUMBER NOT NULL ENABLE, 
	"CREDITCARD_FILE" "SYS"."XMLTYPE"  NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" 
 XMLTYPE COLUMN "CREDITCARD_FILE" STORE AS SECUREFILE BINARY XML (
  TABLESPACE "APPS_TS_TX_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE( INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;

