--------------------------------------------------------
--  DDL for Table XXAR_INV_PRINT_TMP
--------------------------------------------------------


  CREATE TABLE "APPS"."XXAR_INV_PRINT_TMP" 
   (	"REQUEST_ID" NUMBER, 
	"CUSTOMER_TRX_ID" NUMBER, 
	"INVOICE_NUM" VARCHAR2(100 BYTE), 
	"INVOICE_CURR_CODE" VARCHAR2(10 BYTE), 
	"INVOICE_CURR_SYMBOL" VARCHAR2(10 BYTE), 
	"HD_INV_TYPE" VARCHAR2(50 BYTE), 
	"BILL_TO_CUSTOMER" VARCHAR2(300 BYTE), 
	"BILL_TO_ADDRESS" VARCHAR2(1000 BYTE), 
	"BILL_TO_CONTACT" VARCHAR2(500 BYTE), 
	"HEADER_DESC" VARCHAR2(500 BYTE), 
	"TRX_DATE" VARCHAR2(50 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(100 BYTE), 
	"CUSTOMER_ORDER_NUMBER" VARCHAR2(100 BYTE), 
	"DATE_RECEIVED" VARCHAR2(50 BYTE), 
	"INVOICE_SALESREP" VARCHAR2(500 BYTE), 
	"ATTENDEE_EMAIL" VARCHAR2(500 BYTE), 
	"TERM" VARCHAR2(100 BYTE), 
	"INVOICE_TITLE" VARCHAR2(500 BYTE), 
	"INVOICE_STYLE_NAME" VARCHAR2(500 BYTE), 
	"INVOICE_DESC_ONE_LINE" VARCHAR2(3000 BYTE), 
	"INVOICE_FOOT_TOP" VARCHAR2(4000 BYTE), 
	"INVOICE_FOOT_BOTTOM" VARCHAR2(4000 BYTE), 
	"TAX_AMOUNT" NUMBER, 
	"GROUP_INV_LINE_BY" VARCHAR2(4000 BYTE), 
	"CUSTOMER_TRX_LINE_ID" NUMBER, 
	"LINE_TYPE" VARCHAR2(100 BYTE), 
	"LINE_NUMBER" NUMBER, 
	"LEVEL_1" VARCHAR2(4000 BYTE), 
	"LEVEL_2" VARCHAR2(4000 BYTE), 
	"LEVEL_3" VARCHAR2(4000 BYTE), 
	"QUANTITY_SELL" NUMBER, 
	"LONG_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"UNIT_SELL" NUMBER, 
	"SELL_AMOUNT" NUMBER, 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE UNIQUE INDEX "APPS"."XXAR_INV_PRINT_TMP_U1" ON "APPS"."XXAR_INV_PRINT_TMP" ("REQUEST_ID", "CUSTOMER_TRX_ID", "CUSTOMER_TRX_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

