--------------------------------------------------------
--  DDL for Table XXAR_GETPAID_CUSTOMER_MAPPING
--------------------------------------------------------


  CREATE TABLE "APPS"."XXAR_GETPAID_CUSTOMER_MAPPING" 
   (	"CUSTOMER_MAPPING_ID" NUMBER NOT NULL ENABLE, 
	"ORGANIZATION_ID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"MANAGED_CUSTOMER" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"LARGE_CUSTOMER" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"REPORTING_UNIT" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"SITE_FROM" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"SITE_TO" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"BUSINESS_UNIT" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"SITE_NAME" VARCHAR2(10 BYTE), 
	"GP_GROUP_ID" VARCHAR2(10 BYTE), 
	"COLLECTION_TYPE_ID" VARCHAR2(10 BYTE), 
	"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_LOGIN" NUMBER(15,0) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" ;
  CREATE UNIQUE INDEX "APPS"."XXAR_GP_CUST1_UQ" ON "APPS"."XXAR_GETPAID_CUSTOMER_MAPPING" ("CUSTOMER_MAPPING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;
  CREATE UNIQUE INDEX "APPS"."XXAR_GP_CUST2_UQ" ON "APPS"."XXAR_GETPAID_CUSTOMER_MAPPING" ("ORGANIZATION_ID", "MANAGED_CUSTOMER", "LARGE_CUSTOMER", "REPORTING_UNIT", "SITE_FROM", "SITE_TO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;
ALTER TABLE "APPS"."XXAR_GETPAID_CUSTOMER_MAPPING" ADD CONSTRAINT "XXAR_GP_CUST1_UQ" UNIQUE ("CUSTOMER_MAPPING_ID")
  USING INDEX "APPS"."XXAR_GP_CUST1_UQ"  ENABLE;
ALTER TABLE "APPS"."XXAR_GETPAID_CUSTOMER_MAPPING" ADD CONSTRAINT "XXAR_GP_CUST2_UQ" UNIQUE ("ORGANIZATION_ID", "MANAGED_CUSTOMER", "LARGE_CUSTOMER", "REPORTING_UNIT", "SITE_FROM", "SITE_TO")
  USING INDEX "APPS"."XXAR_GP_CUST2_UQ"  ENABLE;

