--------------------------------------------------------
--  DDL for Table XXAR_CREDITCARD_REF
--------------------------------------------------------


  CREATE TABLE "APPS"."XXAR_CREDITCARD_REF" 
   (	"TRX_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"REFERENCE_NUMBER" NUMBER NOT NULL ENABLE, 
	"CONTACT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTACT_PHONE" VARCHAR2(50 BYTE), 
	"EMAIL_RECIPIENT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ORIGINAL_TOTAL" NUMBER NOT NULL ENABLE, 
	"REMAINING_BALANCE" NUMBER NOT NULL ENABLE, 
	"PAYMENT_AMOUNT" NUMBER NOT NULL ENABLE, 
	"EXPIRATION_DATE" DATE NOT NULL ENABLE, 
	"PAID_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_LOGIN" NUMBER(15,0) NOT NULL ENABLE, 
	"ORG_ID" NUMBER NOT NULL ENABLE, 
	"BATCH_SOURCE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXAR_CREDITCARD_REF_N1" ON "APPS"."XXAR_CREDITCARD_REF" ("TRX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE UNIQUE INDEX "APPS"."XXAR_CREDITCARD_REF_U1" ON "APPS"."XXAR_CREDITCARD_REF" ("REFERENCE_NUMBER", "TRX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

