--------------------------------------------------------
--  DDL for Table XXAR_PAYMENTS_INTERFACE
--------------------------------------------------------


  CREATE TABLE "APPS"."XXAR_PAYMENTS_INTERFACE" 
   (	"TRANSMISSION_ID" NUMBER(15,0), 
	"TRANSMISSION_RECORD_ID" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"RECORD_TYPE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(30 BYTE), 
	"TRANSMISSION_REQUEST_ID" NUMBER(15,0), 
	"DESTINATION_ACCOUNT" VARCHAR2(25 BYTE), 
	"ORIGINATION" VARCHAR2(25 BYTE), 
	"DEPOSIT_DATE" DATE, 
	"DEPOSIT_TIME" VARCHAR2(8 BYTE), 
	"TRANSMISSION_RECORD_COUNT" NUMBER(15,0), 
	"LOCKBOX_NUMBER" VARCHAR2(30 BYTE), 
	"LOCKBOX_RECORD_COUNT" NUMBER, 
	"LOCKBOX_AMOUNT" NUMBER, 
	"BATCH_NAME" VARCHAR2(25 BYTE), 
	"BATCH_AMOUNT" NUMBER, 
	"BATCH_RECORD_COUNT" NUMBER(15,0), 
	"ITEM_NUMBER" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"REMITTANCE_AMOUNT" NUMBER, 
	"TRANSIT_ROUTING_NUMBER" VARCHAR2(25 BYTE), 
	"ACCOUNT" VARCHAR2(30 BYTE), 
	"CHECK_NUMBER" VARCHAR2(30 BYTE), 
	"REC_CUSTOMER_NUMBER" VARCHAR2(30 BYTE), 
	"OVERFLOW_INDICATOR" VARCHAR2(1 BYTE), 
	"OVERFLOW_SEQUENCE" NUMBER, 
	"INVOICE1" VARCHAR2(50 BYTE), 
	"INVOICE2" VARCHAR2(50 BYTE), 
	"INVOICE3" VARCHAR2(50 BYTE), 
	"AMOUNT_APPLIED1" NUMBER, 
	"AMOUNT_APPLIED2" NUMBER, 
	"AMOUNT_APPLIED3" NUMBER, 
	"CUSTOMER_NUMBER1" VARCHAR2(30 BYTE), 
	"CUSTOMER_NUMBER2" VARCHAR2(30 BYTE), 
	"CUSTOMER_NUMBER3" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"RECEIPT_DATE" DATE, 
	"COMMENTS" VARCHAR2(340 BYTE), 
	"INVOICE1_ORIG" VARCHAR2(50 BYTE), 
	"INVOICE2_ORIG" VARCHAR2(50 BYTE), 
	"INVOICE3_ORIG" VARCHAR2(50 BYTE), 
	"STATUS_MESSAGE1" VARCHAR2(100 BYTE), 
	"STATUS_MESSAGE2" VARCHAR2(100 BYTE), 
	"STATUS_MESSAGE3" VARCHAR2(100 BYTE), 
	"INPUT_STRING" VARCHAR2(80 BYTE), 
	"OUTPUT_STRING" VARCHAR2(300 BYTE), 
	"AMT_DUE_REMAINING1" NUMBER, 
	"AMT_DUE_REMAINING2" NUMBER, 
	"AMT_DUE_REMAINING3" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXAR_PAYMENTS_INFERFACE_N98" ON "APPS"."XXAR_PAYMENTS_INTERFACE" ("OVERFLOW_SEQUENCE", "RECORD_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

