CREATE TABLE "XXTM"."XXBS_REP_SPLITS" 
   (	
   "REP_SPLIT_ID" NUMBER(15,0) NOT NULL ENABLE 
	,"CUSTOMER_TRX_ID" NUMBER(15,0) NOT NULL ENABLE 
	,"SALESREP_ID" NUMBER(15,0) NOT NULL ENABLE 
	,"PRIMARY_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE 
	,"SPLIT_PERCENTAGE" NUMBER NOT NULL ENABLE 
	,"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE 
	,"CREATION_DATE" DATE NOT NULL ENABLE 
	,"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE 
	,"LAST_UPDATE_DATE" DATE NOT NULL ENABLE
	,"LAST_UPDATE_LOGIN" NUMBER(15,0) NOT NULL ENABLE 
	,"ADJUSTMENT" NUMBER(17,4)
	,"SALESPERSON_TYPE" VARCHAR2(100) 
	,"SEQUENCE_NUMBER" NUMBER(15,0) 
	, CONSTRAINT "XXBS_REP_SPLITS2TRX_FK" FOREIGN KEY ("CUSTOMER_TRX_ID")
	  REFERENCES "XXTM"."XXBS_CUSTOMER_TRX" ("CUSTOMER_TRX_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 15728640 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  CREATE UNIQUE INDEX "XXTM"."XXBS_REP_SPLITS_U1" ON "XXTM"."XXBS_REP_SPLITS" ("REP_SPLIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  ALTER TABLE "XXTM"."XXBS_REP_SPLITS" ADD CONSTRAINT "XXBS_REP_SPLITS_U1" PRIMARY KEY ("REP_SPLIT_ID")
  USING INDEX "XXTM"."XXBS_REP_SPLITS_U1"  ENABLE;

  CREATE INDEX "XXTM"."XXBS_REP_SPLITS_I1" ON "XXTM"."XXBS_REP_SPLITS" ("CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_REP_SPLITS_I2" ON "XXTM"."XXBS_REP_SPLITS" ("SALESREP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;


  GRANT ALTER ON "XXTM"."XXBS_REP_SPLITS" TO "APPS" WITH GRANT OPTION;
  GRANT DELETE ON "XXTM"."XXBS_REP_SPLITS" TO "APPS" WITH GRANT OPTION;
  GRANT INDEX ON "XXTM"."XXBS_REP_SPLITS" TO "APPS" WITH GRANT OPTION;
  GRANT INSERT ON "XXTM"."XXBS_REP_SPLITS" TO "APPS" WITH GRANT OPTION;
  GRANT SELECT ON "XXTM"."XXBS_REP_SPLITS" TO "APPS" WITH GRANT OPTION;
  GRANT UPDATE ON "XXTM"."XXBS_REP_SPLITS" TO "APPS" WITH GRANT OPTION;
  GRANT REFERENCES ON "XXTM"."XXBS_REP_SPLITS" TO "APPS" WITH GRANT OPTION;
  --GRANT SELECT ON "XXTM"."XXBS_REP_SPLITS" TO "XXBA_ROLE";


  CREATE SYNONYM APPS.XXBS_REP_SPLITS FOR XXTM.XXBS_REP_SPLITS;


  SELECT 'ALTER TABLE '||owner||'.'||table_name||' DISABLE CONSTRAINT '|| constraint_name||';'  from dba_constraints where table_name ='XXBS_REP_SPLITS';