CREATE TABLE "XXTM"."XXBS_CUSTOMER_TRX_LINES" 
   (	
    "CUSTOMER_TRX_LINE_ID" NUMBER(15,0) NOT NULL ENABLE 
	,"CUSTOMER_TRX_ID" NUMBER(15,0) NOT NULL ENABLE
	,"ORIG_CUSTOMER_TRX_ID" NUMBER(15,0) 
	,"ORIG_TRX_LINE_ID" NUMBER(15,0) 
	--,"LEVEL1_ID" NUMBER(15,0)
	--,"LEVEL2_ID" NUMBER(15,0) 
	--,"LEVEL3_ID" NUMBER(15,0) 
	--,"ORIG_LEVEL1_ID" NUMBER(15,0) 
	--,"ORIG_LEVEL2_ID" NUMBER(15,0) 
	--,"ORIG_LEVEL3_ID" NUMBER(15,0) 
	--,"EXPENDITURE_ITEM_ID" NUMBER(15,0) 
	,"PROJECT_ID" NUMBER(15,0) NOT NULL ENABLE 
	--,"SOURCE_ID" VARCHAR2(50) 
	,"LINE_NUMBER" NUMBER(15,0) 
	--,"STD_LINE_TYPE_ID" NUMBER(15,0) NOT NULL ENABLE 
	--,"INVENTORY_ITEM_ID" NUMBER NOT NULL ENABLE 
	,"ORG_ID" NUMBER NOT NULL ENABLE 
	,"PROJECT_ORG_ID" NUMBER(15,0) NOT NULL ENABLE 
	--,"PRICING_TYPE_ID" NUMBER(15,0) NOT NULL ENABLE 
	--,"QUANTITY" NUMBER DEFAULT 0 NOT NULL ENABLE 
	--,"EST_QUANTITY_SELL" NUMBER DEFAULT 0 NOT NULL ENABLE 
	--,"UNIT_COST" NUMBER DEFAULT 0 NOT NULL ENABLE 
	--,"EST_UNIT_COST" NUMBER DEFAULT 0 NOT NULL ENABLE 
	--,"COST_AMOUNT" NUMBER(38,2) DEFAULT 0 NOT NULL ENABLE 
	--,"EST_COST_AMOUNT" NUMBER(38,2) DEFAULT 0 NOT NULL ENABLE 
	,"QUANTITY_SELL" NUMBER DEFAULT 0 NOT NULL ENABLE 
	,"UNIT_SELL" NUMBER DEFAULT 0 NOT NULL ENABLE 
	,"SELL_AMOUNT" NUMBER(38,2) DEFAULT 0 NOT NULL ENABLE 
	--,"ADDITION_FLAT_FEE" NUMBER DEFAULT 0 NOT NULL ENABLE 
	--,"PA_WIP_CCID" NUMBER(15,0) 
	--,"AR_REV_CCID" NUMBER(15,0) NOT NULL ENABLE 
	--,"COS_CCID" NUMBER(15,0) 
	--,"ORIGINAL_PA_WIP_CCID" NUMBER(15,0) 
	--,"ORIGINAL_COS_CCID" NUMBER(15,0) 
	--,"ORIGINAL_AR_REV_CCID" NUMBER(15,0) 
	,"PRODUCT_TYPE_ID" VARCHAR2(30) NOT NULL ENABLE 
	--,"CLIENT_NOTES" VARCHAR2(4000) 
	--,"BILLER_NOTES" VARCHAR2(4000) 
	,"LONG_DESCRIPTION" VARCHAR2(4000) 
	--,"PROD_COMMENTS" VARCHAR2(4000) 
	--,"MDN" VARCHAR2(50) 
	--,"DELIVER_BY_DATE" DATE 
	--,"DIST_CYCLE_DESC" VARCHAR2(50) 
	--,"DIST_CYCLE_NUMBER" VARCHAR2(50) 
	--,"DIST_CYCLE_TYPE_ID" NUMBER(15,0) 
	--,"QTY_DISTRIBUTED" NUMBER 
	--,"TARIFFED_COST" NUMBER DEFAULT 0 NOT NULL ENABLE 
	--,"INVOICED_COST" NUMBER DEFAULT 0 NOT NULL ENABLE 
	--,"POS_LINE_ID" NUMBER(15,0) 
	--,"PARENT_POS_LINE_ID" NUMBER(15,0)
	--,"DIST_SITE_ID" NUMBER(15,0)
	--,"FREIGHT_MARKUP" NUMBER
	--,"MULTIPLE_SHIPMENT_INDICATOR" VARCHAR2(1)
	--,"MULTIPLE_SHIPMENT_REFERENCE" VARCHAR2(50)
	--,"THIRD_PARTY_SHIPMENT" VARCHAR2(1)
	--,"NUMBER_OF_DOCUMENTS" NUMBER
	--,"NUMBER_OF_SHIPMENTS" NUMBER
	--,"SHIP_DATE" DATE
	--,"SHIP_FROM_CITY" VARCHAR2(50)
	--,"SHIP_FROM_COMPANY" VARCHAR2(50)
	--,"SHIP_FROM_COUNTRY_CODE" VARCHAR2(50)
	--,"SHIP_FROM_ZIP_CODE" VARCHAR2(50)
	--,"SHIP_TO_ATTN" VARCHAR2(50)
	--,"SHIP_TO_CITY" VARCHAR2(50)
	--,"SHIP_TO_COMPANY" VARCHAR2(50)
	--,"SHIP_TO_COUNTRY" VARCHAR2(50)
	--,"SHIP_TO_STATE" VARCHAR2(50)
	--,"SHIP_FROM_STATE" VARCHAR2(50)
	--,"SHIP_TO_ZIP_CODE" VARCHAR2(50)
	--,"SHIPMENT_TYPE_ID" NUMBER(15,0)
	--,"SERVICE_TYPE_ID" NUMBER(15,0)
	--,"VENDOR_ID" NUMBER(15,0)
	--,"VENDOR_INVOICE_DATE" DATE
	--,"VENDOR_INVOICE_NUMBER" VARCHAR2(50) 
	--,"VENDOR_LONG_CODE" VARCHAR2(50)
	--,"WAYBILL_NUMBER" VARCHAR2(50)
	--,"IGNORE_FLAG" VARCHAR2(1) NOT NULL ENABLE
	--,"WO_REASON_CODE" VARCHAR2(100)
	--,"SHOW_QUANTITY_FLAG" VARCHAR2(1)
	--,"SHOW_UNIT_PRICE_FLAG" VARCHAR2(1)
	--,"DISPLAY_LINE_FLAG" VARCHAR2(1)
	--,"DISPLAY_NUM_UNITS" VARCHAR2(1)
	--,"TAXABLE_FLAG" VARCHAR2(1) NOT NULL ENABLE
	--,"REPORT_GROUP1_ID" NUMBER(15,0)
	--,"VOID_FLAG" VARCHAR2(1) NOT NULL ENABLE
	,"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE
	,"CREATION_DATE" DATE NOT NULL ENABLE
	,"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE
	,"LAST_UPDATE_DATE" DATE NOT NULL ENABLE
	,"LAST_UPDATE_LOGIN" NUMBER(15,0) NOT NULL ENABLE
	--,"AUDIT_TYPE" NUMBER(15,0) NOT NULL ENABLE
	--,"SUMMARY_LINE_ID" NUMBER(15,0)
	--,"MERGE_PARENT_LINE_ID" NUMBER(15,0)
	--,"LATE_COST_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
	--,"LATE_COST_STATUS_ID" NUMBER(15,0)
	--,"PA_PROCESSED_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
	--,"PA_PROCESSED_DATE" DATE
	--,"ORIG_INVENTORY_ITEM_ID" NUMBER(15,0) NOT NULL ENABLE
	--,"ORIG_PRODUCT_TYPE_ID" VARCHAR2(30) NOT NULL ENABLE
	--,"ORIG_PROJECT_ORG_ID" NUMBER(15,0) NOT NULL ENABLE
	,"AR_TRX_LINE_NUMBER" NUMBER(15,0)
	--,"CHANGE_VOID_FLAG" VARCHAR2(1) DEFAULT 'Y'
	--,"VAT_RATE_ID" NUMBER(15,0)
	--,"CLIENT_TURNAROUND_ID" NUMBER(15,0)
	--,"PROD_TURNAROUND_ID" NUMBER(15,0)
	--,"ILLINOIS_TAXABLE_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
	--,"AP_SUPPLIER_NUMBER" NUMBER(15,0)
	--,"AP_SUPPLIER" VARCHAR2(80)
	--,"AP_SUPPLIER_SITE" VARCHAR2(20)
	--,"AP_INVOICE_NUMBER" VARCHAR2(50)
	--,"AP_DESCRIPTION" VARCHAR2(240)
	--,"AP_PO_NUMBER" VARCHAR2(20)
	--,"QUOTE_LINE_ID" NUMBER(15,0)
	--,"SOURCE_PO_NUMBER" VARCHAR2(20)
	--,"SOURCE_CYCLE" VARCHAR2(10)
	--,"SOURCE_TRX_NUMBER" VARCHAR2(20)
	--,"SOURCE_PROJ_ORG_ID" NUMBER(15,0)
	--,"WORK_COMPLETED_DATE" DATE
	--,"MANUAL_PRICE" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
	--,"DISPLAY_UNIT_PRICE" VARCHAR2(1) DEFAULT 'Y'
	--,"UOFM" VARCHAR2(10)
	--,"BALLOT_ID" NUMBER(15,0)
	--,"CLIENT_NOTES_LAST_UPDATED_BY" NUMBER
	--,"CLIENT_NOTES_LAST_UPDATE_DATE" DATE
	--,"BILLER_NOTES_LAST_UPDATED_BY" NUMBER
	--,"BILLER_NOTES_LAST_UPDATE_DATE" DATE
	--,"PROD_COMMENTS_LAST_UPDATED_BY" NUMBER
	--,"PROD_COMMENTS_LAST_UPDATE_DATE" DATE
	--,"PO_TRANSACTION_DISTRIBUTION_ID" NUMBER(15,0)
	--,"FOREIGN_SYSTEM_NUMBER" VARCHAR2(25)
	--,"PO_REQUESTOR_NAME" VARCHAR2(240)
	--,"PO_BUYER_ID" NUMBER(15,0)
	--,"SALESREP_PROJECT_ID" NUMBER(15,0)
	--,"PO_HEADER_DESCRIPTION" VARCHAR2(240)
	--,"PO_TRANSACTION_LINE_ID" NUMBER(15,0)
	--,"PO_TRANSACTION_HEADER_ID" NUMBER(15,0)
	--,"PO_TRANSACTION_SHIPMENT_ID" NUMBER(15,0)
	--,"TAX_CODE" VARCHAR2(50)
	--,"SALESTAX_AMOUNT" NUMBER
	--,"COMMISSION_FLAG" VARCHAR2(1)
	--,"COMMISSION_AMOUNT" NUMBER
	--,"WITNESS_NAME" VARCHAR2(60)
	--,"REPORTER_NAME" VARCHAR2(60)
	--,"BILL_TO_CONTACT_NAME" VARCHAR2(60)
	--,"SHIP_TO_CONTACT_NAME" VARCHAR2(60)
	--,"DEDUCTION" VARCHAR2(1) DEFAULT 'N'
	--,"SPLIT_LINE_PCT" NUMBER
	--,"COST_TYPE" VARCHAR2(1) DEFAULT 'D' NOT NULL ENABLE
	--,"LONG_DESCRIPTION_ALT" VARCHAR2(4000)
	--,"REVENUE_DATE" DATE
	--,"LEDES_BILLING_TYPE" VARCHAR2(1)
	--,"LEDES_FUTURE_1" VARCHAR2(30)
	--,"LEDES_FUTURE_2" VARCHAR2(30)
	--,"LEDES_FUTURE_3" VARCHAR2(30)
	--,"LEDES_FUTURE_4" VARCHAR2(30)
	--,"CONSOLIDATED_PARENT_LINE_ID" NUMBER(15,0)
	--,"CONVERT_CONSOLIDATED_UNITS" VARCHAR2(1)
	--,"TOTAL_DISTRIBUTION_QTY" NUMBER(22,7)
	--,"PA_EVENT_ID" NUMBER
	--,"FEEDER_SYSTEM_COST" NUMBER
	--,"NON_USAGE_EST_COST_AMOUNT" NUMBER
	--,"SOURCE_LINE_ID" VARCHAR2(15)
	
	
	--Newly Added
     ,"LINE_TYPE" VARCHAR2(100) DEFAULT 'Line'    
	 ,"STATUS"  VARCHAR2(100)  
	 ,"LEVEL_1"  VARCHAR2(4000)  
	 ,"LEVEL_2"  VARCHAR2(4000)  
	 ,"LEVEL_3"  VARCHAR2(4000)  
	 ,"REVISED_CUSTOMER_TRX_ID" NUMBER(15,0) 
	 ,"REVISED_CUSTOMER_TRX_LINE_ID" NUMBER(15,0) 
	
	--, CONSTRAINT "XXBS_TRX_LINES2LEVEL1_FK" FOREIGN KEY ("LEVEL1_ID")
	--  REFERENCES "XXTM"."XXBS_LEVEL1" ("LEVEL1_ID") DISABLE
	--, CONSTRAINT "XXBS_TRX_LINES2LEVEL2_FK" FOREIGN KEY ("LEVEL2_ID")
	--  REFERENCES "XXTM"."XXBS_LEVEL2" ("LEVEL2_ID") DISABLE
	--, CONSTRAINT "XXBS_TRX_LINES2LEVEL3_FK" FOREIGN KEY ("LEVEL3_ID")
	--  REFERENCES "XXTM"."XXBS_LEVEL3" ("LEVEL3_ID") DISABLE
	--, CONSTRAINT "XXBS_TRX_LINES2ORIG_LEVEL1_FK" FOREIGN KEY ("ORIG_LEVEL1_ID")
	--  REFERENCES "XXTM"."XXBS_LEVEL1" ("LEVEL1_ID") DISABLE
	--, CONSTRAINT "XXBS_TRX_LINES2ORIG_LEVEL2_FK" FOREIGN KEY ("ORIG_LEVEL2_ID")
	--  REFERENCES "XXTM"."XXBS_LEVEL2" ("LEVEL2_ID") DISABLE
	--, CONSTRAINT "XXBS_TRX_LINES2ORIG_LEVEL3_FK" FOREIGN KEY ("ORIG_LEVEL3_ID")
	--  REFERENCES "XXTM"."XXBS_LEVEL3" ("LEVEL3_ID") DISABLE
	--, CONSTRAINT "XXBS_TRX_LINES2REP_GROUP1_FK" FOREIGN KEY ("REPORT_GROUP1_ID")
	--  REFERENCES "XXTM"."XXBS_REPORT_GROUP1" ("REPORT_GROUP1_ID") ENABLE
	, CONSTRAINT "XXBS_TRX_LINES2TRX_FK" FOREIGN KEY ("CUSTOMER_TRX_ID")
	  REFERENCES "XXTM"."XXBS_CUSTOMER_TRX" ("CUSTOMER_TRX_ID") ENABLE
	--, CONSTRAINT "XCTL_XVR1_FK" FOREIGN KEY ("VAT_RATE_ID")
	--  REFERENCES "XXTM"."XXBS_VAT_RATES" ("VAT_RATE_ID") ENABLE
	--, CONSTRAINT "XCTL_XTQL_FK" FOREIGN KEY ("QUOTE_LINE_ID")
	--  REFERENCES "XXTM"."XXBS_TRX_QUOTE_LINES" ("TRX_QUOTE_LINE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152000 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  
  CREATE UNIQUE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_U1" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("CUSTOMER_TRX_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  ALTER TABLE "XXTM"."XXBS_CUSTOMER_TRX_LINES" ADD CONSTRAINT "XXBS_CUSTOMER_TRX_LINES_U1" PRIMARY KEY ("CUSTOMER_TRX_LINE_ID")
  USING INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_U1"  ENABLE;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_I1" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
/*
  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_I15" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("EXPENDITURE_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_I2" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("LEVEL1_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_I20" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("SUMMARY_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 52428800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_I28" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("PROJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_I3" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("LAST_UPDATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_I39" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("VENDOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_I53" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("PO_TRANSACTION_DISTRIBUTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_I7" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("LEVEL3_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_LINES_N99" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("CUSTOMER_TRX_ID", "PROJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 52428800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I11" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("PROJECT_ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I12" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("PA_WIP_CCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I13" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("AR_REV_CCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I14" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("DIST_SITE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I16" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("ORIGINAL_AR_REV_CCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I17" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("INVENTORY_ITEM_ID", "ORGANIZATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I18" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("PRODUCT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I21" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("ORIGINAL_PA_WIP_CCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I3" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("ORIG_LEVEL1_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I30" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("SERVICE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I31" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("SHIPMENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I34" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("COS_CCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I35" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("ORIGINAL_COS_CCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I37" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("ORIG_CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I4" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("LEVEL2_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I45" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("DISPLAY_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I49" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("PARENT_POS_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I5" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("ORIG_LEVEL2_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_I6" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("ORIG_LEVEL3_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_MDN" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("MDN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINES_SRC_LINE" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("SOURCE_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_LINE_QUOTE_ID" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("QUOTE_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_L_AUDIT_TYPE" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("AUDIT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_L_CONS_PARENT" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("CONSOLIDATED_PARENT_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_L_LATE_COST_STAT" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("LATE_COST_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_L_STD_LINE_TYPE" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("STD_LINE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_L_WO_REASON" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("WO_REASON_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 73400320 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_POS_ID" ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" ("POS_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
*/

  GRANT ALTER ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" TO "APPS" WITH GRANT OPTION;
  GRANT DELETE ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" TO "APPS" WITH GRANT OPTION;
  GRANT INDEX ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" TO "APPS" WITH GRANT OPTION;
  GRANT INSERT ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" TO "APPS" WITH GRANT OPTION;
  GRANT SELECT ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" TO "APPS" WITH GRANT OPTION;
  GRANT UPDATE ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" TO "APPS" WITH GRANT OPTION;
  GRANT REFERENCES ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" TO "APPS" WITH GRANT OPTION;
--  GRANT SELECT ON "XXTM"."XXBS_CUSTOMER_TRX_LINES" TO "XXBA_ROLE";

CREATE SYNONYM APPS.XXBS_CUSTOMER_TRX_LINES FOR XXTM.XXBS_CUSTOMER_TRX_LINES;


SELECT 'ALTER TABLE '||owner||'.'||table_name||' DISABLE CONSTRAINT '|| constraint_name||';'  from dba_constraints where table_name ='XXBS_CUSTOMER_TRX_LINES';

