CREATE TABLE "XXTM"."XXBS_INVOICE_STYLES" 
   (	
    "INVOICE_STYLE_ID" NUMBER(20,0) NOT NULL ENABLE 
	,"INVOICE_STYLE_NAME" VARCHAR2(50) NOT NULL ENABLE 
	,"LANGUAGE" VARCHAR2(20) NOT NULL ENABLE 
	--,"LAYOUT_ID" NUMBER(20,0) 
	,"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE 
	,"CREATION_DATE" DATE NOT NULL ENABLE 
	,"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE 
	,"LAST_UPDATE_DATE" DATE NOT NULL ENABLE 
	,"LAST_UPDATE_LOGIN" NUMBER(15,0) 
	--,"HEAD_COMPANY_LOGO" LONG 
	--,"HEAD_COMPANY_NAME1" VARCHAR2(65) 
	--,"HEAD_COMPANY_NAME2" VARCHAR2(65) 
	,"HEAD_ATTENTION" VARCHAR2(240) 
	--,"HEAD_INQUIRIES" VARCHAR2(20) 
	,"HEAD_INVOICE_NUMBER" VARCHAR2(240) 
	,"HEAD_INVOICE_DATE" VARCHAR2(240) 
	--,"HEAD_MERRILL_PROJECT" VARCHAR2(20) 
	,"HEAD_DATE_RECEIVED" VARCHAR2(240) 
	,"HEAD_SALESPERSON" VARCHAR2(240) 
	,"HEAD_OUR_ORDER_NUMBER" VARCHAR2(240) 
	,"HEAD_CUST_ORDER_NUMBER" VARCHAR2(240) 
	,"HEAD_TERMS" VARCHAR2(240) 
	--,"FOOT_REMIT_TO" VARCHAR2(20) 
	--,"FOOT_COMPANY_NAME1" VARCHAR2(30) 
	--,"FOOT_COMPANY_NAME2" VARCHAR2(30) 
	--,"FOOT_COMPANY_ADDRESS1" VARCHAR2(20) 
	--,"FOOT_COMPANY_ADDRESS2" VARCHAR2(20) 
	--,"FOOT_PAY_INVOICE" VARCHAR2(50) 
	--,"FOOT_SERVICE_CHARGE" VARCHAR2(150) 
	--,"FOOT_PRINTED" VARCHAR2(20) 
	,"FOOT_PAGE" VARCHAR2(240) 
	--,"DETAIL_SUBTOTAL" VARCHAR2(30) 
	,"DETAIL_FREIGHT" VARCHAR2(240) 
	,"DETAIL_TAX" VARCHAR2(240) 
	,"DETAIL_POSTAGE" VARCHAR2(240) 
	,"DETAIL_TOTAL_INVOICE" VARCHAR2(240) 
	--,"DETAIL_PREPAYMENT" VARCHAR2(40) 
	--,"DETAIL_CHECK" VARCHAR2(20) 
	--,"DETAIL_BALANCE_DUE" VARCHAR2(40) 
	--,"DETAIL_QUANTITY" VARCHAR2(20) 
	--,"DETAIL_DESCRIPTION" VARCHAR2(20) 
	--,"DETAIL_UNIT_PRICE" VARCHAR2(20) 
	--,"DETAIL_TOTAL" VARCHAR2(20) 
	--,"HEAD_LOCATION" VARCHAR2(20) 
	--,"DETAIL_DOCUMENT_SERVICES" VARCHAR2(150) 
	,"FOOT_LEFT" VARCHAR2(4000) 
	,"FOOT_RIGHT" VARCHAR2(4000) 
	--,"HEAD_PRELIM" VARCHAR2(40) 
	--,"HEAD_COPY" VARCHAR2(40) 
	--,"HEAD_CTD" VARCHAR2(40) 
	--,"DETAIL_PRELIM" VARCHAR2(150) 
	--,"DETAIL_COPY" VARCHAR2(150) 
	--,"DETAIL_CTD" VARCHAR2(150) 
	--,"HEAD_CUSTOMER_VAT" VARCHAR2(50) 
	--,"HEAD_DUMMY" VARCHAR2(40) 
	--,"DETAIL_DUMMY" VARCHAR2(150) 
	--,"DETAIL_FEDERAL_TAX" VARCHAR2(40) 
	--,"DETAIL_POSTAGE_HANDLING" VARCHAR2(40) 
	--,"DETAIL_BASE_TOTAL" VARCHAR2(20) 
	--,"HEAD_TAXPAYER_ID" VARCHAR2(20) 
	--,"HEAD_COMPANY_NAME3" VARCHAR2(65) 
	--,"HEAD_ADDRESS1" VARCHAR2(240) 
	--,"HEAD_ADDRESS2" VARCHAR2(240) 
	--,"HEAD_ADDRESS3" VARCHAR2(240) 
	--,"HEAD_COUNTRY" VARCHAR2(60) 
	--,"HEAD_PHONE" VARCHAR2(40) 
	--,"HEAD_FAX" VARCHAR2(40) 
	,"HEAD_EMAIL" VARCHAR2(240) 
	--,"DISPLAY_SALESREP" VARCHAR2(1) 
	--,"COURT_NAME" VARCHAR2(240) 
	--,"DETAIL_UNIT" VARCHAR2(20) 
	,"DETAIL_SUBTOTAL_PRETAX" VARCHAR2(240)
	, "INACTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 516096 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  
  CREATE UNIQUE INDEX "XXTM"."XXBS_INVOICE_STYLES_U1" ON "XXTM"."XXBS_INVOICE_STYLES" ("INVOICE_STYLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  ALTER TABLE "XXTM"."XXBS_INVOICE_STYLES" ADD CONSTRAINT "XXBS_INVOICE_STYLES_U1" PRIMARY KEY ("INVOICE_STYLE_ID")
  USING INDEX "XXTM"."XXBS_INVOICE_STYLES_U1"  ENABLE;

  ALTER TABLE "XXTM"."XXBS_INVOICE_STYLES" ADD CONSTRAINT "XXBS_INVOICE_STYLES_U2" UNIQUE ("INVOICE_STYLE_NAME")
  USING INDEX "XXTM"."XXBS_INVOICE_STYLES_I1"  ENABLE;

  CREATE INDEX "XXTM"."XXBS_INVOICE_STYLES_I1" ON "XXTM"."XXBS_INVOICE_STYLES" ("INVOICE_STYLE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;


  GRANT ALTER ON "XXTM"."XXBS_INVOICE_STYLES" TO "APPS" WITH GRANT OPTION;
  GRANT DELETE ON "XXTM"."XXBS_INVOICE_STYLES" TO "APPS" WITH GRANT OPTION;
  GRANT INDEX ON "XXTM"."XXBS_INVOICE_STYLES" TO "APPS" WITH GRANT OPTION;
  GRANT INSERT ON "XXTM"."XXBS_INVOICE_STYLES" TO "APPS" WITH GRANT OPTION;
  GRANT SELECT ON "XXTM"."XXBS_INVOICE_STYLES" TO "APPS" WITH GRANT OPTION;
  GRANT UPDATE ON "XXTM"."XXBS_INVOICE_STYLES" TO "APPS" WITH GRANT OPTION;
  GRANT REFERENCES ON "XXTM"."XXBS_INVOICE_STYLES" TO "APPS" WITH GRANT OPTION;
  --GRANT SELECT ON "XXTM"."XXBS_INVOICE_STYLES" TO "XXBA_ROLE";
  --GRANT SELECT ON "XXTM"."XXBS_INVOICE_STYLES" TO "CSSHT_CSS_REPORT_ROLE";
  
CREATE SYNONYM APPS.XXBS_INVOICE_STYLES FOR XXTM.XXBS_INVOICE_STYLES;


SELECT 'ALTER TABLE '||owner||'.'||table_name||' DISABLE CONSTRAINT '|| constraint_name||';'  from dba_constraints where table_name ='XXBS_INVOICE_STYLES';  
