
  CREATE TABLE "XXTM"."XXBS_TRX_AUDITS" 
   (	
    "TRX_AUDIT_ID" NUMBER(15,0) NOT NULL ENABLE 
	,"CUSTOMER_TRX_ID" NUMBER(15,0) NOT NULL ENABLE
	,"PROBLEM_DESC" VARCHAR2(4000) NOT NULL ENABLE 
	,"FIX_DESC" VARCHAR2(4000)
	,"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE
	,"CREATION_DATE" DATE NOT NULL ENABLE
	,"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE
	,"LAST_UPDATE_DATE" DATE NOT NULL ENABLE
	,"LAST_UPDATE_LOGIN" NUMBER(15,0) NOT NULL ENABLE 
	, CONSTRAINT "XIA_XCT_FK" FOREIGN KEY ("CUSTOMER_TRX_ID")
	  REFERENCES "XXTM"."XXBS_CUSTOMER_TRX" ("CUSTOMER_TRX_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 41943040 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  CREATE UNIQUE INDEX "XXTM"."XXBS_TRX_AUDITS_U1" ON "XXTM"."XXBS_TRX_AUDITS" ("TRX_AUDIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 516096 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  ALTER TABLE "XXTM"."XXBS_TRX_AUDITS" ADD CONSTRAINT "XXBS_TRX_AUDITS_U1" PRIMARY KEY ("TRX_AUDIT_ID")
  USING INDEX "XXTM"."XXBS_TRX_AUDITS_U1"  ENABLE;

  CREATE INDEX "XXTM"."XXBS_TRX_AUDITS_I1" ON "XXTM"."XXBS_TRX_AUDITS" ("CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 516096 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;


  GRANT ALTER ON "XXTM"."XXBS_TRX_AUDITS" TO "APPS" WITH GRANT OPTION;
  GRANT DELETE ON "XXTM"."XXBS_TRX_AUDITS" TO "APPS" WITH GRANT OPTION;
  GRANT INDEX ON "XXTM"."XXBS_TRX_AUDITS" TO "APPS" WITH GRANT OPTION;
  GRANT INSERT ON "XXTM"."XXBS_TRX_AUDITS" TO "APPS" WITH GRANT OPTION;
  GRANT SELECT ON "XXTM"."XXBS_TRX_AUDITS" TO "APPS" WITH GRANT OPTION;
  GRANT UPDATE ON "XXTM"."XXBS_TRX_AUDITS" TO "APPS" WITH GRANT OPTION;
  GRANT REFERENCES ON "XXTM"."XXBS_TRX_AUDITS" TO "APPS" WITH GRANT OPTION;
  --GRANT SELECT ON "XXTM"."XXBS_TRX_AUDITS" TO "XXBA_ROLE";


  CREATE SYNONYM APPS.XXBS_TRX_AUDITS FOR XXTM.XXBS_TRX_AUDITS;