CREATE TABLE "XXTM"."XXBS_CUSTOMER_TRX" 
   (	
    "CUSTOMER_TRX_ID" NUMBER(15,0) NOT NULL ENABLE
	--,"DEAL_ID" NUMBER(15,0) NOT NULL ENABLE 
	,"PARENT_CUSTOMER_TRX_ID" NUMBER(15,0)
	,"AR_TRX_NUMBER" VARCHAR2(20)
	--,"ORGANIZATION_ID" NUMBER(15,0) 
	,"SET_OF_BOOKS_ID" NUMBER(15,0) NOT NULL ENABLE
	,"PRIMARY_PRODUCT_TYPE_ID" VARCHAR2(100) NOT NULL ENABLE
	,"PROFILE_ID" NUMBER(15,0)
	,"CUST_TRX_TYPE_ID" NUMBER(15,0) NOT NULL ENABLE
	,"TRX_DATE" DATE NOT NULL ENABLE
	,"DATE_RECEIVED" DATE
	,"PERIOD_NAME" VARCHAR2(15) NOT NULL ENABLE
	--,"APPLICATION_ID" NUMBER(15,0) NOT NULL ENABLE
	,"PRIMARY_SALESREP_ID" NUMBER(15,0) 
	,"DESCRIPTION" VARCHAR2(100)
	,"COMMENTS" VARCHAR2(4000)
	,"BILL_TO_ADDRESS_ID" NUMBER(15,0) NOT NULL ENABLE
	,"BILL_TO_CUSTOMER_ID" NUMBER(15,0) NOT NULL ENABLE
	,"ATTENDEE" VARCHAR2(4000)
	,"ATTENDEE_EMAIL" VARCHAR2(4000)
	,"INVOICE_ADDRESS_ID" NUMBER(15,0) NOT NULL ENABLE
	,"BILL_TO_CONTACT_ID" NUMBER(15,0) 
	--,"BILL_TO_CONTACT_JOB" VARCHAR2(100)
	--,"SECONDARY_CUST_NAME_ADDR" VARCHAR2(4000)
	--,"SITE_PHONE" VARCHAR2(50)
	,"ORDER_NUMBER" VARCHAR2(50)
	,"CUSTOMER_ORDER_NUMBER" VARCHAR2(50)
	--,"INVOICE_TITLE" VARCHAR2(4000)
	--,"ANTI_GL_PERIOD_NAME" VARCHAR2(15)
	--,"ANTICIPATED_REVENUE" NUMBER
	,"OWNING_BILLER_ID" NUMBER(15,0) NOT NULL ENABLE
	,"ACTIVE_BILLER_ID" NUMBER(15,0) NOT NULL ENABLE
	,"CURRENT_STATUS_DATE" DATE NOT NULL ENABLE
	,"CURRENT_STATUS" VARCHAR2(50) NOT NULL ENABLE
	,"TERM_ID" NUMBER(15,0) NOT NULL ENABLE
	,"CURRENCY_CODE" VARCHAR2(15) NOT NULL ENABLE
	,"ENTERED_CURRENCY_CODE" VARCHAR2(15) NOT NULL ENABLE
	,"EXCHANGE_DATE" DATE
	,"EXCHANGE_RATE" NUMBER
	,"EXCHANGE_RATE_TYPE" VARCHAR2(30)
	--,"VAT_REG_NO" VARCHAR2(50)
	--,"VAT_REGISTERED" VARCHAR2(1) NOT NULL ENABLE
	--,"INVOICE_FOOTER_BOTTOM" VARCHAR2(4000)
	--,"INVOICE_FOOTER_TOP" VARCHAR2(4000)
	--,"DISPLAY_JOB_TITLES" VARCHAR2(1) NOT NULL ENABLE 
	--,"DISPLAY_JOB_TOTALS" VARCHAR2(1) NOT NULL ENABLE
	--,"DISPLAY_NUMBER_OF_PAGES" VARCHAR2(1) NOT NULL ENABLE
	--,"DISPLAY_PRICES" VARCHAR2(1) NOT NULL ENABLE
	--,"DISPLAY_SUB_TOTALS" VARCHAR2(1) NOT NULL ENABLE
	,"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE
	,"CREATION_DATE" DATE NOT NULL ENABLE
	,"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE
	,"LAST_UPDATE_DATE" DATE NOT NULL ENABLE
	,"LAST_UPDATE_LOGIN" NUMBER(15,0) NOT NULL ENABLE
	,"PROJECT_CATEGORY_ID" NUMBER(15,0)
	--,"FUND" VARCHAR2(100)
	--,"QTY_DISTRIBUTED" NUMBER
	--,"CLIENT_MATTER_NUMBER" VARCHAR2(100)
	,"PRIMARY_PROJECT_ORG_ID" NUMBER(15,0)
	--,"AR_REC_CCID" NUMBER(15,0) NOT NULL ENABLE
	--,"ORIG_AR_REC_CCID" NUMBER(15,0) NOT NULL ENABLE
	--,"TEXT_MODEL_ID" NUMBER(15,0)
	--,"PRICING_MODEL_ID" NUMBER(15,0)
	--,"SUMMARY_MODEL_ID" NUMBER(15,0)
	--,"APPROVAL_CODE" NUMBER(15,0)
	--,"APPROVAL_NOTES" VARCHAR2(4000)
	--,"LC_METHOD_ID" NUMBER(15,0)
	--,"LC_CUSTOMER_TRX_ID" NUMBER(15,0)
	--,"INVOICE_STYLE_ID" NUMBER(15,0) NOT NULL ENABLE
	--,"PREPAY_CHECK" VARCHAR2(30)
	--,"PREPAY_AMOUNT" NUMBER
	--,"PRINT_INVOICE_REP_DESC" VARCHAR2(100)
	--,"PRINT_SEC_ADDR_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
	--,"VAT_RULE_ID" NUMBER(15,0)
	,"ORIGINAL_PROJECT_ID" NUMBER(15,0)
	--,"DISPLAY_LEVEL1_TITLE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE
	--,"DISPLAY_LEVEL1_TOTAL" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE
	--,"DISPLAY_LEVEL2_TITLE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE
	--,"DISPLAY_LEVEL2_TOTAL" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE
	--,"DISPLAY_LEVEL3_TITLE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE
	--,"DISPLAY_LEVEL3_TOTAL" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE
	--,"DISPLAY_TURNAROUND" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE
	--,"ONE_LINE_INVOICE_DESC" VARCHAR2(4000)
	--,"PRINT_REQUEST" NUMBER(15,0)
	--,"INVOICE_COMMENTS" VARCHAR2(4000)
	--,"ACCRUAL_PERIOD" VARCHAR2(15)
	--,"QUOTE_MODEL_ID" NUMBER(15,0)
	--,"DISPLAY_COST" VARCHAR2(1) DEFAULT 'Y'
	--,"DISPLAY_SELL" VARCHAR2(1) DEFAULT 'Y'
	--,"DISPLAY_AVG" VARCHAR2(1) DEFAULT 'Y'
	--,"DISPLAY_MARGIN" VARCHAR2(1) DEFAULT 'Y'
	--,"COUNTRY_OF_ISSUER" VARCHAR2(2)
	--,"HAND_DELIVER_FLAG" VARCHAR2(50) DEFAULT 'N'
	--,"SAMPLE_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE 
	--,"E_MAIL_ADDRESS" VARCHAR2(100)
	--,"DISPLAY_UNIT_SELL" VARCHAR2(1) DEFAULT 'N'
	--,"NATIONAL_INVOICE" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
	--,"INV_COMM_LAST_UPDATED_BY" NUMBER
	--,"INV_COMM_LAST_UPDATE_DATE" DATE
	--,"COMMENTS_LAST_UPDATED_BY" NUMBER
	--,"COMMENTS_LAST_UPDATE_DATE" DATE
	--,"ONE_DESC_LAST_UPDATED_BY" NUMBER
	--,"ONE_DESC_LAST_UPDATE_DATE" DATE
	--,"PERIOD_DATE" DATE
	--,"SAR_ID" NUMBER(15,0)
	--,"DISPLAY_POSTAGE_HANDLING" VARCHAR2(1) DEFAULT 'Y'
	--,"CANADIAN_FED_TAX_EXEMPT" VARCHAR2(1)
	--,"QUEBEC_PROV_TAX" VARCHAR2(1)
	--,"ONTARIO_PROV_EXEMPT" VARCHAR2(1)
	--,"BC_PROV_EXEMPT" VARCHAR2(1)
	--,"DISPLAY_POSTAGE_LINE" VARCHAR2(1)
	--,"PROJECT_CLOSE_FLAG" VARCHAR2(1)
	--,"JOB_NUMBER" VARCHAR2(20)
	--,"AUTOBILL_FLAG" VARCHAR2(1)
	--,"JOB_DATE" DATE
	--,"CASE_NUMBER" VARCHAR2(24)
	--,"CASE_CAPTION" VARCHAR2(60)
	--,"ORIG_SYSTEM_BILL_CONTACT_ID" NUMBER(15,0)
	--,"ORIG_AR_TRX_NUMBER" VARCHAR2(20)
	--,"PARENT_ORIG_TRX_NUMBER" VARCHAR2(20)
	--,"LATE_FEE" NUMBER
	--,"SORT_BY_TRNARND_DT" VARCHAR2(1) DEFAULT 'N'
	--,"DISPLAY_BASE_TOTAL" VARCHAR2(1)
	--,"INVESTMENT_BANK" VARCHAR2(100)
	--,"COMPANY" VARCHAR2(50)
	--,"PROJECT_START_DATE" DATE
	--,"TOTAL_PAGES" NUMBER
	--,"RECUR_INVC_GRP" VARCHAR2(1)
	--,"RECUR_INVC_END_DT" DATE
	--,"TAXPAYER_ID" VARCHAR2(20)
	--,"ACCRUAL_COST" NUMBER
	--,"ACCRUAL_REVENUE" NUMBER
	--,"ACCRUAL_ACTIVITY_DATE" DATE
	--,"PRE_PAYMENT_ID" NUMBER
	--,"DISPLAY_MARGIN_DETAIL" VARCHAR2(1) DEFAULT 'N'
	--,"ONE_LINE_INVOICE_DESC_ID" NUMBER(15,0)
	--,"INVOICE_FOOTER_TOP_ID" NUMBER(15,0)
	--,"INVOICE_FOOTER_BOTTOM_ID" NUMBER(15,0)
	,"SOURCE_SYSTEM" VARCHAR2(5)
	--,"CR_FIRM_MATTER_ID" VARCHAR2(100)
	--,"CR_DEPO_DURATION" VARCHAR2(100)
	--,"CR_MATTER_ID" VARCHAR2(100)
	--,"CR_FILE_NUMBER" VARCHAR2(100)
	--,"CR_CLAIM_NUMBER" VARCHAR2(100)
	--,"CR_CLAIM_TYPE" VARCHAR2(100)
	--,"CR_DATE_OF_LOSS" VARCHAR2(100)
	--,"CR_NAME_OF_INSURED" VARCHAR2(100)
	--,"CR_CLIENT_REF_2" VARCHAR2(100)
	--,"CR_SUB_CLAIM_NUM" VARCHAR2(100)
	--,"CR_CLIENT_REF_1" VARCHAR2(100)
	--,"CR_CLIENT_PO" VARCHAR2(100)
	--,"CR_EMAIL_CHECK" VARCHAR2(1)
	--,"CR_EMAIL_ADDRESS" VARCHAR2(100)
	--,"CR_CANCEL_CHECK" VARCHAR2(1)
	--,"CR_CANCEL_REASON" VARCHAR2(100)
	--,"CR_CANCEL_NOTE" VARCHAR2(4000)
	--,"CR_TX_COURT_COST" VARCHAR2(1)
	--,"FEDERAL_FLAG" VARCHAR2(1)
	--,"SOLD_TO_COMPANY" VARCHAR2(120)
	--,"SOLD_TO_ADDRESS_ID" NUMBER
	--,"RB_NUMBER" VARCHAR2(150)
	--,"CASE_ID" VARCHAR2(150)
	--,"M1_GROUP" VARCHAR2(150)
	--,"REVENUE_ESTIMATE" NUMBER
	--,"REV_EST_ENTERED_CURR" VARCHAR2(12)
	--,"REV_EST_EXCH_RATE" NUMBER
	--,"REV_EST_EXCH_DATE" DATE 
	--,"CR_BUSINESS_SEGMENT" VARCHAR2(150)
	--,"CR_CLAIM_OFFICE" VARCHAR2(150)
	--,"PAYING_CUSTOMER_ID" NUMBER(15,0)
	--,"PAYING_SITE_USE_ID" NUMBER(15,0)
	--,"DISPLAY_CATEGORY_TOTAL" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE 
	--,"ACTIVITY_COMMENTS" VARCHAR2(4000)
	--,"USER_COUNT" NUMBER
	--,"SPLIT_BILLING_PERCENTAGE" NUMBER
	
	, "PROJECT_COMPLETE_DATE" DATE
	, "COST_SUM_SEND_DATE" DATE
	, "MARGIN_REPORT_SEND_DATE" DATE
	, "BILL_REMARK" VARCHAR2(4000)
	, "INVOICE_CLASS" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
	
	
	--,"INVOICE_STYLE_ID" NUMBER(20,0)  NOT NULL ENABLE
    ,"INVOICE_STYLE_NAME" VARCHAR2(100) DEFAULT 'TOPPAN DET ENG INT HK' NOT NULL ENABLE  
	,"INVOICE_TITLE" VARCHAR2(4000) 
	,"INVOICE_DESC_ONE_LINE" VARCHAR2(4000) 
	,"TAX_DESC" VARCHAR2(4000) 
	,"TAX_AMOUNT" NUMBER 
	,"INVOICE_FOOT_TOP" VARCHAR2(4000) 
	,"INVOICE_FOOT_BOTTOM" VARCHAR2(4000) DEFAULT 'NOTES: 1.  This is a computer generated invoice.  No signature is required.'   
	,"DISPLAY_SALESPERSON" VARCHAR2(1) DEFAULT 'N'
	,"DISPLAY_LEVEL_1" VARCHAR2(1) DEFAULT 'N'
	,"DISPLAY_LEVEL_1_TOTAL" VARCHAR2(1)  DEFAULT 'N' 
	,"DISPLAY_LEVEL_2" VARCHAR2(1)  DEFAULT 'N'
	,"DISPLAY_LEVEL_2_TOTAL" VARCHAR2(1)  DEFAULT 'N' 
	,"DISPLAY_LEVEL_3" VARCHAR2(1)  DEFAULT 'N'
	,"DISPLAY_LEVEL_3_TOTAL" VARCHAR2(1)  DEFAULT 'N' 	
	,"PRELIMINARY" VARCHAR2(1)  DEFAULT 'N'
	,"SEC_BILL_TO_CUSTOMER_ID" NUMBER(15,0) 
	,"ORG_ID" NUMBER(15,0) NOT NULL ENABLE
	
	,"PRINT_REQUEST_ID" NUMBER(15,0)
	
	,"PREVIOUS_STATUS"  VARCHAR2(50) 
	
	,"TOTAL_LINE_AMOUNT" NUMBER(38,2) DEFAULT 0
	,"REVISED_CUSTOMER_TRX_ID" NUMBER(15,0) 
	
	,"REVISE_TO_NUM"  NUMBER(15,0)
	
	, "BILL_REMARK_2" VARCHAR2(4000)
	 --,CONSTRAINT "XCT_XVR_FK" FOREIGN KEY ("VAT_RULE_ID")
	 -- REFERENCES "XXTM"."XXBS_VAT_RULES" ("VAT_RULE_ID") ENABLE
	 --,CONSTRAINT "XXBS_TRX2DEALS_FK" FOREIGN KEY ("DEAL_ID")
	 -- REFERENCES "XXTM"."XXBS_DEALS" ("DEAL_ID") ENABLE
	 --,CONSTRAINT "XXBS_TRX2PARENT_FK" FOREIGN KEY ("PARENT_CUSTOMER_TRX_ID")
	 -- REFERENCES "XXTM"."XXBS_CUSTOMER_TRX" ("CUSTOMER_TRX_ID") DISABLE 
	 --,CONSTRAINT "XCT_XSM_FK" FOREIGN KEY ("QUOTE_MODEL_ID")
	 -- REFERENCES "XXTM"."XXBS_SUMMARY_MODELS" ("SUMMARY_MODEL_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 209715200 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  
  
  CREATE UNIQUE INDEX "XXTM"."XXBS_CUSTOMER_TRX_U1" ON "XXTM"."XXBS_CUSTOMER_TRX" ("CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  ALTER TABLE "XXTM"."XXBS_CUSTOMER_TRX" ADD CONSTRAINT "XXBS_CUSTOMER_TRX_U1" PRIMARY KEY ("CUSTOMER_TRX_ID")
  USING INDEX "XXTM"."XXBS_CUSTOMER_TRX_U1"  ENABLE;

/*
  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I1" ON "XXTM"."XXBS_CUSTOMER_TRX" ("PARENT_CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I12" ON "XXTM"."XXBS_CUSTOMER_TRX" ("CURRENT_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I16" ON "XXTM"."XXBS_CUSTOMER_TRX" ("ORGANIZATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I2" ON "XXTM"."XXBS_CUSTOMER_TRX" ("DEAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXBS_CUSTOMER_TRX_I20" ON "XXTM"."XXBS_CUSTOMER_TRX" ("OWNING_BILLER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I21" ON "XXTM"."XXBS_CUSTOMER_TRX" ("PRIMARY_SALESREP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I24" ON "XXTM"."XXBS_CUSTOMER_TRX" ("SET_OF_BOOKS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;


  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I25" ON "XXTM"."XXBS_CUSTOMER_TRX" ("APPLICATION_ID", "PERIOD_NAME", "SET_OF_BOOKS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I27" ON "XXTM"."XXBS_CUSTOMER_TRX" ("CUSTOMER_TRX_ID", "ORGANIZATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I32" ON "XXTM"."XXBS_CUSTOMER_TRX" ("PRIMARY_PROJECT_ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I33" ON "XXTM"."XXBS_CUSTOMER_TRX" ("AR_REC_CCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I34" ON "XXTM"."XXBS_CUSTOMER_TRX" ("TEXT_MODEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I35" ON "XXTM"."XXBS_CUSTOMER_TRX" ("PRICING_MODEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I36" ON "XXTM"."XXBS_CUSTOMER_TRX" ("SUMMARY_MODEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I38" ON "XXTM"."XXBS_CUSTOMER_TRX" ("LC_CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I4" ON "XXTM"."XXBS_CUSTOMER_TRX" ("ACTIVE_BILLER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I40" ON "XXTM"."XXBS_CUSTOMER_TRX" ("ORIGINAL_PROJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I41" ON "XXTM"."XXBS_CUSTOMER_TRX" ("INVOICE_STYLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE UNIQUE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I42" ON "XXTM"."XXBS_CUSTOMER_TRX" ("AR_TRX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I43" ON "XXTM"."XXBS_CUSTOMER_TRX" ("ORDER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I5" ON "XXTM"."XXBS_CUSTOMER_TRX" ("BILL_TO_CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXBS_CUSTOMER_TRX_I50" ON "XXTM"."XXBS_CUSTOMER_TRX" ("ORIG_AR_TRX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I6" ON "XXTM"."XXBS_CUSTOMER_TRX" ("BILL_TO_ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I7" ON "XXTM"."XXBS_CUSTOMER_TRX" ("BILL_TO_CONTACT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I8" ON "XXTM"."XXBS_CUSTOMER_TRX" ("PRIMARY_PRODUCT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_I9" ON "XXTM"."XXBS_CUSTOMER_TRX" ("PROFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_N1" ON "XXTM"."XXBS_CUSTOMER_TRX" ("CUSTOMER_ORDER_NUMBER", "ORGANIZATION_ID", "DESCRIPTION") 
  PCTFREE 10 INITRANS 11 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUSTOMER_TRX_SARID_IDX" ON "XXTM"."XXBS_CUSTOMER_TRX" ("SAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_PERIOD_DATE" ON "XXTM"."XXBS_CUSTOMER_TRX" ("PERIOD_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_QUOTE_ID_N" ON "XXTM"."XXBS_CUSTOMER_TRX" ("QUOTE_MODEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "XXTM"."XXBS_CUST_TRX_VAT_RULE_ID_N" ON "XXTM"."XXBS_CUSTOMER_TRX" ("VAT_RULE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
*/

  GRANT ALTER ON "XXTM"."XXBS_CUSTOMER_TRX" TO "APPS" WITH GRANT OPTION;
  GRANT DELETE ON "XXTM"."XXBS_CUSTOMER_TRX" TO "APPS" WITH GRANT OPTION;
  GRANT INDEX ON "XXTM"."XXBS_CUSTOMER_TRX" TO "APPS" WITH GRANT OPTION;
  GRANT INSERT ON "XXTM"."XXBS_CUSTOMER_TRX" TO "APPS" WITH GRANT OPTION;
  GRANT SELECT ON "XXTM"."XXBS_CUSTOMER_TRX" TO "APPS" WITH GRANT OPTION;
  GRANT UPDATE ON "XXTM"."XXBS_CUSTOMER_TRX" TO "APPS" WITH GRANT OPTION;
  GRANT REFERENCES ON "XXTM"."XXBS_CUSTOMER_TRX" TO "APPS" WITH GRANT OPTION;
--  GRANT SELECT ON "XXTM"."XXBS_CUSTOMER_TRX" TO "XXBA_ROLE";
--  GRANT SELECT ON "XXTM"."XXBS_CUSTOMER_TRX" TO "CSSHT_CSS_REPORT_ROLE";


CREATE SYNONYM APPS.XXBS_CUSTOMER_TRX FOR XXTM.XXBS_CUSTOMER_TRX;


ALTER TABLE "XXTM"."XXBS_CUSTOMER_TRX" MODIFY "TOTAL_LINE_AMOUNT" NUMBER(38,2) DEFAULT 0;

SELECT 'ALTER TABLE '||owner||'.'||table_name||' DISABLE CONSTRAINT '|| constraint_name||';'  from dba_constraints where table_name ='XXBS_CUSTOMER_TRX';



