
  CREATE TABLE "XXTM"."XXBS_TRX_ACTIVITY" 
   (	
   "TRX_ACTIVITY_ID" NUMBER(15,0) NOT NULL ENABLE 
	,"CUSTOMER_TRX_ID" NUMBER(15,0) NOT NULL ENABLE 
	,"ACTIVITY_DATE" DATE NOT NULL ENABLE
	,"ACTIVITY_TYPE" VARCHAR2(100) NOT NULL ENABLE
	,"PERSON" NUMBER(15,0) NOT NULL ENABLE 
	,"CHANGE_FROM" VARCHAR2(4000)
	,"CHANGE_TO" VARCHAR2(4000)
	,"APPROVAL_ACTION" VARCHAR2(4000)
	,"APPROVAL_REASON" VARCHAR2(4000)
	,"JUSTIFICATION" VARCHAR2(4000)
	,"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE 
	,"CREATION_DATE" DATE NOT NULL ENABLE 
	,"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE 
	,"LAST_UPDATE_DATE" DATE NOT NULL ENABLE
	,"LAST_UPDATE_LOGIN" NUMBER(15,0) NOT NULL ENABLE 
	, CONSTRAINT "XXBS_TRX_ACT2TRX_FK" FOREIGN KEY ("CUSTOMER_TRX_ID")
	  REFERENCES "XXTM"."XXBS_CUSTOMER_TRX" ("CUSTOMER_TRX_ID") ENABLE	
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE UNIQUE INDEX "XXTM"."XXBS_TRX_ACTIVITY_U1" ON "XXTM"."XXBS_TRX_ACTIVITY" ("TRX_ACTIVITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

  ALTER TABLE "XXTM"."XXBS_TRX_ACTIVITY" ADD CONSTRAINT "XXBS_TRX_ACTIVITY_U1" PRIMARY KEY ("TRX_ACTIVITY_ID")
  USING INDEX "XXTM"."XXBS_TRX_ACTIVITY_U1"  ENABLE;


  CREATE INDEX "XXTM"."XXBS_TRX_ACTIVITY_N1" ON "XXTM"."XXBS_TRX_ACTIVITY" ("CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  

  GRANT ALTER ON "XXTM"."XXBS_TRX_ACTIVITY" TO "APPS" WITH GRANT OPTION;
  GRANT DELETE ON "XXTM"."XXBS_TRX_ACTIVITY" TO "APPS" WITH GRANT OPTION;
  GRANT INDEX ON "XXTM"."XXBS_TRX_ACTIVITY" TO "APPS" WITH GRANT OPTION;
  GRANT INSERT ON "XXTM"."XXBS_TRX_ACTIVITY" TO "APPS" WITH GRANT OPTION;
  GRANT SELECT ON "XXTM"."XXBS_TRX_ACTIVITY" TO "APPS" WITH GRANT OPTION;
  GRANT UPDATE ON "XXTM"."XXBS_TRX_ACTIVITY" TO "APPS" WITH GRANT OPTION;
  GRANT REFERENCES ON "XXTM"."XXBS_TRX_ACTIVITY" TO "APPS" WITH GRANT OPTION;
  
  
  CREATE SYNONYM APPS.XXBS_TRX_ACTIVITY FOR XXTM.XXBS_TRX_ACTIVITY;