CREATE TABLE "XXTM"."XXBS_COMBINE_REQ" 
   (	
   "COMBINE_REQ_ID" NUMBER(15,0) NOT NULL ENABLE 
    ,"REQ_TYPE" VARCHAR2(50)  NOT NULL ENABLE 
	,"PARENT_CUSTOMER_TRX_ID" NUMBER(15,0) NOT NULL ENABLE 
	,"COMBINE_REQ_NUMBER" VARCHAR2(50)  NOT NULL ENABLE 
	,"STATUS" VARCHAR2(50)  NOT NULL ENABLE 
	,"APPROVAL_REASON" VARCHAR2(4000)
	,"JUSTIFICATION" VARCHAR2(4000)
	,"ORG_ID" NUMBER(15,0) NOT NULL ENABLE 	
	,"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE 
	,"CREATION_DATE" DATE NOT NULL ENABLE 
	,"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE 
	,"LAST_UPDATE_DATE" DATE NOT NULL ENABLE
	,"LAST_UPDATE_LOGIN" NUMBER(15,0) NOT NULL ENABLE 
	--, CONSTRAINT "XXBS_COMBINE_REQ_CUST_TRX_FK" FOREIGN KEY ("PARENT_CUSTOMER_TRX_ID")
	--  REFERENCES "XXTM"."XXBS_CUSTOMER_TRX" ("CUSTOMER_TRX_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 15728640 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  CREATE UNIQUE INDEX "XXTM"."XXBS_COMBINE_REQ_ID_U1" ON "XXTM"."XXBS_COMBINE_REQ" ("COMBINE_REQ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
  
  ALTER TABLE "XXTM"."XXBS_COMBINE_REQ" ADD CONSTRAINT "XXBS_COMBINE_REQ_ID_U1" PRIMARY KEY ("COMBINE_REQ_ID")
  USING INDEX "XXTM"."XXBS_COMBINE_REQ_ID_U1"  ENABLE;



  GRANT ALTER ON "XXTM"."XXBS_COMBINE_REQ" TO "APPS" WITH GRANT OPTION;
  GRANT DELETE ON "XXTM"."XXBS_COMBINE_REQ" TO "APPS" WITH GRANT OPTION;
  GRANT INDEX ON "XXTM"."XXBS_COMBINE_REQ" TO "APPS" WITH GRANT OPTION;
  GRANT INSERT ON "XXTM"."XXBS_COMBINE_REQ" TO "APPS" WITH GRANT OPTION;
  GRANT SELECT ON "XXTM"."XXBS_COMBINE_REQ" TO "APPS" WITH GRANT OPTION;
  GRANT UPDATE ON "XXTM"."XXBS_COMBINE_REQ" TO "APPS" WITH GRANT OPTION;
  GRANT REFERENCES ON "XXTM"."XXBS_COMBINE_REQ" TO "APPS" WITH GRANT OPTION;



  CREATE SYNONYM APPS.XXBS_COMBINE_REQ FOR XXTM.XXBS_COMBINE_REQ;




  