--------------------------------------------------------
--  DDL for Table XXCM_ERROR_LINES
--------------------------------------------------------

  CREATE TABLE "APPS"."XXCM_ERROR_LINES" 
   (	"ERROR_LINE_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"ERROR_GROUP_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"APPLICATION_NAME" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"MODULE_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ERROR_NUMBER" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_LOGIN" NUMBER(15,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXCM_ERROR_LINES_N1" ON "APPS"."XXCM_ERROR_LINES" ("ERROR_GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE UNIQUE INDEX "APPS"."XXCM_ERROR_LINES_U1" ON "APPS"."XXCM_ERROR_LINES" ("ERROR_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

