create table apps.xxconv_po
(
 seq_num                    number,
 operating_unit_name        varchar2(240),
 po_num                     varchar2(20),
 po_date                    date,
 po_type					varchar2(240),
 vendor_name                varchar2(240),
 vendor_num					varchar2(240),
 vendor_site_code           varchar2(15),
 vendor_contact             varchar2(240),
 ship_to_location           varchar2(60),
 bill_to_location           varchar2(60),
 currency_code              varchar2(15),
 rate_type                  varchar2(30),
 rate_date                  date,
 rate                       number,
 agent_name                 varchar2(240),
 authorization_status		varchar2(100),
 closed_code				varchar2(240),
 comments                   varchar2(1000),
 payment_terms              varchar2(50),
 line_num                   number,
 line_type					varchar2(240),
 item_segment1              varchar2(2),
 item_segment2              varchar2(20),
 item_segment3              varchar2(6),
 category                   varchar2(100),
 item_description           varchar2(240),
 unit_of_measure            varchar2(25),
 quantity                   number,
 unit_price                 number,
 list_price_per_unit		number,
 shipment_num 				number,
 line_ship_to_location      varchar2(60),
 line_unit_of_measure       varchar2(25), 
 line_quantity				number,
 vendor_product_num         varchar2(25),
 promised_date              date,
 need_by_date               date,
 RECEIVE_CLOSE_TOLERANCE	number,
 INVOICE_CLOSE_TOLERANCE	number,
 MATCH_APPROVAL_LEVEL		varchar2(100),
 MATCH_OPTION 				varchar2(100),
 LINE_CLOSED_CODE			varchar2(100),
 QUANTITY_RECEIVED			number,
 QUANTITY_CANCELLED			number,
 QUANTITY_BILLED			number,
 DAYS_EARLY_RECEIPT_ALLOWED number,
 DAYS_LATE_RECEIPT_ALLOWED 	number,
 RECEIPT_DAYS_EXCEPTION_CODE varchar2(100),
 QTY_RCV_TOLERANCE 			number,
 QTY_RCV_EXCEPTION_CODE		varchar2(100),
 ALLOW_SUBSTITUTE_RECEIPTS_FLAG varchar2(100),
 ROUTING_NAME 				varchar2(100),
 ENFORCE_SHIP_TO_LOCATION_CODE varchar2(100),
 DISTRIBUTION_NUM 			number,
 destination_type_code      varchar2(25),
 requestor					varchar2(240),
 DELIVER_TO 				varchar2(240),
 DIST_QUANTITY_ORDERED 		number,
 DIST_QUANTITY_BILLED 		number,
 charge_account             varchar2(60),
 budget_account             varchar2(60),
 PROJECT_NUMBER 			varchar2(100),
 TASK_NUMBER 				number,
 EXPENDITURE_TYPE			varchar2(100),
 ORG 						varchar2(100),
 EXPENDITURE_ITEM_DATE		date,
	creation_date              date,
	request_id                 number,
 status_flag                varchar2(1)    default 'N',
 error_message              varchar2(1000),
 vendor_contact_name        varchar2(240),
 org_id                     number,
 batch_id                   number,
 interface_header_id        number,
 interface_line_id          number,
 interface_distribution_id  number
) tablespace apps_ts_interface;

create or replace public synonym xxconv_po for apps.xxconv_po;

create index apps.xxconv_po_n1 on apps.xxconv_po
(request_id)
 tablespace apps_ts_interface;
