--------------------------------------------------------
--  DDL for Table XXFA_GLOBAL_ASSETS
--------------------------------------------------------


  CREATE TABLE "APPS"."XXFA_GLOBAL_ASSETS" 
   (	"REQUEST_ID" NUMBER, 
	"SEQ_NO" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(50 BYTE), 
	"ASSET_NUMBER" VARCHAR2(15 BYTE), 
	"ASSET_DESCRIPTION" VARCHAR2(100 BYTE), 
	"ASSET_MAJOR_CATEGORY" VARCHAR2(30 BYTE), 
	"ASSET_MINOR_CATEGORY" VARCHAR2(30 BYTE), 
	"SERIAL_NUMBER" VARCHAR2(35 BYTE), 
	"TAG_NUMBER" VARCHAR2(15 BYTE), 
	"FISCAL_YEAR" NUMBER, 
	"PERIOD_ENTERED" VARCHAR2(15 BYTE), 
	"ASSET_BOOK" VARCHAR2(15 BYTE), 
	"DATE_PLACED_IN_SERVICE" VARCHAR2(20 BYTE), 
	"LIFE_IN_MONTHS" NUMBER, 
	"COUNTRY" VARCHAR2(30 BYTE), 
	"STATE" VARCHAR2(30 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"LOCATION" VARCHAR2(30 BYTE), 
	"ASSET_CURRENCY" VARCHAR2(10 BYTE), 
	"ASSET_COST" NUMBER, 
	"TRANSACTION_DATE" DATE, 
	"EXCHANGE_RATE" NUMBER, 
	"COST_IN_USD" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"ASSET_TYPE" VARCHAR2(11 BYTE), 
	"TRANSACTION_HEADER_ID" NUMBER, 
	"SOURCE_TRANSACTION_HEADER_ID" NUMBER, 
	"ASSET_ID" NUMBER, 
	"BOOK_TYPE_CODE" VARCHAR2(15 BYTE), 
	"BOOK_CLASS" VARCHAR2(15 BYTE), 
	"SOB_ID" NUMBER, 
	"SOB_TYPE" VARCHAR2(1 BYTE), 
	"COMPANY_NAME" VARCHAR2(30 BYTE), 
	"CATEGORY_FLEX_STRUCTURE" NUMBER, 
	"ASSET_COST_ACCT" VARCHAR2(25 BYTE), 
	"DEPRN_RESERVE_ACCT" VARCHAR2(25 BYTE), 
	"DEPRECIATION_RESRV_ACCT_STRING" VARCHAR2(155 BYTE), 
	"ASSET_COST_ACCOUNT_STRING" VARCHAR2(155 BYTE), 
	"DEPRECIATION_ACCOUNT_STRING" VARCHAR2(155 BYTE), 
	"DEPRN_EXPENSE_ACCOUNT_CCID" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXFA_GA_IDX1" ON "APPS"."XXFA_GLOBAL_ASSETS" ("REQUEST_ID", "ASSET_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXFA_GA_IDX2" ON "APPS"."XXFA_GLOBAL_ASSETS" ("SEQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXFA_GA_IDX3" ON "APPS"."XXFA_GLOBAL_ASSETS" ("BOOK_TYPE_CODE", "BOOK_CLASS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXFA_GA_IDX4" ON "APPS"."XXFA_GLOBAL_ASSETS" ("TRANSACTION_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

