--------------------------------------------------------
--  DDL for Table XXFA_GLOBAL_ASSET_RETIREMENTS
--------------------------------------------------------


  CREATE TABLE "APPS"."XXFA_GLOBAL_ASSET_RETIREMENTS" 
   (	"REQUEST_ID" NUMBER, 
	"SEQ_NO" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(50 BYTE), 
	"BOOK_TYPE_CODE" VARCHAR2(15 BYTE), 
	"BOOK_CLASS" VARCHAR2(15 BYTE), 
	"SOB_ID" NUMBER, 
	"SOB_TYPE" VARCHAR2(1 BYTE), 
	"ASSET_ID" NUMBER, 
	"ASSET_TYPE" VARCHAR2(11 BYTE), 
	"ASSET_NUMBER" VARCHAR2(15 BYTE), 
	"ASSET_DESCRIPTION" VARCHAR2(100 BYTE), 
	"ASSET_BOOK" VARCHAR2(15 BYTE), 
	"DATE_PLACED_IN_SERVICE" VARCHAR2(20 BYTE), 
	"TRANSACTION_HEADER_ID" NUMBER, 
	"SOURCE_TRANSACTION_HEADER_ID" NUMBER, 
	"TRANSACTION_DATE" DATE, 
	"PERIOD_EFFECTIVE" VARCHAR2(15 BYTE), 
	"PERIOD_ENTERED" VARCHAR2(15 BYTE), 
	"ASSET_CURRENCY" VARCHAR2(10 BYTE), 
	"COST_RETIRED" NUMBER, 
	"RESERVE_RETIRED" NUMBER, 
	"NET_BOOK_VALUE_RETIRED" NUMBER, 
	"PROCEEDS_OF_SALE" NUMBER, 
	"REMOVAL_COST" NUMBER, 
	"GAIN_LOSS" NUMBER, 
	"EXCHANGE_RATE" NUMBER, 
	"CONVERSION_DATE" DATE, 
	"COST_RETIRED_USD" NUMBER, 
	"RESERVE_RETIRED_USD" NUMBER, 
	"NET_BOOK_VALUE_RETIRED_USD" NUMBER, 
	"PROCEEDS_OF_SALE_USD" NUMBER, 
	"REMOVAL_COST_USD" NUMBER, 
	"GAIN_LOSS_USD" NUMBER, 
	"DEPRN_EXPENSE_ACCOUNT_CCID" NUMBER, 
	"DEPRECIATION_ACCOUNT_STRING" VARCHAR2(155 BYTE), 
	"ASSET_COST_ACCOUNT_STRING" VARCHAR2(155 BYTE), 
	"ASSET_COST_ACCT" VARCHAR2(25 BYTE), 
	"DEPRN_RESERVE_ACCT" VARCHAR2(25 BYTE), 
	"DEPRECIATION_RESRV_ACCT_STRING" VARCHAR2(155 BYTE), 
	"COMPANY_NAME" VARCHAR2(30 BYTE), 
	"CATEGORY_FLEX_STRUCTURE" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXFA_GA_RET_IDX1" ON "APPS"."XXFA_GLOBAL_ASSET_RETIREMENTS" ("REQUEST_ID", "ASSET_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXFA_GA_RET_IDX2" ON "APPS"."XXFA_GLOBAL_ASSET_RETIREMENTS" ("SEQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXFA_GA_RET_IDX3" ON "APPS"."XXFA_GLOBAL_ASSET_RETIREMENTS" ("BOOK_TYPE_CODE", "BOOK_CLASS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE INDEX "APPS"."XXFA_GA_RET_IDX4" ON "APPS"."XXFA_GLOBAL_ASSET_RETIREMENTS" ("TRANSACTION_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;

