DROP TABLE XXTM.XXHR_EMPLOYEE_UPLOAD CASCADE CONSTRAINTS;

CREATE TABLE XXTM.XXHR_EMPLOYEE_UPLOAD
(
  XEU_ID                NUMBER,
  LAST_NAME             VARCHAR2(40 BYTE),
  FIRST_NAME            VARCHAR2(40 BYTE),
  MI                    VARCHAR2(60 BYTE),
  EMP_NUMBER            VARCHAR2(50 BYTE)       NOT NULL,
  SEX                   VARCHAR2(30 BYTE),
  STREET1               VARCHAR2(60 BYTE),
  STREET2               VARCHAR2(60 BYTE),
  CITY                  VARCHAR2(30 BYTE),
  STATE                 VARCHAR2(30 BYTE),
  ZIP_CODE              VARCHAR2(30 BYTE),
  COUNTRY               VARCHAR2(30 BYTE),
  TERM_STATUS           VARCHAR2(10 BYTE)       NOT NULL,
  START_DATE_ACTIVE     DATE,
  TERM_DATE             DATE,
  EMAIL                 VARCHAR2(60 BYTE),
  DEFAULT_EXPENSE_ACCT  VARCHAR2(100 BYTE),
  SUPERVISOR            VARCHAR2(25 BYTE),
  LOCATION_CODE         VARCHAR2(10 BYTE),
  MESSAGE               VARCHAR2(2000 BYTE),
  CREATED_BY            VARCHAR2(35 BYTE)       NOT NULL,
  CREATION_DATE         DATE                    NOT NULL,
  LAST_UPDATED_BY       VARCHAR2(35 BYTE)       NOT NULL,
  LAST_UPDATE_DATE      DATE                    NOT NULL,
  LAST_UPDATE_LOGIN     NUMBER(15)              NOT NULL,
  SET_OF_BOOKS_NAME     VARCHAR2(50 BYTE),
  GRADE                 VARCHAR2(30 BYTE),
  APPROVAL_GRADE        VARCHAR2(30 BYTE),
  BUS_GROUP             VARCHAR2(10 BYTE),
  OVERRIDE_FLAG         VARCHAR2(1 BYTE),
  JOB_ID                NUMBER,
  JOB_CODE              VARCHAR2(9 BYTE),
  JOB_CODE_GRADE        VARCHAR2(9 BYTE),
  JOB_DESCRIPTION       VARCHAR2(200 BYTE),
  KNOWN_AS              VARCHAR2(30 BYTE),
  LEGAL_ENTITY          VARCHAR2(10 BYTE),
  PRODUCT_LINE          VARCHAR2(50 BYTE),
  SITE                  VARCHAR2(10 BYTE),
  COST_CENTER           VARCHAR2(10 BYTE)
)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

CREATE UNIQUE INDEX XXTM.XXHR_XEU_EMP_NUMBER_UK ON XXTM.XXHR_EMPLOYEE_UPLOAD
(EMP_NUMBER)
NOLOGGING
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
           
CREATE UNIQUE INDEX XXTM.XXHR_XEU_ID_PK ON XXTM.XXHR_EMPLOYEE_UPLOAD
(XEU_ID)
NOLOGGING
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE XXTM.XXHR_EMPLOYEE_UPLOAD ADD (
  CONSTRAINT XXHR_XEU_ID_PK
  PRIMARY KEY
  (XEU_ID)
  USING INDEX XXTM.XXHR_XEU_ID_PK
  ENABLE VALIDATE
,  CONSTRAINT XXHR_XEU_EMP_NUMBER_UK
  UNIQUE (EMP_NUMBER)
  USING INDEX XXTM.XXHR_XEU_EMP_NUMBER_UK
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM XXHR_EMPLOYEE_UPLOAD FOR XXTM.XXHR_EMPLOYEE_UPLOAD;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON XXTM.XXHR_EMPLOYEE_UPLOAD TO APPS;