DROP TABLE XXTM.XXPA_TRANSACTION_INTERFACE_ALL;

CREATE TABLE "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" 
(	
    "TRANSACTION_SOURCE" VARCHAR2(30 BYTE), 
    "BATCH_NAME" VARCHAR2(240 BYTE), 
    "EXPENDITURE_ENDING_DATE" DATE, 
    "EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
    "ORGANIZATION_NAME" VARCHAR2(240 BYTE), 
    "EXPENDITURE_ITEM_DATE" DATE, 
    "PROJECT_NUMBER" VARCHAR2(25 BYTE), 
    "TASK_NUMBER" VARCHAR2(25 BYTE), 
    "EXPENDITURE_TYPE" VARCHAR2(30 BYTE), 
    "NON_LABOR_RESOURCE" VARCHAR2(20 BYTE), 
    "NON_LABOR_RESOURCE_ORG_NAME" VARCHAR2(240 BYTE), 
    "QUANTITY" NUMBER, 
    "RAW_COST" NUMBER, 
    "EXPENDITURE_COMMENT" VARCHAR2(240 BYTE), 
    "TRANSACTION_STATUS_CODE" VARCHAR2(2 BYTE), 
    "TRANSACTION_REJECTION_CODE" VARCHAR2(30 BYTE), 
    "EXPENDITURE_ID" NUMBER(15,0), 
    "ORIG_TRANSACTION_REFERENCE" VARCHAR2(50 BYTE), 
    "ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
    "ATTRIBUTE1" VARCHAR2(150 BYTE), 
    "ATTRIBUTE2" VARCHAR2(150 BYTE), 
    "ATTRIBUTE3" VARCHAR2(150 BYTE), 
    "ATTRIBUTE4" VARCHAR2(150 BYTE), 
    "ATTRIBUTE5" VARCHAR2(150 BYTE), 
    "ATTRIBUTE6" VARCHAR2(150 BYTE), 
    "ATTRIBUTE7" VARCHAR2(150 BYTE), 
    "ATTRIBUTE8" VARCHAR2(150 BYTE), 
    "ATTRIBUTE9" VARCHAR2(150 BYTE), 
    "ATTRIBUTE10" VARCHAR2(150 BYTE), 
    "RAW_COST_RATE" NUMBER, 
    "INTERFACE_ID" NUMBER(15,0), 
    "UNMATCHED_NEGATIVE_TXN_FLAG" VARCHAR2(1 BYTE), 
    "EXPENDITURE_ITEM_ID" NUMBER(15,0), 
    "ORG_ID" NUMBER(15,0) DEFAULT NULL, 
    "DR_CODE_COMBINATION_ID" NUMBER(15,0), 
    "CR_CODE_COMBINATION_ID" NUMBER(15,0), 
    "CDL_SYSTEM_REFERENCE1" VARCHAR2(30 BYTE), 
    "CDL_SYSTEM_REFERENCE2" VARCHAR2(30 BYTE), 
    "CDL_SYSTEM_REFERENCE3" VARCHAR2(30 BYTE), 
    "GL_DATE" DATE, 
    "BURDENED_COST" NUMBER, 
    "BURDENED_COST_RATE" NUMBER, 
    "SYSTEM_LINKAGE" VARCHAR2(30 BYTE), 
    "TXN_INTERFACE_ID" NUMBER(15,0), 
    "USER_TRANSACTION_SOURCE" VARCHAR2(80 BYTE), 
    "CREATED_BY" NUMBER(15,0), 
    "CREATION_DATE" DATE, 
    "LAST_UPDATED_BY" NUMBER(15,0), 
    "LAST_UPDATE_DATE" DATE, 
    "RECEIPT_CURRENCY_AMOUNT" NUMBER, 
    "RECEIPT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
    "RECEIPT_EXCHANGE_RATE" NUMBER, 
    "DENOM_CURRENCY_CODE" VARCHAR2(15 BYTE), 
    "DENOM_RAW_COST" NUMBER, 
    "DENOM_BURDENED_COST" NUMBER, 
    "ACCT_RATE_DATE" DATE, 
    "ACCT_RATE_TYPE" VARCHAR2(30 BYTE), 
    "ACCT_EXCHANGE_RATE" NUMBER, 
    "ACCT_RAW_COST" NUMBER, 
    "ACCT_BURDENED_COST" NUMBER, 
    "ACCT_EXCHANGE_ROUNDING_LIMIT" NUMBER, 
    "PROJECT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
    "PROJECT_RATE_DATE" DATE, 
    "PROJECT_RATE_TYPE" VARCHAR2(30 BYTE), 
    "PROJECT_EXCHANGE_RATE" NUMBER, 
    "ORIG_EXP_TXN_REFERENCE1" VARCHAR2(60 BYTE), 
    "ORIG_EXP_TXN_REFERENCE2" VARCHAR2(60 BYTE), 
    "ORIG_EXP_TXN_REFERENCE3" VARCHAR2(60 BYTE), 
    "ORIG_USER_EXP_TXN_REFERENCE" VARCHAR2(60 BYTE), 
    "VENDOR_NUMBER" VARCHAR2(30 BYTE), 
    "OVERRIDE_TO_ORGANIZATION_NAME" VARCHAR2(240 BYTE), 
    "REVERSED_ORIG_TXN_REFERENCE" VARCHAR2(30 BYTE), 
    "BILLABLE_FLAG" VARCHAR2(1 BYTE), 
    "PERSON_BUSINESS_GROUP_NAME" VARCHAR2(240 BYTE), 
    "PROJFUNC_CURRENCY_CODE" VARCHAR2(15 BYTE), 
    "PROJFUNC_COST_RATE_TYPE" VARCHAR2(30 BYTE), 
    "PROJFUNC_COST_RATE_DATE" DATE, 
    "PROJFUNC_COST_EXCHANGE_RATE" NUMBER, 
    "PROJECT_RAW_COST" NUMBER, 
    "PROJECT_BURDENED_COST" NUMBER, 
    "ASSIGNMENT_NAME" VARCHAR2(80 BYTE), 
    "WORK_TYPE_NAME" VARCHAR2(80 BYTE), 
    "CDL_SYSTEM_REFERENCE4" VARCHAR2(30 BYTE), 
    "ACCRUAL_FLAG" VARCHAR2(1 BYTE), 
    "PROJECT_ID" NUMBER(15,0), 
    "TASK_ID" NUMBER(15,0), 
    "PERSON_ID" NUMBER(15,0), 
    "ORGANIZATION_ID" NUMBER(15,0), 
    "NON_LABOR_RESOURCE_ORG_ID" NUMBER(15,0), 
    "VENDOR_ID" NUMBER(15,0), 
    "OVERRIDE_TO_ORGANIZATION_ID" NUMBER(15,0), 
    "ASSIGNMENT_ID" NUMBER(15,0), 
    "WORK_TYPE_ID" NUMBER, 
    "PERSON_BUSINESS_GROUP_ID" NUMBER(15,0), 
    "INVENTORY_ITEM_ID" NUMBER, 
    "WIP_RESOURCE_ID" NUMBER, 
    "UNIT_OF_MEASURE" VARCHAR2(30 BYTE), 
    "PO_NUMBER" VARCHAR2(20 BYTE), 
    "PO_HEADER_ID" NUMBER, 
    "PO_LINE_NUM" NUMBER, 
    "PO_LINE_ID" NUMBER, 
    "PERSON_TYPE" VARCHAR2(30 BYTE), 
    "PO_PRICE_TYPE" VARCHAR2(30 BYTE), 
    "ADJUSTED_EXPENDITURE_ITEM_ID" NUMBER(15,0), 
    "FC_DOCUMENT_TYPE" VARCHAR2(3 BYTE), 
    "DOCUMENT_TYPE" VARCHAR2(30 BYTE), 
    "DOCUMENT_DISTRIBUTION_TYPE" VARCHAR2(30 BYTE), 
    "SI_ASSETS_ADDITION_FLAG" VARCHAR2(1 BYTE), 
    "CDL_SYSTEM_REFERENCE5" NUMBER(15,0), 
    "SC_XFER_CODE" VARCHAR2(1 BYTE), 
    "ADJUSTED_TXN_INTERFACE_ID" NUMBER(15,0), 
    "NET_ZERO_ADJUSTMENT_FLAG" VARCHAR2(1 BYTE), 
    "JOB_ID" NUMBER(15,0), 
    "JOB_NAME" VARCHAR2(700 BYTE), 
    "LOCATION_ID" NUMBER(15,0), 
    "LOCATION_CODE" VARCHAR2(20 BYTE), 
    "PAY_ELEMENT_TYPE_ID" NUMBER(9,0), 
    "CBS_ELEMENT_ID" NUMBER(15,0), 
    "CBS_ELEMENT_NAME" VARCHAR2(250 BYTE), 
    "LEGAL_ENTITY_ID" NUMBER(15,0), 
    "RECEIVER_LEGAL_ENTITY_ID" NUMBER(15,0), 
    "LEGAL_ENTITY_NAME" VARCHAR2(240 BYTE), 
    "RECEIVER_LEGAL_ENTITY_NAME" VARCHAR2(240 BYTE)
) 
TABLESPACE "APPS_TS_INTERFACE" ;

/*
CREATE TABLE "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" 
(	
    "TRANSACTION_SOURCE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    "BATCH_NAME" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
    "EXPENDITURE_ENDING_DATE" DATE NOT NULL ENABLE, 
    "EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
    "ORGANIZATION_NAME" VARCHAR2(240 BYTE), 
    "EXPENDITURE_ITEM_DATE" DATE NOT NULL ENABLE, 
    "PROJECT_NUMBER" VARCHAR2(25 BYTE), 
    "TASK_NUMBER" VARCHAR2(25 BYTE), 
    "EXPENDITURE_TYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    "NON_LABOR_RESOURCE" VARCHAR2(20 BYTE), 
    "NON_LABOR_RESOURCE_ORG_NAME" VARCHAR2(240 BYTE), 
    "QUANTITY" NUMBER NOT NULL ENABLE, 
    "RAW_COST" NUMBER, 
    "EXPENDITURE_COMMENT" VARCHAR2(240 BYTE), 
    "TRANSACTION_STATUS_CODE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
    "TRANSACTION_REJECTION_CODE" VARCHAR2(30 BYTE), 
    "EXPENDITURE_ID" NUMBER(15,0), 
    "ORIG_TRANSACTION_REFERENCE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
    "ATTRIBUTE1" VARCHAR2(150 BYTE), 
    "ATTRIBUTE2" VARCHAR2(150 BYTE), 
    "ATTRIBUTE3" VARCHAR2(150 BYTE), 
    "ATTRIBUTE4" VARCHAR2(150 BYTE), 
    "ATTRIBUTE5" VARCHAR2(150 BYTE), 
    "ATTRIBUTE6" VARCHAR2(150 BYTE), 
    "ATTRIBUTE7" VARCHAR2(150 BYTE), 
    "ATTRIBUTE8" VARCHAR2(150 BYTE), 
    "ATTRIBUTE9" VARCHAR2(150 BYTE), 
    "ATTRIBUTE10" VARCHAR2(150 BYTE), 
    "RAW_COST_RATE" NUMBER, 
    "INTERFACE_ID" NUMBER(15,0), 
    "UNMATCHED_NEGATIVE_TXN_FLAG" VARCHAR2(1 BYTE), 
    "EXPENDITURE_ITEM_ID" NUMBER(15,0), 
    "ORG_ID" NUMBER(15,0) DEFAULT NULL, 
    "DR_CODE_COMBINATION_ID" NUMBER(15,0), 
    "CR_CODE_COMBINATION_ID" NUMBER(15,0), 
    "CDL_SYSTEM_REFERENCE1" VARCHAR2(30 BYTE), 
    "CDL_SYSTEM_REFERENCE2" VARCHAR2(30 BYTE), 
    "CDL_SYSTEM_REFERENCE3" VARCHAR2(30 BYTE), 
    "GL_DATE" DATE, 
    "BURDENED_COST" NUMBER, 
    "BURDENED_COST_RATE" NUMBER, 
    "SYSTEM_LINKAGE" VARCHAR2(30 BYTE), 
    "TXN_INTERFACE_ID" NUMBER(15,0) NOT NULL ENABLE, 
    "USER_TRANSACTION_SOURCE" VARCHAR2(80 BYTE), 
    "CREATED_BY" NUMBER(15,0), 
    "CREATION_DATE" DATE, 
    "LAST_UPDATED_BY" NUMBER(15,0), 
    "LAST_UPDATE_DATE" DATE, 
    "RECEIPT_CURRENCY_AMOUNT" NUMBER, 
    "RECEIPT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
    "RECEIPT_EXCHANGE_RATE" NUMBER, 
    "DENOM_CURRENCY_CODE" VARCHAR2(15 BYTE), 
    "DENOM_RAW_COST" NUMBER, 
    "DENOM_BURDENED_COST" NUMBER, 
    "ACCT_RATE_DATE" DATE, 
    "ACCT_RATE_TYPE" VARCHAR2(30 BYTE), 
    "ACCT_EXCHANGE_RATE" NUMBER, 
    "ACCT_RAW_COST" NUMBER, 
    "ACCT_BURDENED_COST" NUMBER, 
    "ACCT_EXCHANGE_ROUNDING_LIMIT" NUMBER, 
    "PROJECT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
    "PROJECT_RATE_DATE" DATE, 
    "PROJECT_RATE_TYPE" VARCHAR2(30 BYTE), 
    "PROJECT_EXCHANGE_RATE" NUMBER, 
    "ORIG_EXP_TXN_REFERENCE1" VARCHAR2(60 BYTE), 
    "ORIG_EXP_TXN_REFERENCE2" VARCHAR2(60 BYTE), 
    "ORIG_EXP_TXN_REFERENCE3" VARCHAR2(60 BYTE), 
    "ORIG_USER_EXP_TXN_REFERENCE" VARCHAR2(60 BYTE), 
    "VENDOR_NUMBER" VARCHAR2(30 BYTE), 
    "OVERRIDE_TO_ORGANIZATION_NAME" VARCHAR2(240 BYTE), 
    "REVERSED_ORIG_TXN_REFERENCE" VARCHAR2(30 BYTE), 
    "BILLABLE_FLAG" VARCHAR2(1 BYTE), 
    "PERSON_BUSINESS_GROUP_NAME" VARCHAR2(240 BYTE), 
    "PROJFUNC_CURRENCY_CODE" VARCHAR2(15 BYTE), 
    "PROJFUNC_COST_RATE_TYPE" VARCHAR2(30 BYTE), 
    "PROJFUNC_COST_RATE_DATE" DATE, 
    "PROJFUNC_COST_EXCHANGE_RATE" NUMBER, 
    "PROJECT_RAW_COST" NUMBER, 
    "PROJECT_BURDENED_COST" NUMBER, 
    "ASSIGNMENT_NAME" VARCHAR2(80 BYTE), 
    "WORK_TYPE_NAME" VARCHAR2(80 BYTE), 
    "CDL_SYSTEM_REFERENCE4" VARCHAR2(30 BYTE), 
    "ACCRUAL_FLAG" VARCHAR2(1 BYTE), 
    "PROJECT_ID" NUMBER(15,0), 
    "TASK_ID" NUMBER(15,0), 
    "PERSON_ID" NUMBER(15,0), 
    "ORGANIZATION_ID" NUMBER(15,0), 
    "NON_LABOR_RESOURCE_ORG_ID" NUMBER(15,0), 
    "VENDOR_ID" NUMBER(15,0), 
    "OVERRIDE_TO_ORGANIZATION_ID" NUMBER(15,0), 
    "ASSIGNMENT_ID" NUMBER(15,0), 
    "WORK_TYPE_ID" NUMBER, 
    "PERSON_BUSINESS_GROUP_ID" NUMBER(15,0), 
    "INVENTORY_ITEM_ID" NUMBER, 
    "WIP_RESOURCE_ID" NUMBER, 
    "UNIT_OF_MEASURE" VARCHAR2(30 BYTE), 
    "PO_NUMBER" VARCHAR2(20 BYTE), 
    "PO_HEADER_ID" NUMBER, 
    "PO_LINE_NUM" NUMBER, 
    "PO_LINE_ID" NUMBER, 
    "PERSON_TYPE" VARCHAR2(30 BYTE), 
    "PO_PRICE_TYPE" VARCHAR2(30 BYTE), 
    "ADJUSTED_EXPENDITURE_ITEM_ID" NUMBER(15,0), 
    "FC_DOCUMENT_TYPE" VARCHAR2(3 BYTE), 
    "DOCUMENT_TYPE" VARCHAR2(30 BYTE), 
    "DOCUMENT_DISTRIBUTION_TYPE" VARCHAR2(30 BYTE), 
    "SI_ASSETS_ADDITION_FLAG" VARCHAR2(1 BYTE), 
    "CDL_SYSTEM_REFERENCE5" NUMBER(15,0), 
    "SC_XFER_CODE" VARCHAR2(1 BYTE), 
    "ADJUSTED_TXN_INTERFACE_ID" NUMBER(15,0), 
    "NET_ZERO_ADJUSTMENT_FLAG" VARCHAR2(1 BYTE), 
    "JOB_ID" NUMBER(15,0), 
    "JOB_NAME" VARCHAR2(700 BYTE), 
    "LOCATION_ID" NUMBER(15,0), 
    "LOCATION_CODE" VARCHAR2(20 BYTE), 
    "PAY_ELEMENT_TYPE_ID" NUMBER(9,0), 
    "CBS_ELEMENT_ID" NUMBER(15,0), 
    "CBS_ELEMENT_NAME" VARCHAR2(250 BYTE), 
    "LEGAL_ENTITY_ID" NUMBER(15,0), 
    "RECEIVER_LEGAL_ENTITY_ID" NUMBER(15,0), 
    "LEGAL_ENTITY_NAME" VARCHAR2(240 BYTE), 
    "RECEIVER_LEGAL_ENTITY_NAME" VARCHAR2(240 BYTE)
) 
TABLESPACE "APPS_TS_INTERFACE" ;
*/

CREATE OR REPLACE PUBLIC SYNONYM XXPA_TRANSACTION_INTERFACE_ALL FOR XXTM.XXPA_TRANSACTION_INTERFACE_ALL;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N1" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("TRANSACTION_SOURCE", "BATCH_NAME", "TRANSACTION_STATUS_CODE") 
TABLESPACE "APPS_TS_INTERFACE" ;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N10" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("PROJECT_NUMBER") 
TABLESPACE "APPS_TS_INTERFACE" ;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N2" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("BATCH_NAME", "EXPENDITURE_ID") 
TABLESPACE "APPS_TS_INTERFACE" ;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N3" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("INTERFACE_ID") 
TABLESPACE "APPS_TS_INTERFACE" ;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N4" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("TRANSACTION_SOURCE", "ORIG_TRANSACTION_REFERENCE") 
TABLESPACE "APPS_TS_INTERFACE" ;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N5" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("EXPENDITURE_ITEM_ID") 
TABLESPACE "APPS_TS_INTERFACE" ;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N6" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("CDL_SYSTEM_REFERENCE2", "CDL_SYSTEM_REFERENCE5", "CDL_SYSTEM_REFERENCE3", "CDL_SYSTEM_REFERENCE4") 
TABLESPACE "APPS_TS_INTERFACE" ;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N7" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("ADJUSTED_EXPENDITURE_ITEM_ID", "FC_DOCUMENT_TYPE") 
TABLESPACE "APPS_TS_INTERFACE" ;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N8" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("NET_ZERO_ADJUSTMENT_FLAG") 
TABLESPACE "APPS_TS_INTERFACE" ;

CREATE INDEX "XXTM"."XXPA_TRANSACTION_INTERFACE_N9" ON "XXTM"."XXPA_TRANSACTION_INTERFACE_ALL" ("EXPENDITURE_ID")
TABLESPACE "APPS_TS_INTERFACE" ;

BEGIN

--    ad_dd.delete_table ('XXTM', 'XXPA_TRANSACTION_INTERFACE_ALL');
    ad_dd.register_table ('XXTM', 'XXPA_TRANSACTION_INTERFACE_ALL', 'T');

    for rec in (
        select 'XXTM' application, 'XXPA_TRANSACTION_INTERFACE_ALL' table_name, fc.column_name,fc.column_sequence,
        case when column_type = 'N' then 'NUMBER'
        when column_type = 'V' then 'VARCHAR2'
        when column_type = 'D' then 'DATE'
        end column_type,
        width,null_allowed_flag,TRANSLATE_FLAG
        from fnd_columns fc,fnd_tables ft 
        where fc.table_id = ft.table_id 
        and ft.table_name = 'PA_TRANSACTION_INTERFACE_ALL' 
        order by column_sequence
    ) loop
        ad_dd.register_column ( rec.application,  rec.table_name, rec.column_name, rec.column_sequence, rec.column_type, rec.width, rec.null_allowed_flag, rec.TRANSLATE_FLAG); 
    end loop;

    commit;
END;