  CREATE TABLE "XXTM"."XXTM_TABLEAU_EXEC_CTL" 
   (	"BATCH_ID" NUMBER, 
	"SEQ" NUMBER, 
	"APPLICATION" VARCHAR2(50 BYTE), 
	"PROGRAM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE),
	"EXEC_CYCLE" VARCHAR2(10 BYTE), 
	"EXEC_DAY" VARCHAR2(10 BYTE), 
	"WAIT" VARCHAR2(10 BYTE),     
	"P1" VARCHAR2(4000 BYTE), 
	"P2" VARCHAR2(4000 BYTE), 
	"P3" VARCHAR2(4000 BYTE), 
	"P4" VARCHAR2(4000 BYTE), 
	"P5" VARCHAR2(4000 BYTE), 
	"P6" VARCHAR2(4000 BYTE), 
	"P7" VARCHAR2(4000 BYTE), 
	"P8" VARCHAR2(4000 BYTE), 
	"P9" VARCHAR2(4000 BYTE), 
	"P10" VARCHAR2(4000 BYTE) 
   );

CREATE OR REPLACE PUBLIC SYNONYM XXTM_TABLEAU_EXEC_CTL FOR XXTM.XXTM_TABLEAU_EXEC_CTL;

Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,20,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXBS_TRX_STATUS.csv','F','SELECT * FROM XXBS_TRX_STATUS_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,30,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAR_CUSTOMER_MASTER.csv','F','SELECT * FROM XXAR_CUSTOMER_MASTER_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,40,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAP_EXPENSE_REPORT.csv','F','SELECT * FROM XXAP_EXPENSE_REPORT_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,50,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXPO_LIST.csv','F','SELECT * FROM XXPO_LIST_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,60,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAP_FUNDING.csv','F','SELECT * FROM XXAP_FUNDING_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,70,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAR_DAY_PAID.csv','F','SELECT * FROM XXAR_DAY_PAID_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,80,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXGL_ACCOUNT_ANALYSIS.csv','F','SELECT * FROM XXGL_ACCOUNT_ANALYSIS_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,90,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAP_SUPPLIER_MASTER.csv','F','SELECT * FROM XXAP_SUPPLIER_MASTER_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,100,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXPA_COST.csv','F','SELECT * FROM XXPA_COST_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,110,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAR_COMMISSION_DEPOSIT.csv','F','SELECT * FROM XXAR_COMMISSION_DEPOSIT_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,120,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAR_COMMISSION_FINAL.csv','F','SELECT * FROM XXAR_COMMISSION_FINAL_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,130,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAR_COMMISSION_CONVERT.csv','F','SELECT * FROM XXAR_COMMISSION_CONVERT_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,140,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAR_AGING.csv','PF','BEGIN XXAR_EXPANDED_AGING_RPT.GET_RECORDS_TABLEAU(:p_dir,:p_file); END',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,150,'XXTM','XXTM_CSV_GENERATOR',null,'D',null,'Y','TABLEAU_STAGE','XXAP_INVOICE_LIST.csv','F','SELECT * FROM XXAP_INVOICE_LIST_V',null,null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,220,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXBS_TRX_STATUS.csv','XXBS_TRX_STATUS','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,230,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAR_CUSTOMER_MASTER.csv','XXAR_CUSTOMER_MASTER','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,240,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAP_EXPENSE_REPORT.csv','XXAP_EXPENSE_REPORT','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,250,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXPO_LIST.csv','XXPO_LIST','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,260,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAP_FUNDING.csv','XXAP_FUNDING','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,270,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAR_DAY_PAID.csv','XXAR_DAY_PAID','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,280,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXGL_ACCOUNT_ANALYSIS.csv','XXGL_ACCOUNT_ANALYSIS','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,290,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAP_SUPPLIER_MASTER.csv','XXAP_SUPPLIER_MASTER','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,300,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXPA_COST.csv','XXPA_COST','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,310,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAR_COMMISSION_DEPOSIT.csv','XXAR_COMMISSION_DEPOSIT','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,320,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAR_COMMISSION_FINAL.csv','XXAR_COMMISSION_FINAL','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,330,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAR_COMMISSION_CONVERT.csv','XXAR_COMMISSION_CONVERT','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,340,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAR_AGING.csv','XXAR_AGING','Y','N',null,null,null,null,null);
Insert into XXTM.XXTM_TABLEAU_EXEC_CTL (BATCH_ID,SEQ,APPLICATION,PROGRAM,DESCRIPTION,EXEC_CYCLE,EXEC_DAY,WAIT,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10) values (1,350,'XXTM','XXTM_STGDATA_IMPORT',null,'D',null,'Y','/TABLEAU/stage/','XXAP_INVOICE_LIST.csv','XXAP_INVOICE_LIST','Y','Y',null,null,null,null,null);
