  CREATE TABLE "XXTM"."XXTM_TABLEAU_PARAMS" 
   (	"PARAMS_NAME" VARCHAR2(240 BYTE), 
	"VALUE" VARCHAR2(240 BYTE), 
	"DATE_VALUE" DATE
   );

CREATE OR REPLACE PUBLIC SYNONYM XXTM_TABLEAU_PARAMS FOR XXTM.XXTM_TABLEAU_PARAMS;

Insert into XXTM.XXTM_TABLEAU_PARAMS (PARAMS_NAME,VALUE,DATE_VALUE) values ('CUTOFFDATE',null,to_date('18-MAY-2021 00:00:00','DD-MON-YYYY HH24:MI:SS'));
