--DROP TABLE XXTM.XXTM_WEBADI_ERR;

CREATE TABLE XXTM.XXTM_WEBADI_ERR
(
  RUN_ID                      NUMBER,
  ERROR_CODE                  VARCHAR2(30 BYTE),
  ERROR_MESSAGE               VARCHAR2(1000 BYTE),
  SOURCE                      VARCHAR2(100 BYTE),
  CREATED_BY                  NUMBER(15)        NOT NULL,
  CREATION_DATE               DATE              NOT NULL
);

CREATE SEQUENCE APPS.XXTM_WEBADI_ERR_ID_S;

CREATE INDEX XXTM.XXTM_WEBADI_ERR_N1 ON XXTM.XXTM_WEBADI_ERR
(RUN_ID);

CREATE OR REPLACE PUBLIC SYNONYM XXTM_WEBADI_ERR FOR XXTM.XXTM_WEBADI_ERR;
